[package]
name = "xtask"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
regex = "1"
gltf = { version = "1.4", default-features = false, features = ["import", "utils", "names"] }
game_core = { workspace = true }
game_protocol = { workspace = true }
game_schema = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
ron = { workspace = true }
sha2 = "0.10"
