use spacetimedb::{view, ViewContext, SpacetimeType};

use crate::tables::EntityTransform;

// Import view-access traits for table accessors (generated by #[table] macros).
use crate::tables::{
    client_sequence__view,
    entity_region__view,
    entity_transform__view,
};

// ── Per-User Region Info ────────────────────────────────────────────
// Custom return type instead of EntityRegion (private table type may
// not appear in generated client bindings).

#[derive(SpacetimeType)]
pub struct RegionInfo {
    pub entity_id: u64,
    pub region_x: i32,
    pub region_z: i32,
    pub layer: u32,
}

// ── my_region ───────────────────────────────────────────────────────
// Returns the caller's own region assignment.  The client learns which
// cell it occupies without being able to see anyone else's region.

#[view(accessor = my_region, public)]
fn my_region(ctx: &ViewContext) -> Option<RegionInfo> {
    let seq = ctx.db.client_sequence()
        .client_identity().find(&ctx.sender())?;
    let er = ctx.db.entity_region()
        .entity_id().find(&seq.entity_id)?;
    Some(RegionInfo {
        entity_id: er.entity_id,
        region_x: er.region_x,
        region_z: er.region_z,
        layer: er.layer,
    })
}

// ── nearby_transforms ───────────────────────────────────────────────
// Returns transforms for every entity in the caller's cell + layer.
// This is the AOI filter: the client only sees entities sharing its
// region and layer.  Distant entities and other-layer entities are
// invisible.
//
// Access path (all indexed):
//   ctx.sender()         → client_sequence PK   (Identity)
//   seq.entity_id        → entity_region  PK   (u64)
//   region.region_x      → entity_region  btree (i32)  ← prefix scan
//   er.entity_id         → entity_transform PK  (u64)

#[view(accessor = nearby_transforms, public)]
fn nearby_transforms(ctx: &ViewContext) -> Vec<EntityTransform> {
    let Some(seq) = ctx.db.client_sequence()
        .client_identity().find(&ctx.sender()) else { return vec![]; };
    let Some(region) = ctx.db.entity_region()
        .entity_id().find(&seq.entity_id) else { return vec![]; };
    ctx.db.entity_region().region_x().filter(&region.region_x)
        .filter(|er| er.region_z == region.region_z && er.layer == region.layer)
        .filter_map(|er| ctx.db.entity_transform()
            .entity_id().find(&er.entity_id))
        .collect()
}
