use spacetimedb::{view, ViewContext, SpacetimeType};

use crate::tables::{Entity, EntityHealth, EntityTransform};

// Import view-access traits for table accessors (generated by #[table] macros).
use crate::tables::{
    client_sequence__view,
    entity__view,
    entity_health__view,
    entity_region__view,
    entity_team__view,
    entity_transform__view,
    stealthed_entity__view,
};

// ── Per-User Region Info ────────────────────────────────────────────
// Custom return type instead of EntityRegion (private table type may
// not appear in generated client bindings).

#[derive(SpacetimeType)]
pub struct RegionInfo {
    pub entity_id: u64,
    pub region_x: i32,
    pub region_z: i32,
    pub layer: u32,
}

// ── my_region ───────────────────────────────────────────────────────
// Returns the caller's own region assignment.  The client learns which
// cell it occupies without being able to see anyone else's region.

#[view(accessor = my_region, public)]
fn my_region(ctx: &ViewContext) -> Option<RegionInfo> {
    let seq = ctx.db.client_sequence()
        .client_identity().find(&ctx.sender())?;
    let er = ctx.db.entity_region()
        .entity_id().find(&seq.entity_id)?;
    Some(RegionInfo {
        entity_id: er.entity_id,
        region_x: er.region_x,
        region_z: er.region_z,
        layer: er.layer,
    })
}

// ── nearby_transforms ───────────────────────────────────────────────
// Returns transforms for every entity in the caller's cell + layer.
// This is the AOI filter: the client only sees entities sharing its
// region and layer.  Distant entities, other-layer entities, and
// enemy-stealthed entities are invisible.
//
// Access path (all indexed):
//   ctx.sender()         → client_sequence PK   (Identity)
//   seq.entity_id        → entity_region  PK   (u64)
//   seq.entity_id        → entity_team    PK   (u64)  ← caller's team
//   by_region            → composite btree (layer, region_x, region_z)
//                          3 range scans: pin layer + x, range z
//   er.entity_id         → stealthed_entity PK (u64)  ← stealth check
//   er.entity_id         → entity_transform PK  (u64)

#[view(accessor = nearby_transforms, public)]
fn nearby_transforms(ctx: &ViewContext) -> Vec<EntityTransform> {
    let Some(seq) = ctx.db.client_sequence()
        .client_identity().find(&ctx.sender()) else { return vec![]; };
    let Some(region) = ctx.db.entity_region()
        .entity_id().find(&seq.entity_id) else { return vec![]; };

    // Look up caller's team once before the loop.
    let my_team = ctx.db.entity_team()
        .entity_id().find(&seq.entity_id)
        .map(|t| t.team_id);

    let z_start = region.region_z - 1;
    let z_end = region.region_z + 1;
    let mut result = Vec::new();
    for dx in -1..=1i32 {
        let target_x = region.region_x + dx;
        for er in ctx.db.entity_region().by_region()
            .filter((region.layer, target_x, z_start..=z_end))
        {
            // Stealth check: stealthed entities are visible only to allies.
            if let Some(stealth) = ctx.db.stealthed_entity()
                .entity_id().find(&er.entity_id)
            {
                if my_team != Some(stealth.team_id) {
                    continue;
                }
            }
            if let Some(tf) = ctx.db.entity_transform()
                .entity_id().find(&er.entity_id)
            {
                result.push(tf);
            }
        }
    }
    result
}

// ── nearby_health ───────────────────────────────────────────────────
// Returns health for every entity in the caller's AOI (cell + layer),
// with the same stealth filter as nearby_transforms.  Clients use this
// instead of subscribing to the raw entity_health table.
//
// Access path: identical to nearby_transforms, final lookup is
//   er.entity_id → entity_health PK  (u64)

#[view(accessor = nearby_health, public)]
fn nearby_health(ctx: &ViewContext) -> Vec<EntityHealth> {
    let Some(seq) = ctx.db.client_sequence()
        .client_identity().find(&ctx.sender()) else { return vec![]; };
    let Some(region) = ctx.db.entity_region()
        .entity_id().find(&seq.entity_id) else { return vec![]; };

    let my_team = ctx.db.entity_team()
        .entity_id().find(&seq.entity_id)
        .map(|t| t.team_id);

    let z_start = region.region_z - 1;
    let z_end = region.region_z + 1;
    let mut result = Vec::new();
    for dx in -1..=1i32 {
        let target_x = region.region_x + dx;
        for er in ctx.db.entity_region().by_region()
            .filter((region.layer, target_x, z_start..=z_end))
        {
            if let Some(stealth) = ctx.db.stealthed_entity()
                .entity_id().find(&er.entity_id)
            {
                if my_team != Some(stealth.team_id) {
                    continue;
                }
            }
            if let Some(h) = ctx.db.entity_health()
                .entity_id().find(&er.entity_id)
            {
                result.push(h);
            }
        }
    }
    result
}

// ── nearby_entities ─────────────────────────────────────────────────
// Returns entity metadata for every entity in the caller's AOI
// (cell + layer), with the same stealth filter.  Clients use this
// instead of subscribing to the raw entity table.
//
// Access path: identical to nearby_transforms, final lookup is
//   er.entity_id → entity PK  (u64)

#[view(accessor = nearby_entities, public)]
fn nearby_entities(ctx: &ViewContext) -> Vec<Entity> {
    let Some(seq) = ctx.db.client_sequence()
        .client_identity().find(&ctx.sender()) else { return vec![]; };
    let Some(region) = ctx.db.entity_region()
        .entity_id().find(&seq.entity_id) else { return vec![]; };

    let my_team = ctx.db.entity_team()
        .entity_id().find(&seq.entity_id)
        .map(|t| t.team_id);

    let z_start = region.region_z - 1;
    let z_end = region.region_z + 1;
    let mut result = Vec::new();
    for dx in -1..=1i32 {
        let target_x = region.region_x + dx;
        for er in ctx.db.entity_region().by_region()
            .filter((region.layer, target_x, z_start..=z_end))
        {
            if let Some(stealth) = ctx.db.stealthed_entity()
                .entity_id().find(&er.entity_id)
            {
                if my_team != Some(stealth.team_id) {
                    continue;
                }
            }
            if let Some(e) = ctx.db.entity()
                .entity_id().find(&er.entity_id)
            {
                result.push(e);
            }
        }
    }
    result
}
