// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct AddRespawnPointArgs {
    pub layer: u32,
    pub pos_x: f32,
    pub pos_y: f32,
    pub pos_z: f32,
    pub name: String,
}

impl From<AddRespawnPointArgs> for super::Reducer {
    fn from(args: AddRespawnPointArgs) -> Self {
        Self::AddRespawnPoint {
            layer: args.layer,
            pos_x: args.pos_x,
            pos_y: args.pos_y,
            pos_z: args.pos_z,
            name: args.name,
        }
    }
}

impl __sdk::InModule for AddRespawnPointArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `add_respawn_point`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait add_respawn_point {
    /// Request that the remote module invoke the reducer `add_respawn_point` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`add_respawn_point:add_respawn_point_then`] to run a callback after the reducer completes.
    fn add_respawn_point(
        &self,
        layer: u32,
        pos_x: f32,
        pos_y: f32,
        pos_z: f32,
        name: String,
    ) -> __sdk::Result<()> {
        self.add_respawn_point_then(layer, pos_x, pos_y, pos_z, name, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `add_respawn_point` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn add_respawn_point_then(
        &self,
        layer: u32,
        pos_x: f32,
        pos_y: f32,
        pos_z: f32,
        name: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl add_respawn_point for super::RemoteReducers {
    fn add_respawn_point_then(
        &self,
        layer: u32,
        pos_x: f32,
        pos_y: f32,
        pos_z: f32,
        name: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            AddRespawnPointArgs {
                layer,
                pos_x,
                pos_y,
                pos_z,
                name,
            },
            callback,
        )
    }
}
