// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Bank {
    pub row_id: u64,
    pub owner_entity: u64,
    pub slot_index: u32,
    pub item_id: u32,
    pub quantity: u32,
}

impl __sdk::InModule for Bank {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Bank`.
///
/// Provides typed access to columns for query building.
pub struct BankCols {
    pub row_id: __sdk::__query_builder::Col<Bank, u64>,
    pub owner_entity: __sdk::__query_builder::Col<Bank, u64>,
    pub slot_index: __sdk::__query_builder::Col<Bank, u32>,
    pub item_id: __sdk::__query_builder::Col<Bank, u32>,
    pub quantity: __sdk::__query_builder::Col<Bank, u32>,
}

impl __sdk::__query_builder::HasCols for Bank {
    type Cols = BankCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        BankCols {
            row_id: __sdk::__query_builder::Col::new(table_name, "row_id"),
            owner_entity: __sdk::__query_builder::Col::new(table_name, "owner_entity"),
            slot_index: __sdk::__query_builder::Col::new(table_name, "slot_index"),
            item_id: __sdk::__query_builder::Col::new(table_name, "item_id"),
            quantity: __sdk::__query_builder::Col::new(table_name, "quantity"),
        }
    }
}

/// Indexed column accessor struct for the table `Bank`.
///
/// Provides typed access to indexed columns for query building.
pub struct BankIxCols {
    pub row_id: __sdk::__query_builder::IxCol<Bank, u64>,
}

impl __sdk::__query_builder::HasIxCols for Bank {
    type IxCols = BankIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        BankIxCols {
            row_id: __sdk::__query_builder::IxCol::new(table_name, "row_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Bank {}
