// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct BossPhaseUpdateInput {
    pub boss_entity_id: u64,
    pub phase: u32,
    pub entered_at_tick: u64,
}

impl __sdk::InModule for BossPhaseUpdateInput {
    type Module = super::RemoteModule;
}
