// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct BossPhase {
    pub boss_entity_id: u64,
    pub phase: u32,
    pub entered_at_tick: u64,
}

impl __sdk::InModule for BossPhase {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `BossPhase`.
///
/// Provides typed access to columns for query building.
pub struct BossPhaseCols {
    pub boss_entity_id: __sdk::__query_builder::Col<BossPhase, u64>,
    pub phase: __sdk::__query_builder::Col<BossPhase, u32>,
    pub entered_at_tick: __sdk::__query_builder::Col<BossPhase, u64>,
}

impl __sdk::__query_builder::HasCols for BossPhase {
    type Cols = BossPhaseCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        BossPhaseCols {
            boss_entity_id: __sdk::__query_builder::Col::new(table_name, "boss_entity_id"),
            phase: __sdk::__query_builder::Col::new(table_name, "phase"),
            entered_at_tick: __sdk::__query_builder::Col::new(table_name, "entered_at_tick"),
        }
    }
}

/// Indexed column accessor struct for the table `BossPhase`.
///
/// Provides typed access to indexed columns for query building.
pub struct BossPhaseIxCols {
    pub boss_entity_id: __sdk::__query_builder::IxCol<BossPhase, u64>,
}

impl __sdk::__query_builder::HasIxCols for BossPhase {
    type IxCols = BossPhaseIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        BossPhaseIxCols {
            boss_entity_id: __sdk::__query_builder::IxCol::new(table_name, "boss_entity_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for BossPhase {}
