// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::boss_phase_type::BossPhase;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `boss_phase`.
///
/// Obtain a handle from the [`BossPhaseTableAccess::boss_phase`] method on [`super::RemoteTables`],
/// like `ctx.db.boss_phase()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.boss_phase().on_insert(...)`.
pub struct BossPhaseTableHandle<'ctx> {
    imp: __sdk::TableHandle<BossPhase>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `boss_phase`.
///
/// Implemented for [`super::RemoteTables`].
pub trait BossPhaseTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`BossPhaseTableHandle`], which mediates access to the table `boss_phase`.
    fn boss_phase(&self) -> BossPhaseTableHandle<'_>;
}

impl BossPhaseTableAccess for super::RemoteTables {
    fn boss_phase(&self) -> BossPhaseTableHandle<'_> {
        BossPhaseTableHandle {
            imp: self.imp.get_table::<BossPhase>("boss_phase"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct BossPhaseInsertCallbackId(__sdk::CallbackId);
pub struct BossPhaseDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for BossPhaseTableHandle<'ctx> {
    type Row = BossPhase;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = BossPhase> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = BossPhaseInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> BossPhaseInsertCallbackId {
        BossPhaseInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: BossPhaseInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = BossPhaseDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> BossPhaseDeleteCallbackId {
        BossPhaseDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: BossPhaseDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct BossPhaseUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for BossPhaseTableHandle<'ctx> {
    type UpdateCallbackId = BossPhaseUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> BossPhaseUpdateCallbackId {
        BossPhaseUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: BossPhaseUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `boss_entity_id` unique index on the table `boss_phase`,
/// which allows point queries on the field of the same name
/// via the [`BossPhaseBossEntityIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.boss_phase().boss_entity_id().find(...)`.
pub struct BossPhaseBossEntityIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<BossPhase, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> BossPhaseTableHandle<'ctx> {
    /// Get a handle on the `boss_entity_id` unique index on the table `boss_phase`.
    pub fn boss_entity_id(&self) -> BossPhaseBossEntityIdUnique<'ctx> {
        BossPhaseBossEntityIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("boss_entity_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> BossPhaseBossEntityIdUnique<'ctx> {
    /// Find the subscribed row whose `boss_entity_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<BossPhase> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<BossPhase>("boss_phase");
    _table.add_unique_constraint::<u64>("boss_entity_id", |row| &row.boss_entity_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<BossPhase>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<BossPhase>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `BossPhase`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait boss_phaseQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `BossPhase`.
    fn boss_phase(&self) -> __sdk::__query_builder::Table<BossPhase>;
}

impl boss_phaseQueryTableAccess for __sdk::QueryTableAccessor {
    fn boss_phase(&self) -> __sdk::__query_builder::Table<BossPhase> {
        __sdk::__query_builder::Table::new("boss_phase")
    }
}
