// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::ability_cancelled_data_type::AbilityCancelledData;
use super::area_telegraph_data_type::AreaTelegraphData;
use super::blocked_data_type::BlockedData;
use super::buff_applied_data_type::BuffAppliedData;
use super::cast_start_data_type::CastStartData;
use super::cc_cleared_data_type::CcClearedData;
use super::cc_immune_data_type::CcImmuneData;
use super::charge_start_data_type::ChargeStartData;
use super::charge_tier_reached_data_type::ChargeTierReachedData;
use super::cleansed_data_type::CleansedData;
use super::contact_hitbox_spawned_data_type::ContactHitboxSpawnedData;
use super::covered_data_type::CoveredData;
use super::damage_data_type::DamageData;
use super::encounter_cue_data_type::EncounterCueData;
use super::feared_data_type::FearedData;
use super::hazard_spawned_data_type::HazardSpawnedData;
use super::healed_data_type::HealedData;
use super::knockback_data_type::KnockbackData;
use super::knocked_down_data_type::KnockedDownData;
use super::lock_on_canceled_data_type::LockOnCanceledData;
use super::lock_on_fired_data_type::LockOnFiredData;
use super::lock_on_session_started_data_type::LockOnSessionStartedData;
use super::projectile_launched_data_type::ProjectileLaunchedData;
use super::silenced_data_type::SilencedData;
use super::slept_data_type::SleptData;
use super::stunned_data_type::StunnedData;
use super::telegraph_warning_data_type::TelegraphWarningData;
use super::teleported_data_type::TeleportedData;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub enum CombatEventKind {
    CastStart(CastStartData),

    ChargeStart(ChargeStartData),

    ChargeTierReached(ChargeTierReachedData),

    BlockStart,

    BlockEnd,

    Damage(DamageData),

    Healed(HealedData),

    SkillHit(u32),

    BuffApplied(BuffAppliedData),

    BuffExpired(u32),

    EntityDied(Option<u64>),

    Dodged(u32),

    Blocked(BlockedData),

    Covered(CoveredData),

    TelegraphWarning(TelegraphWarningData),

    AreaTelegraph(AreaTelegraphData),

    EncounterCue(EncounterCueData),

    LockOnAcquired,

    LockOnSessionStarted(LockOnSessionStartedData),

    LockOnCanceled(LockOnCanceledData),

    LockOnFired(LockOnFiredData),

    ProjectileLaunched(ProjectileLaunchedData),

    HazardSpawned(HazardSpawnedData),

    ContactHitboxSpawned(ContactHitboxSpawnedData),

    SkillObjectRemoved(u64),

    Teleported(TeleportedData),

    Knockback(KnockbackData),

    Launched,

    Stunned(StunnedData),

    KnockedDown(KnockedDownData),

    Pulled,

    Slept(SleptData),

    Silenced(SilencedData),

    Feared(FearedData),

    StabilityConsumed(u32),

    WeaponSwapped(u8),

    CcCleared(CcClearedData),

    Cleansed(CleansedData),

    Stunbreak,

    CcImmune(CcImmuneData),

    AbilityCancelled(AbilityCancelledData),
}

impl __sdk::InModule for CombatEventKind {
    type Module = super::RemoteModule;
}
