// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct CreateInstanceArgs {
    pub template_id: String,
    pub max_players: u32,
}

impl From<CreateInstanceArgs> for super::Reducer {
    fn from(args: CreateInstanceArgs) -> Self {
        Self::CreateInstance {
            template_id: args.template_id,
            max_players: args.max_players,
        }
    }
}

impl __sdk::InModule for CreateInstanceArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `create_instance`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait create_instance {
    /// Request that the remote module invoke the reducer `create_instance` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`create_instance:create_instance_then`] to run a callback after the reducer completes.
    fn create_instance(&self, template_id: String, max_players: u32) -> __sdk::Result<()> {
        self.create_instance_then(template_id, max_players, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `create_instance` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn create_instance_then(
        &self,
        template_id: String,
        max_players: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl create_instance for super::RemoteReducers {
    fn create_instance_then(
        &self,
        template_id: String,
        max_players: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            CreateInstanceArgs {
                template_id,
                max_players,
            },
            callback,
        )
    }
}
