// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct DeathState {
    pub entity_id: u64,
    pub died_at_tick: u64,
    pub respawn_at_tick: u64,
    pub killer_entity: Option<u64>,
    pub layer: u32,
    pub death_pos_x: f32,
    pub death_pos_y: f32,
    pub death_pos_z: f32,
}

impl __sdk::InModule for DeathState {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `DeathState`.
///
/// Provides typed access to columns for query building.
pub struct DeathStateCols {
    pub entity_id: __sdk::__query_builder::Col<DeathState, u64>,
    pub died_at_tick: __sdk::__query_builder::Col<DeathState, u64>,
    pub respawn_at_tick: __sdk::__query_builder::Col<DeathState, u64>,
    pub killer_entity: __sdk::__query_builder::Col<DeathState, Option<u64>>,
    pub layer: __sdk::__query_builder::Col<DeathState, u32>,
    pub death_pos_x: __sdk::__query_builder::Col<DeathState, f32>,
    pub death_pos_y: __sdk::__query_builder::Col<DeathState, f32>,
    pub death_pos_z: __sdk::__query_builder::Col<DeathState, f32>,
}

impl __sdk::__query_builder::HasCols for DeathState {
    type Cols = DeathStateCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        DeathStateCols {
            entity_id: __sdk::__query_builder::Col::new(table_name, "entity_id"),
            died_at_tick: __sdk::__query_builder::Col::new(table_name, "died_at_tick"),
            respawn_at_tick: __sdk::__query_builder::Col::new(table_name, "respawn_at_tick"),
            killer_entity: __sdk::__query_builder::Col::new(table_name, "killer_entity"),
            layer: __sdk::__query_builder::Col::new(table_name, "layer"),
            death_pos_x: __sdk::__query_builder::Col::new(table_name, "death_pos_x"),
            death_pos_y: __sdk::__query_builder::Col::new(table_name, "death_pos_y"),
            death_pos_z: __sdk::__query_builder::Col::new(table_name, "death_pos_z"),
        }
    }
}

/// Indexed column accessor struct for the table `DeathState`.
///
/// Provides typed access to indexed columns for query building.
pub struct DeathStateIxCols {
    pub entity_id: __sdk::__query_builder::IxCol<DeathState, u64>,
}

impl __sdk::__query_builder::HasIxCols for DeathState {
    type IxCols = DeathStateIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        DeathStateIxCols {
            entity_id: __sdk::__query_builder::IxCol::new(table_name, "entity_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for DeathState {}
