// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct DebugSetHpArgs {
    pub entity_id: u64,
    pub hp: f32,
    pub max_hp: f32,
}

impl From<DebugSetHpArgs> for super::Reducer {
    fn from(args: DebugSetHpArgs) -> Self {
        Self::DebugSetHp {
            entity_id: args.entity_id,
            hp: args.hp,
            max_hp: args.max_hp,
        }
    }
}

impl __sdk::InModule for DebugSetHpArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `debug_set_hp`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait debug_set_hp {
    /// Request that the remote module invoke the reducer `debug_set_hp` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`debug_set_hp:debug_set_hp_then`] to run a callback after the reducer completes.
    fn debug_set_hp(&self, entity_id: u64, hp: f32, max_hp: f32) -> __sdk::Result<()> {
        self.debug_set_hp_then(entity_id, hp, max_hp, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `debug_set_hp` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn debug_set_hp_then(
        &self,
        entity_id: u64,
        hp: f32,
        max_hp: f32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl debug_set_hp for super::RemoteReducers {
    fn debug_set_hp_then(
        &self,
        entity_id: u64,
        hp: f32,
        max_hp: f32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            DebugSetHpArgs {
                entity_id,
                hp,
                max_hp,
            },
            callback,
        )
    }
}
