// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct DebugSpawnBossArgs {
    pub pos_x: f32,
    pub pos_y: f32,
    pub pos_z: f32,
    pub max_hp: f32,
}

impl From<DebugSpawnBossArgs> for super::Reducer {
    fn from(args: DebugSpawnBossArgs) -> Self {
        Self::DebugSpawnBoss {
            pos_x: args.pos_x,
            pos_y: args.pos_y,
            pos_z: args.pos_z,
            max_hp: args.max_hp,
        }
    }
}

impl __sdk::InModule for DebugSpawnBossArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `debug_spawn_boss`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait debug_spawn_boss {
    /// Request that the remote module invoke the reducer `debug_spawn_boss` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`debug_spawn_boss:debug_spawn_boss_then`] to run a callback after the reducer completes.
    fn debug_spawn_boss(
        &self,
        pos_x: f32,
        pos_y: f32,
        pos_z: f32,
        max_hp: f32,
    ) -> __sdk::Result<()> {
        self.debug_spawn_boss_then(pos_x, pos_y, pos_z, max_hp, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `debug_spawn_boss` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn debug_spawn_boss_then(
        &self,
        pos_x: f32,
        pos_y: f32,
        pos_z: f32,
        max_hp: f32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl debug_spawn_boss for super::RemoteReducers {
    fn debug_spawn_boss_then(
        &self,
        pos_x: f32,
        pos_y: f32,
        pos_z: f32,
        max_hp: f32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            DebugSpawnBossArgs {
                pos_x,
                pos_y,
                pos_z,
                max_hp,
            },
            callback,
        )
    }
}
