// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct DebugJoinInstanceArgs {
    pub entity_id: u64,
    pub instance_id: u64,
}

impl From<DebugJoinInstanceArgs> for super::Reducer {
    fn from(args: DebugJoinInstanceArgs) -> Self {
        Self::DebugJoinInstance {
            entity_id: args.entity_id,
            instance_id: args.instance_id,
        }
    }
}

impl __sdk::InModule for DebugJoinInstanceArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `debug_join_instance`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait debug_join_instance {
    /// Request that the remote module invoke the reducer `debug_join_instance` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`debug_join_instance:debug_join_instance_then`] to run a callback after the reducer completes.
    fn debug_join_instance(&self, entity_id: u64, instance_id: u64) -> __sdk::Result<()> {
        self.debug_join_instance_then(entity_id, instance_id, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `debug_join_instance` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn debug_join_instance_then(
        &self,
        entity_id: u64,
        instance_id: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl debug_join_instance for super::RemoteReducers {
    fn debug_join_instance_then(
        &self,
        entity_id: u64,
        instance_id: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            DebugJoinInstanceArgs {
                entity_id,
                instance_id,
            },
            callback,
        )
    }
}
