// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct DebugAddZoneKillArgs {
    pub layer: u32,
    pub region_x: i32,
    pub region_z: i32,
    pub count: u32,
}

impl From<DebugAddZoneKillArgs> for super::Reducer {
    fn from(args: DebugAddZoneKillArgs) -> Self {
        Self::DebugAddZoneKill {
            layer: args.layer,
            region_x: args.region_x,
            region_z: args.region_z,
            count: args.count,
        }
    }
}

impl __sdk::InModule for DebugAddZoneKillArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `debug_add_zone_kill`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait debug_add_zone_kill {
    /// Request that the remote module invoke the reducer `debug_add_zone_kill` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`debug_add_zone_kill:debug_add_zone_kill_then`] to run a callback after the reducer completes.
    fn debug_add_zone_kill(
        &self,
        layer: u32,
        region_x: i32,
        region_z: i32,
        count: u32,
    ) -> __sdk::Result<()> {
        self.debug_add_zone_kill_then(layer, region_x, region_z, count, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `debug_add_zone_kill` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn debug_add_zone_kill_then(
        &self,
        layer: u32,
        region_x: i32,
        region_z: i32,
        count: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl debug_add_zone_kill for super::RemoteReducers {
    fn debug_add_zone_kill_then(
        &self,
        layer: u32,
        region_x: i32,
        region_z: i32,
        count: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            DebugAddZoneKillArgs {
                layer,
                region_x,
                region_z,
                count,
            },
            callback,
        )
    }
}
