// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct DebugSpawnCombatArgs {
    pub pair_count: u32,
    pub pair_spacing: f32,
    pub no_chase: bool,
}

impl From<DebugSpawnCombatArgs> for super::Reducer {
    fn from(args: DebugSpawnCombatArgs) -> Self {
        Self::DebugSpawnCombat {
            pair_count: args.pair_count,
            pair_spacing: args.pair_spacing,
            no_chase: args.no_chase,
        }
    }
}

impl __sdk::InModule for DebugSpawnCombatArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `debug_spawn_combat`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait debug_spawn_combat {
    /// Request that the remote module invoke the reducer `debug_spawn_combat` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`debug_spawn_combat:debug_spawn_combat_then`] to run a callback after the reducer completes.
    fn debug_spawn_combat(
        &self,
        pair_count: u32,
        pair_spacing: f32,
        no_chase: bool,
    ) -> __sdk::Result<()> {
        self.debug_spawn_combat_then(pair_count, pair_spacing, no_chase, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `debug_spawn_combat` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn debug_spawn_combat_then(
        &self,
        pair_count: u32,
        pair_spacing: f32,
        no_chase: bool,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl debug_spawn_combat for super::RemoteReducers {
    fn debug_spawn_combat_then(
        &self,
        pair_count: u32,
        pair_spacing: f32,
        no_chase: bool,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            DebugSpawnCombatArgs {
                pair_count,
                pair_spacing,
                no_chase,
            },
            callback,
        )
    }
}
