// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct DebugSetTeamArgs {
    pub entity_id: u64,
    pub team_id: u32,
}

impl From<DebugSetTeamArgs> for super::Reducer {
    fn from(args: DebugSetTeamArgs) -> Self {
        Self::DebugSetTeam {
            entity_id: args.entity_id,
            team_id: args.team_id,
        }
    }
}

impl __sdk::InModule for DebugSetTeamArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `debug_set_team`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait debug_set_team {
    /// Request that the remote module invoke the reducer `debug_set_team` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`debug_set_team:debug_set_team_then`] to run a callback after the reducer completes.
    fn debug_set_team(&self, entity_id: u64, team_id: u32) -> __sdk::Result<()> {
        self.debug_set_team_then(entity_id, team_id, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `debug_set_team` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn debug_set_team_then(
        &self,
        entity_id: u64,
        team_id: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl debug_set_team for super::RemoteReducers {
    fn debug_set_team_then(
        &self,
        entity_id: u64,
        team_id: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(DebugSetTeamArgs { entity_id, team_id }, callback)
    }
}
