// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct DebugApplyBuffArgs {
    pub entity_id: u64,
    pub buff_id: u32,
    pub stacks: u32,
    pub duration_ticks: u32,
    pub mod_stealth: Option<bool>,
}

impl From<DebugApplyBuffArgs> for super::Reducer {
    fn from(args: DebugApplyBuffArgs) -> Self {
        Self::DebugApplyBuff {
            entity_id: args.entity_id,
            buff_id: args.buff_id,
            stacks: args.stacks,
            duration_ticks: args.duration_ticks,
            mod_stealth: args.mod_stealth,
        }
    }
}

impl __sdk::InModule for DebugApplyBuffArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `debug_apply_buff`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait debug_apply_buff {
    /// Request that the remote module invoke the reducer `debug_apply_buff` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`debug_apply_buff:debug_apply_buff_then`] to run a callback after the reducer completes.
    fn debug_apply_buff(
        &self,
        entity_id: u64,
        buff_id: u32,
        stacks: u32,
        duration_ticks: u32,
        mod_stealth: Option<bool>,
    ) -> __sdk::Result<()> {
        self.debug_apply_buff_then(
            entity_id,
            buff_id,
            stacks,
            duration_ticks,
            mod_stealth,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `debug_apply_buff` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn debug_apply_buff_then(
        &self,
        entity_id: u64,
        buff_id: u32,
        stacks: u32,
        duration_ticks: u32,
        mod_stealth: Option<bool>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl debug_apply_buff for super::RemoteReducers {
    fn debug_apply_buff_then(
        &self,
        entity_id: u64,
        buff_id: u32,
        stacks: u32,
        duration_ticks: u32,
        mod_stealth: Option<bool>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            DebugApplyBuffArgs {
                entity_id,
                buff_id,
                stacks,
                duration_ticks,
                mod_stealth,
            },
            callback,
        )
    }
}
