// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct DebugGrantItemArgs {
    pub entity_id: u64,
    pub item_id: u32,
    pub quantity: u32,
}

impl From<DebugGrantItemArgs> for super::Reducer {
    fn from(args: DebugGrantItemArgs) -> Self {
        Self::DebugGrantItem {
            entity_id: args.entity_id,
            item_id: args.item_id,
            quantity: args.quantity,
        }
    }
}

impl __sdk::InModule for DebugGrantItemArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `debug_grant_item`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait debug_grant_item {
    /// Request that the remote module invoke the reducer `debug_grant_item` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`debug_grant_item:debug_grant_item_then`] to run a callback after the reducer completes.
    fn debug_grant_item(&self, entity_id: u64, item_id: u32, quantity: u32) -> __sdk::Result<()> {
        self.debug_grant_item_then(entity_id, item_id, quantity, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `debug_grant_item` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn debug_grant_item_then(
        &self,
        entity_id: u64,
        item_id: u32,
        quantity: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl debug_grant_item for super::RemoteReducers {
    fn debug_grant_item_then(
        &self,
        entity_id: u64,
        item_id: u32,
        quantity: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            DebugGrantItemArgs {
                entity_id,
                item_id,
                quantity,
            },
            callback,
        )
    }
}
