// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct DebugSpawnManyArgs {
    pub count: u32,
    pub spacing: f32,
}

impl From<DebugSpawnManyArgs> for super::Reducer {
    fn from(args: DebugSpawnManyArgs) -> Self {
        Self::DebugSpawnMany {
            count: args.count,
            spacing: args.spacing,
        }
    }
}

impl __sdk::InModule for DebugSpawnManyArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `debug_spawn_many`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait debug_spawn_many {
    /// Request that the remote module invoke the reducer `debug_spawn_many` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`debug_spawn_many:debug_spawn_many_then`] to run a callback after the reducer completes.
    fn debug_spawn_many(&self, count: u32, spacing: f32) -> __sdk::Result<()> {
        self.debug_spawn_many_then(count, spacing, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `debug_spawn_many` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn debug_spawn_many_then(
        &self,
        count: u32,
        spacing: f32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl debug_spawn_many for super::RemoteReducers {
    fn debug_spawn_many_then(
        &self,
        count: u32,
        spacing: f32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(DebugSpawnManyArgs { count, spacing }, callback)
    }
}
