// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct DeclinePartyInviteArgs {
    pub invite_id: u64,
}

impl From<DeclinePartyInviteArgs> for super::Reducer {
    fn from(args: DeclinePartyInviteArgs) -> Self {
        Self::DeclinePartyInvite {
            invite_id: args.invite_id,
        }
    }
}

impl __sdk::InModule for DeclinePartyInviteArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `decline_party_invite`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait decline_party_invite {
    /// Request that the remote module invoke the reducer `decline_party_invite` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`decline_party_invite:decline_party_invite_then`] to run a callback after the reducer completes.
    fn decline_party_invite(&self, invite_id: u64) -> __sdk::Result<()> {
        self.decline_party_invite_then(invite_id, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `decline_party_invite` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn decline_party_invite_then(
        &self,
        invite_id: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl decline_party_invite for super::RemoteReducers {
    fn decline_party_invite_then(
        &self,
        invite_id: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(DeclinePartyInviteArgs { invite_id }, callback)
    }
}
