// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct DisbandPartyArgs {}

impl From<DisbandPartyArgs> for super::Reducer {
    fn from(args: DisbandPartyArgs) -> Self {
        Self::DisbandParty
    }
}

impl __sdk::InModule for DisbandPartyArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `disband_party`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait disband_party {
    /// Request that the remote module invoke the reducer `disband_party` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`disband_party:disband_party_then`] to run a callback after the reducer completes.
    fn disband_party(&self) -> __sdk::Result<()> {
        self.disband_party_then(|_, _| {})
    }

    /// Request that the remote module invoke the reducer `disband_party` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn disband_party_then(
        &self,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl disband_party for super::RemoteReducers {
    fn disband_party_then(
        &self,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(DisbandPartyArgs {}, callback)
    }
}
