// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct EncounterAddMembershipInput {
    pub spawn_index: u32,
    pub boss_entity: u64,
    pub archetype: String,
    pub tags: Vec<String>,
}

impl __sdk::InModule for EncounterAddMembershipInput {
    type Module = super::RemoteModule;
}
