// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::entity_layer_type::EntityLayer;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `entity_layer`.
///
/// Obtain a handle from the [`EntityLayerTableAccess::entity_layer`] method on [`super::RemoteTables`],
/// like `ctx.db.entity_layer()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.entity_layer().on_insert(...)`.
pub struct EntityLayerTableHandle<'ctx> {
    imp: __sdk::TableHandle<EntityLayer>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `entity_layer`.
///
/// Implemented for [`super::RemoteTables`].
pub trait EntityLayerTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`EntityLayerTableHandle`], which mediates access to the table `entity_layer`.
    fn entity_layer(&self) -> EntityLayerTableHandle<'_>;
}

impl EntityLayerTableAccess for super::RemoteTables {
    fn entity_layer(&self) -> EntityLayerTableHandle<'_> {
        EntityLayerTableHandle {
            imp: self.imp.get_table::<EntityLayer>("entity_layer"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct EntityLayerInsertCallbackId(__sdk::CallbackId);
pub struct EntityLayerDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for EntityLayerTableHandle<'ctx> {
    type Row = EntityLayer;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = EntityLayer> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = EntityLayerInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> EntityLayerInsertCallbackId {
        EntityLayerInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: EntityLayerInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = EntityLayerDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> EntityLayerDeleteCallbackId {
        EntityLayerDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: EntityLayerDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct EntityLayerUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for EntityLayerTableHandle<'ctx> {
    type UpdateCallbackId = EntityLayerUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> EntityLayerUpdateCallbackId {
        EntityLayerUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: EntityLayerUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `entity_id` unique index on the table `entity_layer`,
/// which allows point queries on the field of the same name
/// via the [`EntityLayerEntityIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.entity_layer().entity_id().find(...)`.
pub struct EntityLayerEntityIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<EntityLayer, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> EntityLayerTableHandle<'ctx> {
    /// Get a handle on the `entity_id` unique index on the table `entity_layer`.
    pub fn entity_id(&self) -> EntityLayerEntityIdUnique<'ctx> {
        EntityLayerEntityIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("entity_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> EntityLayerEntityIdUnique<'ctx> {
    /// Find the subscribed row whose `entity_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<EntityLayer> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<EntityLayer>("entity_layer");
    _table.add_unique_constraint::<u64>("entity_id", |row| &row.entity_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<EntityLayer>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<EntityLayer>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `EntityLayer`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait entity_layerQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `EntityLayer`.
    fn entity_layer(&self) -> __sdk::__query_builder::Table<EntityLayer>;
}

impl entity_layerQueryTableAccess for __sdk::QueryTableAccessor {
    fn entity_layer(&self) -> __sdk::__query_builder::Table<EntityLayer> {
        __sdk::__query_builder::Table::new("entity_layer")
    }
}
