// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::entity_health_type::EntityHealth;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `entity_health`.
///
/// Obtain a handle from the [`EntityHealthTableAccess::entity_health`] method on [`super::RemoteTables`],
/// like `ctx.db.entity_health()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.entity_health().on_insert(...)`.
pub struct EntityHealthTableHandle<'ctx> {
    imp: __sdk::TableHandle<EntityHealth>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `entity_health`.
///
/// Implemented for [`super::RemoteTables`].
pub trait EntityHealthTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`EntityHealthTableHandle`], which mediates access to the table `entity_health`.
    fn entity_health(&self) -> EntityHealthTableHandle<'_>;
}

impl EntityHealthTableAccess for super::RemoteTables {
    fn entity_health(&self) -> EntityHealthTableHandle<'_> {
        EntityHealthTableHandle {
            imp: self.imp.get_table::<EntityHealth>("entity_health"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct EntityHealthInsertCallbackId(__sdk::CallbackId);
pub struct EntityHealthDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for EntityHealthTableHandle<'ctx> {
    type Row = EntityHealth;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = EntityHealth> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = EntityHealthInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> EntityHealthInsertCallbackId {
        EntityHealthInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: EntityHealthInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = EntityHealthDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> EntityHealthDeleteCallbackId {
        EntityHealthDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: EntityHealthDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct EntityHealthUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for EntityHealthTableHandle<'ctx> {
    type UpdateCallbackId = EntityHealthUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> EntityHealthUpdateCallbackId {
        EntityHealthUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: EntityHealthUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `entity_id` unique index on the table `entity_health`,
/// which allows point queries on the field of the same name
/// via the [`EntityHealthEntityIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.entity_health().entity_id().find(...)`.
pub struct EntityHealthEntityIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<EntityHealth, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> EntityHealthTableHandle<'ctx> {
    /// Get a handle on the `entity_id` unique index on the table `entity_health`.
    pub fn entity_id(&self) -> EntityHealthEntityIdUnique<'ctx> {
        EntityHealthEntityIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("entity_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> EntityHealthEntityIdUnique<'ctx> {
    /// Find the subscribed row whose `entity_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<EntityHealth> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<EntityHealth>("entity_health");
    _table.add_unique_constraint::<u64>("entity_id", |row| &row.entity_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<EntityHealth>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<EntityHealth>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `EntityHealth`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait entity_healthQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `EntityHealth`.
    fn entity_health(&self) -> __sdk::__query_builder::Table<EntityHealth>;
}

impl entity_healthQueryTableAccess for __sdk::QueryTableAccessor {
    fn entity_health(&self) -> __sdk::__query_builder::Table<EntityHealth> {
        __sdk::__query_builder::Table::new("entity_health")
    }
}
