// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct EntityRegion {
    pub entity_id: u64,
    pub region_x: i32,
    pub region_z: i32,
    pub layer: u32,
}

impl __sdk::InModule for EntityRegion {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `EntityRegion`.
///
/// Provides typed access to columns for query building.
pub struct EntityRegionCols {
    pub entity_id: __sdk::__query_builder::Col<EntityRegion, u64>,
    pub region_x: __sdk::__query_builder::Col<EntityRegion, i32>,
    pub region_z: __sdk::__query_builder::Col<EntityRegion, i32>,
    pub layer: __sdk::__query_builder::Col<EntityRegion, u32>,
}

impl __sdk::__query_builder::HasCols for EntityRegion {
    type Cols = EntityRegionCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        EntityRegionCols {
            entity_id: __sdk::__query_builder::Col::new(table_name, "entity_id"),
            region_x: __sdk::__query_builder::Col::new(table_name, "region_x"),
            region_z: __sdk::__query_builder::Col::new(table_name, "region_z"),
            layer: __sdk::__query_builder::Col::new(table_name, "layer"),
        }
    }
}

/// Indexed column accessor struct for the table `EntityRegion`.
///
/// Provides typed access to indexed columns for query building.
pub struct EntityRegionIxCols {
    pub entity_id: __sdk::__query_builder::IxCol<EntityRegion, u64>,
}

impl __sdk::__query_builder::HasIxCols for EntityRegion {
    type IxCols = EntityRegionIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        EntityRegionIxCols {
            entity_id: __sdk::__query_builder::IxCol::new(table_name, "entity_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for EntityRegion {}
