// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::entity_kind_type::EntityKind;
use super::entity_state_type::EntityState;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Entity {
    pub entity_id: u64,
    pub kind: EntityKind,
    pub state: EntityState,
    pub spawned_at_tick: u64,
    pub owner_identity: Option<__sdk::Identity>,
    pub rls_group: u8,
}

impl __sdk::InModule for Entity {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Entity`.
///
/// Provides typed access to columns for query building.
pub struct EntityCols {
    pub entity_id: __sdk::__query_builder::Col<Entity, u64>,
    pub kind: __sdk::__query_builder::Col<Entity, EntityKind>,
    pub state: __sdk::__query_builder::Col<Entity, EntityState>,
    pub spawned_at_tick: __sdk::__query_builder::Col<Entity, u64>,
    pub owner_identity: __sdk::__query_builder::Col<Entity, Option<__sdk::Identity>>,
    pub rls_group: __sdk::__query_builder::Col<Entity, u8>,
}

impl __sdk::__query_builder::HasCols for Entity {
    type Cols = EntityCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        EntityCols {
            entity_id: __sdk::__query_builder::Col::new(table_name, "entity_id"),
            kind: __sdk::__query_builder::Col::new(table_name, "kind"),
            state: __sdk::__query_builder::Col::new(table_name, "state"),
            spawned_at_tick: __sdk::__query_builder::Col::new(table_name, "spawned_at_tick"),
            owner_identity: __sdk::__query_builder::Col::new(table_name, "owner_identity"),
            rls_group: __sdk::__query_builder::Col::new(table_name, "rls_group"),
        }
    }
}

/// Indexed column accessor struct for the table `Entity`.
///
/// Provides typed access to indexed columns for query building.
pub struct EntityIxCols {
    pub entity_id: __sdk::__query_builder::IxCol<Entity, u64>,
    pub rls_group: __sdk::__query_builder::IxCol<Entity, u8>,
}

impl __sdk::__query_builder::HasIxCols for Entity {
    type IxCols = EntityIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        EntityIxCols {
            entity_id: __sdk::__query_builder::IxCol::new(table_name, "entity_id"),
            rls_group: __sdk::__query_builder::IxCol::new(table_name, "rls_group"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Entity {}
