// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::instance_membership_type::InstanceMembership;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `instance_membership`.
///
/// Obtain a handle from the [`InstanceMembershipTableAccess::instance_membership`] method on [`super::RemoteTables`],
/// like `ctx.db.instance_membership()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.instance_membership().on_insert(...)`.
pub struct InstanceMembershipTableHandle<'ctx> {
    imp: __sdk::TableHandle<InstanceMembership>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `instance_membership`.
///
/// Implemented for [`super::RemoteTables`].
pub trait InstanceMembershipTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`InstanceMembershipTableHandle`], which mediates access to the table `instance_membership`.
    fn instance_membership(&self) -> InstanceMembershipTableHandle<'_>;
}

impl InstanceMembershipTableAccess for super::RemoteTables {
    fn instance_membership(&self) -> InstanceMembershipTableHandle<'_> {
        InstanceMembershipTableHandle {
            imp: self
                .imp
                .get_table::<InstanceMembership>("instance_membership"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct InstanceMembershipInsertCallbackId(__sdk::CallbackId);
pub struct InstanceMembershipDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for InstanceMembershipTableHandle<'ctx> {
    type Row = InstanceMembership;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = InstanceMembership> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = InstanceMembershipInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> InstanceMembershipInsertCallbackId {
        InstanceMembershipInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: InstanceMembershipInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = InstanceMembershipDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> InstanceMembershipDeleteCallbackId {
        InstanceMembershipDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: InstanceMembershipDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct InstanceMembershipUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for InstanceMembershipTableHandle<'ctx> {
    type UpdateCallbackId = InstanceMembershipUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> InstanceMembershipUpdateCallbackId {
        InstanceMembershipUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: InstanceMembershipUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `entity_id` unique index on the table `instance_membership`,
/// which allows point queries on the field of the same name
/// via the [`InstanceMembershipEntityIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.instance_membership().entity_id().find(...)`.
pub struct InstanceMembershipEntityIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<InstanceMembership, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> InstanceMembershipTableHandle<'ctx> {
    /// Get a handle on the `entity_id` unique index on the table `instance_membership`.
    pub fn entity_id(&self) -> InstanceMembershipEntityIdUnique<'ctx> {
        InstanceMembershipEntityIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("entity_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> InstanceMembershipEntityIdUnique<'ctx> {
    /// Find the subscribed row whose `entity_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<InstanceMembership> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<InstanceMembership>("instance_membership");
    _table.add_unique_constraint::<u64>("entity_id", |row| &row.entity_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<InstanceMembership>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<InstanceMembership>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `InstanceMembership`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait instance_membershipQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `InstanceMembership`.
    fn instance_membership(&self) -> __sdk::__query_builder::Table<InstanceMembership>;
}

impl instance_membershipQueryTableAccess for __sdk::QueryTableAccessor {
    fn instance_membership(&self) -> __sdk::__query_builder::Table<InstanceMembership> {
        __sdk::__query_builder::Table::new("instance_membership")
    }
}
