// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct InstanceMembership {
    pub entity_id: u64,
    pub instance_id: u64,
    pub disconnect_at: Option<i64>,
}

impl __sdk::InModule for InstanceMembership {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `InstanceMembership`.
///
/// Provides typed access to columns for query building.
pub struct InstanceMembershipCols {
    pub entity_id: __sdk::__query_builder::Col<InstanceMembership, u64>,
    pub instance_id: __sdk::__query_builder::Col<InstanceMembership, u64>,
    pub disconnect_at: __sdk::__query_builder::Col<InstanceMembership, Option<i64>>,
}

impl __sdk::__query_builder::HasCols for InstanceMembership {
    type Cols = InstanceMembershipCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        InstanceMembershipCols {
            entity_id: __sdk::__query_builder::Col::new(table_name, "entity_id"),
            instance_id: __sdk::__query_builder::Col::new(table_name, "instance_id"),
            disconnect_at: __sdk::__query_builder::Col::new(table_name, "disconnect_at"),
        }
    }
}

/// Indexed column accessor struct for the table `InstanceMembership`.
///
/// Provides typed access to indexed columns for query building.
pub struct InstanceMembershipIxCols {
    pub entity_id: __sdk::__query_builder::IxCol<InstanceMembership, u64>,
    pub instance_id: __sdk::__query_builder::IxCol<InstanceMembership, u64>,
}

impl __sdk::__query_builder::HasIxCols for InstanceMembership {
    type IxCols = InstanceMembershipIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        InstanceMembershipIxCols {
            entity_id: __sdk::__query_builder::IxCol::new(table_name, "entity_id"),
            instance_id: __sdk::__query_builder::IxCol::new(table_name, "instance_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for InstanceMembership {}
