// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct InviteToPartyArgs {
    pub target_entity_id: u64,
}

impl From<InviteToPartyArgs> for super::Reducer {
    fn from(args: InviteToPartyArgs) -> Self {
        Self::InviteToParty {
            target_entity_id: args.target_entity_id,
        }
    }
}

impl __sdk::InModule for InviteToPartyArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `invite_to_party`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait invite_to_party {
    /// Request that the remote module invoke the reducer `invite_to_party` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`invite_to_party:invite_to_party_then`] to run a callback after the reducer completes.
    fn invite_to_party(&self, target_entity_id: u64) -> __sdk::Result<()> {
        self.invite_to_party_then(target_entity_id, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `invite_to_party` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn invite_to_party_then(
        &self,
        target_entity_id: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl invite_to_party for super::RemoteReducers {
    fn invite_to_party_then(
        &self,
        target_entity_id: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(InviteToPartyArgs { target_entity_id }, callback)
    }
}
