// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct LootItemArgs {
    pub entity_id: u64,
    pub target_slot: u32,
    pub item_id: u32,
    pub quantity: u32,
}

impl From<LootItemArgs> for super::Reducer {
    fn from(args: LootItemArgs) -> Self {
        Self::LootItem {
            entity_id: args.entity_id,
            target_slot: args.target_slot,
            item_id: args.item_id,
            quantity: args.quantity,
        }
    }
}

impl __sdk::InModule for LootItemArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `loot_item`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait loot_item {
    /// Request that the remote module invoke the reducer `loot_item` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`loot_item:loot_item_then`] to run a callback after the reducer completes.
    fn loot_item(
        &self,
        entity_id: u64,
        target_slot: u32,
        item_id: u32,
        quantity: u32,
    ) -> __sdk::Result<()> {
        self.loot_item_then(entity_id, target_slot, item_id, quantity, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `loot_item` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn loot_item_then(
        &self,
        entity_id: u64,
        target_slot: u32,
        item_id: u32,
        quantity: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl loot_item for super::RemoteReducers {
    fn loot_item_then(
        &self,
        entity_id: u64,
        target_slot: u32,
        item_id: u32,
        quantity: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            LootItemArgs {
                entity_id,
                target_slot,
                item_id,
                quantity,
            },
            callback,
        )
    }
}
