// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::module_config_type::ModuleConfig;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `module_config`.
///
/// Obtain a handle from the [`ModuleConfigTableAccess::module_config`] method on [`super::RemoteTables`],
/// like `ctx.db.module_config()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.module_config().on_insert(...)`.
pub struct ModuleConfigTableHandle<'ctx> {
    imp: __sdk::TableHandle<ModuleConfig>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `module_config`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ModuleConfigTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ModuleConfigTableHandle`], which mediates access to the table `module_config`.
    fn module_config(&self) -> ModuleConfigTableHandle<'_>;
}

impl ModuleConfigTableAccess for super::RemoteTables {
    fn module_config(&self) -> ModuleConfigTableHandle<'_> {
        ModuleConfigTableHandle {
            imp: self.imp.get_table::<ModuleConfig>("module_config"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ModuleConfigInsertCallbackId(__sdk::CallbackId);
pub struct ModuleConfigDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for ModuleConfigTableHandle<'ctx> {
    type Row = ModuleConfig;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = ModuleConfig> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = ModuleConfigInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ModuleConfigInsertCallbackId {
        ModuleConfigInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ModuleConfigInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = ModuleConfigDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ModuleConfigDeleteCallbackId {
        ModuleConfigDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ModuleConfigDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct ModuleConfigUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for ModuleConfigTableHandle<'ctx> {
    type UpdateCallbackId = ModuleConfigUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ModuleConfigUpdateCallbackId {
        ModuleConfigUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ModuleConfigUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `key` unique index on the table `module_config`,
/// which allows point queries on the field of the same name
/// via the [`ModuleConfigKeyUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.module_config().key().find(...)`.
pub struct ModuleConfigKeyUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<ModuleConfig, u32>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> ModuleConfigTableHandle<'ctx> {
    /// Get a handle on the `key` unique index on the table `module_config`.
    pub fn key(&self) -> ModuleConfigKeyUnique<'ctx> {
        ModuleConfigKeyUnique {
            imp: self.imp.get_unique_constraint::<u32>("key"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> ModuleConfigKeyUnique<'ctx> {
    /// Find the subscribed row whose `key` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u32) -> Option<ModuleConfig> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<ModuleConfig>("module_config");
    _table.add_unique_constraint::<u32>("key", |row| &row.key);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<ModuleConfig>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<ModuleConfig>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `ModuleConfig`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait module_configQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `ModuleConfig`.
    fn module_config(&self) -> __sdk::__query_builder::Table<ModuleConfig>;
}

impl module_configQueryTableAccess for __sdk::QueryTableAccessor {
    fn module_config(&self) -> __sdk::__query_builder::Table<ModuleConfig> {
        __sdk::__query_builder::Table::new("module_config")
    }
}
