// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::entity_transform_type::EntityTransform;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `nearby_transforms`.
///
/// Obtain a handle from the [`NearbyTransformsTableAccess::nearby_transforms`] method on [`super::RemoteTables`],
/// like `ctx.db.nearby_transforms()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.nearby_transforms().on_insert(...)`.
pub struct NearbyTransformsTableHandle<'ctx> {
    imp: __sdk::TableHandle<EntityTransform>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `nearby_transforms`.
///
/// Implemented for [`super::RemoteTables`].
pub trait NearbyTransformsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`NearbyTransformsTableHandle`], which mediates access to the table `nearby_transforms`.
    fn nearby_transforms(&self) -> NearbyTransformsTableHandle<'_>;
}

impl NearbyTransformsTableAccess for super::RemoteTables {
    fn nearby_transforms(&self) -> NearbyTransformsTableHandle<'_> {
        NearbyTransformsTableHandle {
            imp: self.imp.get_table::<EntityTransform>("nearby_transforms"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct NearbyTransformsInsertCallbackId(__sdk::CallbackId);
pub struct NearbyTransformsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for NearbyTransformsTableHandle<'ctx> {
    type Row = EntityTransform;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = EntityTransform> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = NearbyTransformsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> NearbyTransformsInsertCallbackId {
        NearbyTransformsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: NearbyTransformsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = NearbyTransformsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> NearbyTransformsDeleteCallbackId {
        NearbyTransformsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: NearbyTransformsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<EntityTransform>("nearby_transforms");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<EntityTransform>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<EntityTransform>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `EntityTransform`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait nearby_transformsQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `EntityTransform`.
    fn nearby_transforms(&self) -> __sdk::__query_builder::Table<EntityTransform>;
}

impl nearby_transformsQueryTableAccess for __sdk::QueryTableAccessor {
    fn nearby_transforms(&self) -> __sdk::__query_builder::Table<EntityTransform> {
        __sdk::__query_builder::Table::new("nearby_transforms")
    }
}
