// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct PartyMember {
    pub member_id: u64,
    pub party_id: u64,
    pub entity_id: u64,
}

impl __sdk::InModule for PartyMember {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `PartyMember`.
///
/// Provides typed access to columns for query building.
pub struct PartyMemberCols {
    pub member_id: __sdk::__query_builder::Col<PartyMember, u64>,
    pub party_id: __sdk::__query_builder::Col<PartyMember, u64>,
    pub entity_id: __sdk::__query_builder::Col<PartyMember, u64>,
}

impl __sdk::__query_builder::HasCols for PartyMember {
    type Cols = PartyMemberCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        PartyMemberCols {
            member_id: __sdk::__query_builder::Col::new(table_name, "member_id"),
            party_id: __sdk::__query_builder::Col::new(table_name, "party_id"),
            entity_id: __sdk::__query_builder::Col::new(table_name, "entity_id"),
        }
    }
}

/// Indexed column accessor struct for the table `PartyMember`.
///
/// Provides typed access to indexed columns for query building.
pub struct PartyMemberIxCols {
    pub entity_id: __sdk::__query_builder::IxCol<PartyMember, u64>,
    pub member_id: __sdk::__query_builder::IxCol<PartyMember, u64>,
    pub party_id: __sdk::__query_builder::IxCol<PartyMember, u64>,
}

impl __sdk::__query_builder::HasIxCols for PartyMember {
    type IxCols = PartyMemberIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        PartyMemberIxCols {
            entity_id: __sdk::__query_builder::IxCol::new(table_name, "entity_id"),
            member_id: __sdk::__query_builder::IxCol::new(table_name, "member_id"),
            party_id: __sdk::__query_builder::IxCol::new(table_name, "party_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for PartyMember {}
