// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::intent_action_type::IntentAction;
use super::player_intent_type::PlayerIntent;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `player_intent`.
///
/// Obtain a handle from the [`PlayerIntentTableAccess::player_intent`] method on [`super::RemoteTables`],
/// like `ctx.db.player_intent()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.player_intent().on_insert(...)`.
pub struct PlayerIntentTableHandle<'ctx> {
    imp: __sdk::TableHandle<PlayerIntent>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `player_intent`.
///
/// Implemented for [`super::RemoteTables`].
pub trait PlayerIntentTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`PlayerIntentTableHandle`], which mediates access to the table `player_intent`.
    fn player_intent(&self) -> PlayerIntentTableHandle<'_>;
}

impl PlayerIntentTableAccess for super::RemoteTables {
    fn player_intent(&self) -> PlayerIntentTableHandle<'_> {
        PlayerIntentTableHandle {
            imp: self.imp.get_table::<PlayerIntent>("player_intent"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct PlayerIntentInsertCallbackId(__sdk::CallbackId);
pub struct PlayerIntentDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for PlayerIntentTableHandle<'ctx> {
    type Row = PlayerIntent;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = PlayerIntent> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = PlayerIntentInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PlayerIntentInsertCallbackId {
        PlayerIntentInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: PlayerIntentInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = PlayerIntentDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PlayerIntentDeleteCallbackId {
        PlayerIntentDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: PlayerIntentDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct PlayerIntentUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for PlayerIntentTableHandle<'ctx> {
    type UpdateCallbackId = PlayerIntentUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> PlayerIntentUpdateCallbackId {
        PlayerIntentUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: PlayerIntentUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `intent_id` unique index on the table `player_intent`,
/// which allows point queries on the field of the same name
/// via the [`PlayerIntentIntentIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.player_intent().intent_id().find(...)`.
pub struct PlayerIntentIntentIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<PlayerIntent, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> PlayerIntentTableHandle<'ctx> {
    /// Get a handle on the `intent_id` unique index on the table `player_intent`.
    pub fn intent_id(&self) -> PlayerIntentIntentIdUnique<'ctx> {
        PlayerIntentIntentIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("intent_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> PlayerIntentIntentIdUnique<'ctx> {
    /// Find the subscribed row whose `intent_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<PlayerIntent> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<PlayerIntent>("player_intent");
    _table.add_unique_constraint::<u64>("intent_id", |row| &row.intent_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<PlayerIntent>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<PlayerIntent>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `PlayerIntent`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait player_intentQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `PlayerIntent`.
    fn player_intent(&self) -> __sdk::__query_builder::Table<PlayerIntent>;
}

impl player_intentQueryTableAccess for __sdk::QueryTableAccessor {
    fn player_intent(&self) -> __sdk::__query_builder::Table<PlayerIntent> {
        __sdk::__query_builder::Table::new("player_intent")
    }
}
