// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::equipment_slot_type::EquipmentSlot;
use super::player_equipment_type::PlayerEquipment;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `player_equipment`.
///
/// Obtain a handle from the [`PlayerEquipmentTableAccess::player_equipment`] method on [`super::RemoteTables`],
/// like `ctx.db.player_equipment()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.player_equipment().on_insert(...)`.
pub struct PlayerEquipmentTableHandle<'ctx> {
    imp: __sdk::TableHandle<PlayerEquipment>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `player_equipment`.
///
/// Implemented for [`super::RemoteTables`].
pub trait PlayerEquipmentTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`PlayerEquipmentTableHandle`], which mediates access to the table `player_equipment`.
    fn player_equipment(&self) -> PlayerEquipmentTableHandle<'_>;
}

impl PlayerEquipmentTableAccess for super::RemoteTables {
    fn player_equipment(&self) -> PlayerEquipmentTableHandle<'_> {
        PlayerEquipmentTableHandle {
            imp: self.imp.get_table::<PlayerEquipment>("player_equipment"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct PlayerEquipmentInsertCallbackId(__sdk::CallbackId);
pub struct PlayerEquipmentDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for PlayerEquipmentTableHandle<'ctx> {
    type Row = PlayerEquipment;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = PlayerEquipment> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = PlayerEquipmentInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PlayerEquipmentInsertCallbackId {
        PlayerEquipmentInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: PlayerEquipmentInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = PlayerEquipmentDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PlayerEquipmentDeleteCallbackId {
        PlayerEquipmentDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: PlayerEquipmentDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct PlayerEquipmentUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for PlayerEquipmentTableHandle<'ctx> {
    type UpdateCallbackId = PlayerEquipmentUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> PlayerEquipmentUpdateCallbackId {
        PlayerEquipmentUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: PlayerEquipmentUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `row_id` unique index on the table `player_equipment`,
/// which allows point queries on the field of the same name
/// via the [`PlayerEquipmentRowIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.player_equipment().row_id().find(...)`.
pub struct PlayerEquipmentRowIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<PlayerEquipment, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> PlayerEquipmentTableHandle<'ctx> {
    /// Get a handle on the `row_id` unique index on the table `player_equipment`.
    pub fn row_id(&self) -> PlayerEquipmentRowIdUnique<'ctx> {
        PlayerEquipmentRowIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("row_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> PlayerEquipmentRowIdUnique<'ctx> {
    /// Find the subscribed row whose `row_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<PlayerEquipment> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<PlayerEquipment>("player_equipment");
    _table.add_unique_constraint::<u64>("row_id", |row| &row.row_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<PlayerEquipment>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<PlayerEquipment>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `PlayerEquipment`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait player_equipmentQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `PlayerEquipment`.
    fn player_equipment(&self) -> __sdk::__query_builder::Table<PlayerEquipment>;
}

impl player_equipmentQueryTableAccess for __sdk::QueryTableAccessor {
    fn player_equipment(&self) -> __sdk::__query_builder::Table<PlayerEquipment> {
        __sdk::__query_builder::Table::new("player_equipment")
    }
}
