// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct PlayerInventory {
    pub row_id: u64,
    pub owner_entity: u64,
    pub slot_index: u32,
    pub item_id: u32,
    pub quantity: u32,
}

impl __sdk::InModule for PlayerInventory {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `PlayerInventory`.
///
/// Provides typed access to columns for query building.
pub struct PlayerInventoryCols {
    pub row_id: __sdk::__query_builder::Col<PlayerInventory, u64>,
    pub owner_entity: __sdk::__query_builder::Col<PlayerInventory, u64>,
    pub slot_index: __sdk::__query_builder::Col<PlayerInventory, u32>,
    pub item_id: __sdk::__query_builder::Col<PlayerInventory, u32>,
    pub quantity: __sdk::__query_builder::Col<PlayerInventory, u32>,
}

impl __sdk::__query_builder::HasCols for PlayerInventory {
    type Cols = PlayerInventoryCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        PlayerInventoryCols {
            row_id: __sdk::__query_builder::Col::new(table_name, "row_id"),
            owner_entity: __sdk::__query_builder::Col::new(table_name, "owner_entity"),
            slot_index: __sdk::__query_builder::Col::new(table_name, "slot_index"),
            item_id: __sdk::__query_builder::Col::new(table_name, "item_id"),
            quantity: __sdk::__query_builder::Col::new(table_name, "quantity"),
        }
    }
}

/// Indexed column accessor struct for the table `PlayerInventory`.
///
/// Provides typed access to indexed columns for query building.
pub struct PlayerInventoryIxCols {
    pub owner_entity: __sdk::__query_builder::IxCol<PlayerInventory, u64>,
    pub row_id: __sdk::__query_builder::IxCol<PlayerInventory, u64>,
}

impl __sdk::__query_builder::HasIxCols for PlayerInventory {
    type IxCols = PlayerInventoryIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        PlayerInventoryIxCols {
            owner_entity: __sdk::__query_builder::IxCol::new(table_name, "owner_entity"),
            row_id: __sdk::__query_builder::IxCol::new(table_name, "row_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for PlayerInventory {}
