// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::player_inventory_type::PlayerInventory;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `player_inventory`.
///
/// Obtain a handle from the [`PlayerInventoryTableAccess::player_inventory`] method on [`super::RemoteTables`],
/// like `ctx.db.player_inventory()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.player_inventory().on_insert(...)`.
pub struct PlayerInventoryTableHandle<'ctx> {
    imp: __sdk::TableHandle<PlayerInventory>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `player_inventory`.
///
/// Implemented for [`super::RemoteTables`].
pub trait PlayerInventoryTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`PlayerInventoryTableHandle`], which mediates access to the table `player_inventory`.
    fn player_inventory(&self) -> PlayerInventoryTableHandle<'_>;
}

impl PlayerInventoryTableAccess for super::RemoteTables {
    fn player_inventory(&self) -> PlayerInventoryTableHandle<'_> {
        PlayerInventoryTableHandle {
            imp: self.imp.get_table::<PlayerInventory>("player_inventory"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct PlayerInventoryInsertCallbackId(__sdk::CallbackId);
pub struct PlayerInventoryDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for PlayerInventoryTableHandle<'ctx> {
    type Row = PlayerInventory;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = PlayerInventory> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = PlayerInventoryInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PlayerInventoryInsertCallbackId {
        PlayerInventoryInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: PlayerInventoryInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = PlayerInventoryDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PlayerInventoryDeleteCallbackId {
        PlayerInventoryDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: PlayerInventoryDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct PlayerInventoryUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for PlayerInventoryTableHandle<'ctx> {
    type UpdateCallbackId = PlayerInventoryUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> PlayerInventoryUpdateCallbackId {
        PlayerInventoryUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: PlayerInventoryUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `row_id` unique index on the table `player_inventory`,
/// which allows point queries on the field of the same name
/// via the [`PlayerInventoryRowIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.player_inventory().row_id().find(...)`.
pub struct PlayerInventoryRowIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<PlayerInventory, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> PlayerInventoryTableHandle<'ctx> {
    /// Get a handle on the `row_id` unique index on the table `player_inventory`.
    pub fn row_id(&self) -> PlayerInventoryRowIdUnique<'ctx> {
        PlayerInventoryRowIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("row_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> PlayerInventoryRowIdUnique<'ctx> {
    /// Find the subscribed row whose `row_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<PlayerInventory> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<PlayerInventory>("player_inventory");
    _table.add_unique_constraint::<u64>("row_id", |row| &row.row_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<PlayerInventory>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<PlayerInventory>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `PlayerInventory`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait player_inventoryQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `PlayerInventory`.
    fn player_inventory(&self) -> __sdk::__query_builder::Table<PlayerInventory>;
}

impl player_inventoryQueryTableAccess for __sdk::QueryTableAccessor {
    fn player_inventory(&self) -> __sdk::__query_builder::Table<PlayerInventory> {
        __sdk::__query_builder::Table::new("player_inventory")
    }
}
