// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct RemoveRespawnPointArgs {
    pub point_id: u64,
}

impl From<RemoveRespawnPointArgs> for super::Reducer {
    fn from(args: RemoveRespawnPointArgs) -> Self {
        Self::RemoveRespawnPoint {
            point_id: args.point_id,
        }
    }
}

impl __sdk::InModule for RemoveRespawnPointArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `remove_respawn_point`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait remove_respawn_point {
    /// Request that the remote module invoke the reducer `remove_respawn_point` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`remove_respawn_point:remove_respawn_point_then`] to run a callback after the reducer completes.
    fn remove_respawn_point(&self, point_id: u64) -> __sdk::Result<()> {
        self.remove_respawn_point_then(point_id, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `remove_respawn_point` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn remove_respawn_point_then(
        &self,
        point_id: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl remove_respawn_point for super::RemoteReducers {
    fn remove_respawn_point_then(
        &self,
        point_id: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(RemoveRespawnPointArgs { point_id }, callback)
    }
}
