// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct RespawnPoint {
    pub point_id: u64,
    pub layer: u32,
    pub region_x: i32,
    pub region_z: i32,
    pub pos_x: f32,
    pub pos_y: f32,
    pub pos_z: f32,
    pub name: String,
}

impl __sdk::InModule for RespawnPoint {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `RespawnPoint`.
///
/// Provides typed access to columns for query building.
pub struct RespawnPointCols {
    pub point_id: __sdk::__query_builder::Col<RespawnPoint, u64>,
    pub layer: __sdk::__query_builder::Col<RespawnPoint, u32>,
    pub region_x: __sdk::__query_builder::Col<RespawnPoint, i32>,
    pub region_z: __sdk::__query_builder::Col<RespawnPoint, i32>,
    pub pos_x: __sdk::__query_builder::Col<RespawnPoint, f32>,
    pub pos_y: __sdk::__query_builder::Col<RespawnPoint, f32>,
    pub pos_z: __sdk::__query_builder::Col<RespawnPoint, f32>,
    pub name: __sdk::__query_builder::Col<RespawnPoint, String>,
}

impl __sdk::__query_builder::HasCols for RespawnPoint {
    type Cols = RespawnPointCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        RespawnPointCols {
            point_id: __sdk::__query_builder::Col::new(table_name, "point_id"),
            layer: __sdk::__query_builder::Col::new(table_name, "layer"),
            region_x: __sdk::__query_builder::Col::new(table_name, "region_x"),
            region_z: __sdk::__query_builder::Col::new(table_name, "region_z"),
            pos_x: __sdk::__query_builder::Col::new(table_name, "pos_x"),
            pos_y: __sdk::__query_builder::Col::new(table_name, "pos_y"),
            pos_z: __sdk::__query_builder::Col::new(table_name, "pos_z"),
            name: __sdk::__query_builder::Col::new(table_name, "name"),
        }
    }
}

/// Indexed column accessor struct for the table `RespawnPoint`.
///
/// Provides typed access to indexed columns for query building.
pub struct RespawnPointIxCols {
    pub layer: __sdk::__query_builder::IxCol<RespawnPoint, u32>,
    pub point_id: __sdk::__query_builder::IxCol<RespawnPoint, u64>,
}

impl __sdk::__query_builder::HasIxCols for RespawnPoint {
    type IxCols = RespawnPointIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        RespawnPointIxCols {
            layer: __sdk::__query_builder::IxCol::new(table_name, "layer"),
            point_id: __sdk::__query_builder::IxCol::new(table_name, "point_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for RespawnPoint {}
