// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::respawn_point_type::RespawnPoint;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `respawn_point`.
///
/// Obtain a handle from the [`RespawnPointTableAccess::respawn_point`] method on [`super::RemoteTables`],
/// like `ctx.db.respawn_point()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.respawn_point().on_insert(...)`.
pub struct RespawnPointTableHandle<'ctx> {
    imp: __sdk::TableHandle<RespawnPoint>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `respawn_point`.
///
/// Implemented for [`super::RemoteTables`].
pub trait RespawnPointTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`RespawnPointTableHandle`], which mediates access to the table `respawn_point`.
    fn respawn_point(&self) -> RespawnPointTableHandle<'_>;
}

impl RespawnPointTableAccess for super::RemoteTables {
    fn respawn_point(&self) -> RespawnPointTableHandle<'_> {
        RespawnPointTableHandle {
            imp: self.imp.get_table::<RespawnPoint>("respawn_point"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct RespawnPointInsertCallbackId(__sdk::CallbackId);
pub struct RespawnPointDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for RespawnPointTableHandle<'ctx> {
    type Row = RespawnPoint;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = RespawnPoint> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = RespawnPointInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> RespawnPointInsertCallbackId {
        RespawnPointInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: RespawnPointInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = RespawnPointDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> RespawnPointDeleteCallbackId {
        RespawnPointDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: RespawnPointDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct RespawnPointUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for RespawnPointTableHandle<'ctx> {
    type UpdateCallbackId = RespawnPointUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> RespawnPointUpdateCallbackId {
        RespawnPointUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: RespawnPointUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `point_id` unique index on the table `respawn_point`,
/// which allows point queries on the field of the same name
/// via the [`RespawnPointPointIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.respawn_point().point_id().find(...)`.
pub struct RespawnPointPointIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<RespawnPoint, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> RespawnPointTableHandle<'ctx> {
    /// Get a handle on the `point_id` unique index on the table `respawn_point`.
    pub fn point_id(&self) -> RespawnPointPointIdUnique<'ctx> {
        RespawnPointPointIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("point_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> RespawnPointPointIdUnique<'ctx> {
    /// Find the subscribed row whose `point_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<RespawnPoint> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<RespawnPoint>("respawn_point");
    _table.add_unique_constraint::<u64>("point_id", |row| &row.point_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<RespawnPoint>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<RespawnPoint>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `RespawnPoint`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait respawn_pointQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `RespawnPoint`.
    fn respawn_point(&self) -> __sdk::__query_builder::Table<RespawnPoint>;
}

impl respawn_pointQueryTableAccess for __sdk::QueryTableAccessor {
    fn respawn_point(&self) -> __sdk::__query_builder::Table<RespawnPoint> {
        __sdk::__query_builder::Table::new("respawn_point")
    }
}
