// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::sim_tick_type::SimTick;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `sim_tick`.
///
/// Obtain a handle from the [`SimTickTableAccess::sim_tick`] method on [`super::RemoteTables`],
/// like `ctx.db.sim_tick()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.sim_tick().on_insert(...)`.
pub struct SimTickTableHandle<'ctx> {
    imp: __sdk::TableHandle<SimTick>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `sim_tick`.
///
/// Implemented for [`super::RemoteTables`].
pub trait SimTickTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`SimTickTableHandle`], which mediates access to the table `sim_tick`.
    fn sim_tick(&self) -> SimTickTableHandle<'_>;
}

impl SimTickTableAccess for super::RemoteTables {
    fn sim_tick(&self) -> SimTickTableHandle<'_> {
        SimTickTableHandle {
            imp: self.imp.get_table::<SimTick>("sim_tick"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct SimTickInsertCallbackId(__sdk::CallbackId);
pub struct SimTickDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for SimTickTableHandle<'ctx> {
    type Row = SimTick;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = SimTick> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = SimTickInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SimTickInsertCallbackId {
        SimTickInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: SimTickInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = SimTickDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SimTickDeleteCallbackId {
        SimTickDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: SimTickDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct SimTickUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for SimTickTableHandle<'ctx> {
    type UpdateCallbackId = SimTickUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> SimTickUpdateCallbackId {
        SimTickUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: SimTickUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `tick_id` unique index on the table `sim_tick`,
/// which allows point queries on the field of the same name
/// via the [`SimTickTickIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.sim_tick().tick_id().find(...)`.
pub struct SimTickTickIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<SimTick, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> SimTickTableHandle<'ctx> {
    /// Get a handle on the `tick_id` unique index on the table `sim_tick`.
    pub fn tick_id(&self) -> SimTickTickIdUnique<'ctx> {
        SimTickTickIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("tick_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> SimTickTickIdUnique<'ctx> {
    /// Find the subscribed row whose `tick_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<SimTick> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<SimTick>("sim_tick");
    _table.add_unique_constraint::<u64>("tick_id", |row| &row.tick_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<SimTick>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<SimTick>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `SimTick`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait sim_tickQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `SimTick`.
    fn sim_tick(&self) -> __sdk::__query_builder::Table<SimTick>;
}

impl sim_tickQueryTableAccess for __sdk::QueryTableAccessor {
    fn sim_tick(&self) -> __sdk::__query_builder::Table<SimTick> {
        __sdk::__query_builder::Table::new("sim_tick")
    }
}
