// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct SimLog {
    pub log_id: u64,
    pub tick_id: u64,
    pub level: u8,
    pub message: String,
}

impl __sdk::InModule for SimLog {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `SimLog`.
///
/// Provides typed access to columns for query building.
pub struct SimLogCols {
    pub log_id: __sdk::__query_builder::Col<SimLog, u64>,
    pub tick_id: __sdk::__query_builder::Col<SimLog, u64>,
    pub level: __sdk::__query_builder::Col<SimLog, u8>,
    pub message: __sdk::__query_builder::Col<SimLog, String>,
}

impl __sdk::__query_builder::HasCols for SimLog {
    type Cols = SimLogCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        SimLogCols {
            log_id: __sdk::__query_builder::Col::new(table_name, "log_id"),
            tick_id: __sdk::__query_builder::Col::new(table_name, "tick_id"),
            level: __sdk::__query_builder::Col::new(table_name, "level"),
            message: __sdk::__query_builder::Col::new(table_name, "message"),
        }
    }
}

/// Indexed column accessor struct for the table `SimLog`.
///
/// Provides typed access to indexed columns for query building.
pub struct SimLogIxCols {
    pub log_id: __sdk::__query_builder::IxCol<SimLog, u64>,
    pub tick_id: __sdk::__query_builder::IxCol<SimLog, u64>,
}

impl __sdk::__query_builder::HasIxCols for SimLog {
    type IxCols = SimLogIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        SimLogIxCols {
            log_id: __sdk::__query_builder::IxCol::new(table_name, "log_id"),
            tick_id: __sdk::__query_builder::IxCol::new(table_name, "tick_id"),
        }
    }
}
