// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct SimTick {
    pub tick_id: u64,
    pub timestamp_us: i64,
}

impl __sdk::InModule for SimTick {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `SimTick`.
///
/// Provides typed access to columns for query building.
pub struct SimTickCols {
    pub tick_id: __sdk::__query_builder::Col<SimTick, u64>,
    pub timestamp_us: __sdk::__query_builder::Col<SimTick, i64>,
}

impl __sdk::__query_builder::HasCols for SimTick {
    type Cols = SimTickCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        SimTickCols {
            tick_id: __sdk::__query_builder::Col::new(table_name, "tick_id"),
            timestamp_us: __sdk::__query_builder::Col::new(table_name, "timestamp_us"),
        }
    }
}

/// Indexed column accessor struct for the table `SimTick`.
///
/// Provides typed access to indexed columns for query building.
pub struct SimTickIxCols {
    pub tick_id: __sdk::__query_builder::IxCol<SimTick, u64>,
}

impl __sdk::__query_builder::HasIxCols for SimTick {
    type IxCols = SimTickIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        SimTickIxCols {
            tick_id: __sdk::__query_builder::IxCol::new(table_name, "tick_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for SimTick {}
