// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::sim_log_type::SimLog;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `sim_log`.
///
/// Obtain a handle from the [`SimLogTableAccess::sim_log`] method on [`super::RemoteTables`],
/// like `ctx.db.sim_log()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.sim_log().on_insert(...)`.
pub struct SimLogTableHandle<'ctx> {
    imp: __sdk::TableHandle<SimLog>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `sim_log`.
///
/// Implemented for [`super::RemoteTables`].
pub trait SimLogTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`SimLogTableHandle`], which mediates access to the table `sim_log`.
    fn sim_log(&self) -> SimLogTableHandle<'_>;
}

impl SimLogTableAccess for super::RemoteTables {
    fn sim_log(&self) -> SimLogTableHandle<'_> {
        SimLogTableHandle {
            imp: self.imp.get_table::<SimLog>("sim_log"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct SimLogInsertCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::EventTable for SimLogTableHandle<'ctx> {
    type Row = SimLog;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = SimLog> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = SimLogInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SimLogInsertCallbackId {
        SimLogInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: SimLogInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<SimLog>("sim_log");
    _table.add_unique_constraint::<u64>("log_id", |row| &row.log_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<SimLog>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<SimLog>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `SimLog`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait sim_logQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `SimLog`.
    fn sim_log(&self) -> __sdk::__query_builder::Table<SimLog>;
}

impl sim_logQueryTableAccess for __sdk::QueryTableAccessor {
    fn sim_log(&self) -> __sdk::__query_builder::Table<SimLog> {
        __sdk::__query_builder::Table::new("sim_log")
    }
}
