// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct StealthedEntity {
    pub entity_id: u64,
    pub team_id: u32,
}

impl __sdk::InModule for StealthedEntity {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `StealthedEntity`.
///
/// Provides typed access to columns for query building.
pub struct StealthedEntityCols {
    pub entity_id: __sdk::__query_builder::Col<StealthedEntity, u64>,
    pub team_id: __sdk::__query_builder::Col<StealthedEntity, u32>,
}

impl __sdk::__query_builder::HasCols for StealthedEntity {
    type Cols = StealthedEntityCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        StealthedEntityCols {
            entity_id: __sdk::__query_builder::Col::new(table_name, "entity_id"),
            team_id: __sdk::__query_builder::Col::new(table_name, "team_id"),
        }
    }
}

/// Indexed column accessor struct for the table `StealthedEntity`.
///
/// Provides typed access to indexed columns for query building.
pub struct StealthedEntityIxCols {
    pub entity_id: __sdk::__query_builder::IxCol<StealthedEntity, u64>,
}

impl __sdk::__query_builder::HasIxCols for StealthedEntity {
    type IxCols = StealthedEntityIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        StealthedEntityIxCols {
            entity_id: __sdk::__query_builder::IxCol::new(table_name, "entity_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for StealthedEntity {}
