// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SwapItemArgs {
    pub entity_id: u64,
    pub slot_a: u32,
    pub slot_b: u32,
}

impl From<SwapItemArgs> for super::Reducer {
    fn from(args: SwapItemArgs) -> Self {
        Self::SwapItem {
            entity_id: args.entity_id,
            slot_a: args.slot_a,
            slot_b: args.slot_b,
        }
    }
}

impl __sdk::InModule for SwapItemArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `swap_item`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait swap_item {
    /// Request that the remote module invoke the reducer `swap_item` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`swap_item:swap_item_then`] to run a callback after the reducer completes.
    fn swap_item(&self, entity_id: u64, slot_a: u32, slot_b: u32) -> __sdk::Result<()> {
        self.swap_item_then(entity_id, slot_a, slot_b, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `swap_item` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn swap_item_then(
        &self,
        entity_id: u64,
        slot_a: u32,
        slot_b: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl swap_item for super::RemoteReducers {
    fn swap_item_then(
        &self,
        entity_id: u64,
        slot_a: u32,
        slot_b: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            SwapItemArgs {
                entity_id,
                slot_a,
                slot_b,
            },
            callback,
        )
    }
}
