// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct TerrainManifest {
    pub row_id: u64,
    pub terrain_set_id: u32,
    pub chunk_morton: u64,
    pub content_hash: String,
    pub version: u32,
}

impl __sdk::InModule for TerrainManifest {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `TerrainManifest`.
///
/// Provides typed access to columns for query building.
pub struct TerrainManifestCols {
    pub row_id: __sdk::__query_builder::Col<TerrainManifest, u64>,
    pub terrain_set_id: __sdk::__query_builder::Col<TerrainManifest, u32>,
    pub chunk_morton: __sdk::__query_builder::Col<TerrainManifest, u64>,
    pub content_hash: __sdk::__query_builder::Col<TerrainManifest, String>,
    pub version: __sdk::__query_builder::Col<TerrainManifest, u32>,
}

impl __sdk::__query_builder::HasCols for TerrainManifest {
    type Cols = TerrainManifestCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        TerrainManifestCols {
            row_id: __sdk::__query_builder::Col::new(table_name, "row_id"),
            terrain_set_id: __sdk::__query_builder::Col::new(table_name, "terrain_set_id"),
            chunk_morton: __sdk::__query_builder::Col::new(table_name, "chunk_morton"),
            content_hash: __sdk::__query_builder::Col::new(table_name, "content_hash"),
            version: __sdk::__query_builder::Col::new(table_name, "version"),
        }
    }
}

/// Indexed column accessor struct for the table `TerrainManifest`.
///
/// Provides typed access to indexed columns for query building.
pub struct TerrainManifestIxCols {
    pub row_id: __sdk::__query_builder::IxCol<TerrainManifest, u64>,
}

impl __sdk::__query_builder::HasIxCols for TerrainManifest {
    type IxCols = TerrainManifestIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        TerrainManifestIxCols {
            row_id: __sdk::__query_builder::IxCol::new(table_name, "row_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for TerrainManifest {}
