// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct TerrainSet {
    pub terrain_set_id: u32,
    pub name: String,
    pub content_hash: String,
    pub version: u32,
}

impl __sdk::InModule for TerrainSet {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `TerrainSet`.
///
/// Provides typed access to columns for query building.
pub struct TerrainSetCols {
    pub terrain_set_id: __sdk::__query_builder::Col<TerrainSet, u32>,
    pub name: __sdk::__query_builder::Col<TerrainSet, String>,
    pub content_hash: __sdk::__query_builder::Col<TerrainSet, String>,
    pub version: __sdk::__query_builder::Col<TerrainSet, u32>,
}

impl __sdk::__query_builder::HasCols for TerrainSet {
    type Cols = TerrainSetCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        TerrainSetCols {
            terrain_set_id: __sdk::__query_builder::Col::new(table_name, "terrain_set_id"),
            name: __sdk::__query_builder::Col::new(table_name, "name"),
            content_hash: __sdk::__query_builder::Col::new(table_name, "content_hash"),
            version: __sdk::__query_builder::Col::new(table_name, "version"),
        }
    }
}

/// Indexed column accessor struct for the table `TerrainSet`.
///
/// Provides typed access to indexed columns for query building.
pub struct TerrainSetIxCols {
    pub name: __sdk::__query_builder::IxCol<TerrainSet, String>,
    pub terrain_set_id: __sdk::__query_builder::IxCol<TerrainSet, u32>,
}

impl __sdk::__query_builder::HasIxCols for TerrainSet {
    type IxCols = TerrainSetIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        TerrainSetIxCols {
            name: __sdk::__query_builder::IxCol::new(table_name, "name"),
            terrain_set_id: __sdk::__query_builder::IxCol::new(table_name, "terrain_set_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for TerrainSet {}
