// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct TerrainSetUpsertArgs {
    pub name: String,
    pub content_hash: String,
    pub version: u32,
}

impl From<TerrainSetUpsertArgs> for super::Reducer {
    fn from(args: TerrainSetUpsertArgs) -> Self {
        Self::TerrainSetUpsert {
            name: args.name,
            content_hash: args.content_hash,
            version: args.version,
        }
    }
}

impl __sdk::InModule for TerrainSetUpsertArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `terrain_set_upsert`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait terrain_set_upsert {
    /// Request that the remote module invoke the reducer `terrain_set_upsert` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`terrain_set_upsert:terrain_set_upsert_then`] to run a callback after the reducer completes.
    fn terrain_set_upsert(
        &self,
        name: String,
        content_hash: String,
        version: u32,
    ) -> __sdk::Result<()> {
        self.terrain_set_upsert_then(name, content_hash, version, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `terrain_set_upsert` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn terrain_set_upsert_then(
        &self,
        name: String,
        content_hash: String,
        version: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl terrain_set_upsert for super::RemoteReducers {
    fn terrain_set_upsert_then(
        &self,
        name: String,
        content_hash: String,
        version: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            TerrainSetUpsertArgs {
                name,
                content_hash,
                version,
            },
            callback,
        )
    }
}
