// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::trusted_worker_type::TrustedWorker;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `trusted_worker`.
///
/// Obtain a handle from the [`TrustedWorkerTableAccess::trusted_worker`] method on [`super::RemoteTables`],
/// like `ctx.db.trusted_worker()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.trusted_worker().on_insert(...)`.
pub struct TrustedWorkerTableHandle<'ctx> {
    imp: __sdk::TableHandle<TrustedWorker>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `trusted_worker`.
///
/// Implemented for [`super::RemoteTables`].
pub trait TrustedWorkerTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`TrustedWorkerTableHandle`], which mediates access to the table `trusted_worker`.
    fn trusted_worker(&self) -> TrustedWorkerTableHandle<'_>;
}

impl TrustedWorkerTableAccess for super::RemoteTables {
    fn trusted_worker(&self) -> TrustedWorkerTableHandle<'_> {
        TrustedWorkerTableHandle {
            imp: self.imp.get_table::<TrustedWorker>("trusted_worker"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct TrustedWorkerInsertCallbackId(__sdk::CallbackId);
pub struct TrustedWorkerDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for TrustedWorkerTableHandle<'ctx> {
    type Row = TrustedWorker;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = TrustedWorker> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = TrustedWorkerInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TrustedWorkerInsertCallbackId {
        TrustedWorkerInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: TrustedWorkerInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = TrustedWorkerDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TrustedWorkerDeleteCallbackId {
        TrustedWorkerDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: TrustedWorkerDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct TrustedWorkerUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for TrustedWorkerTableHandle<'ctx> {
    type UpdateCallbackId = TrustedWorkerUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> TrustedWorkerUpdateCallbackId {
        TrustedWorkerUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: TrustedWorkerUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `worker_identity` unique index on the table `trusted_worker`,
/// which allows point queries on the field of the same name
/// via the [`TrustedWorkerWorkerIdentityUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.trusted_worker().worker_identity().find(...)`.
pub struct TrustedWorkerWorkerIdentityUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<TrustedWorker, __sdk::Identity>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> TrustedWorkerTableHandle<'ctx> {
    /// Get a handle on the `worker_identity` unique index on the table `trusted_worker`.
    pub fn worker_identity(&self) -> TrustedWorkerWorkerIdentityUnique<'ctx> {
        TrustedWorkerWorkerIdentityUnique {
            imp: self
                .imp
                .get_unique_constraint::<__sdk::Identity>("worker_identity"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> TrustedWorkerWorkerIdentityUnique<'ctx> {
    /// Find the subscribed row whose `worker_identity` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &__sdk::Identity) -> Option<TrustedWorker> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<TrustedWorker>("trusted_worker");
    _table.add_unique_constraint::<__sdk::Identity>("worker_identity", |row| &row.worker_identity);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<TrustedWorker>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<TrustedWorker>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `TrustedWorker`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait trusted_workerQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `TrustedWorker`.
    fn trusted_worker(&self) -> __sdk::__query_builder::Table<TrustedWorker>;
}

impl trusted_workerQueryTableAccess for __sdk::QueryTableAccessor {
    fn trusted_worker(&self) -> __sdk::__query_builder::Table<TrustedWorker> {
        __sdk::__query_builder::Table::new("trusted_worker")
    }
}
