// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct TrustedWorker {
    pub worker_identity: __sdk::Identity,
    pub rls_group: u8,
}

impl __sdk::InModule for TrustedWorker {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `TrustedWorker`.
///
/// Provides typed access to columns for query building.
pub struct TrustedWorkerCols {
    pub worker_identity: __sdk::__query_builder::Col<TrustedWorker, __sdk::Identity>,
    pub rls_group: __sdk::__query_builder::Col<TrustedWorker, u8>,
}

impl __sdk::__query_builder::HasCols for TrustedWorker {
    type Cols = TrustedWorkerCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        TrustedWorkerCols {
            worker_identity: __sdk::__query_builder::Col::new(table_name, "worker_identity"),
            rls_group: __sdk::__query_builder::Col::new(table_name, "rls_group"),
        }
    }
}

/// Indexed column accessor struct for the table `TrustedWorker`.
///
/// Provides typed access to indexed columns for query building.
pub struct TrustedWorkerIxCols {
    pub rls_group: __sdk::__query_builder::IxCol<TrustedWorker, u8>,
    pub worker_identity: __sdk::__query_builder::IxCol<TrustedWorker, __sdk::Identity>,
}

impl __sdk::__query_builder::HasIxCols for TrustedWorker {
    type IxCols = TrustedWorkerIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        TrustedWorkerIxCols {
            rls_group: __sdk::__query_builder::IxCol::new(table_name, "rls_group"),
            worker_identity: __sdk::__query_builder::IxCol::new(table_name, "worker_identity"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for TrustedWorker {}
