// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::ability_target_type::AbilityTarget;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct UseAbilityData {
    pub ability_id: u32,
    pub target: AbilityTarget,
    pub target_hint: Option<u64>,
}

impl __sdk::InModule for UseAbilityData {
    type Module = super::RemoteModule;
}
