// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct WorldPhase {
    pub zone_id: u32,
    pub phase_name: String,
    pub started_at: i64,
    pub metadata: String,
}

impl __sdk::InModule for WorldPhase {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `WorldPhase`.
///
/// Provides typed access to columns for query building.
pub struct WorldPhaseCols {
    pub zone_id: __sdk::__query_builder::Col<WorldPhase, u32>,
    pub phase_name: __sdk::__query_builder::Col<WorldPhase, String>,
    pub started_at: __sdk::__query_builder::Col<WorldPhase, i64>,
    pub metadata: __sdk::__query_builder::Col<WorldPhase, String>,
}

impl __sdk::__query_builder::HasCols for WorldPhase {
    type Cols = WorldPhaseCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        WorldPhaseCols {
            zone_id: __sdk::__query_builder::Col::new(table_name, "zone_id"),
            phase_name: __sdk::__query_builder::Col::new(table_name, "phase_name"),
            started_at: __sdk::__query_builder::Col::new(table_name, "started_at"),
            metadata: __sdk::__query_builder::Col::new(table_name, "metadata"),
        }
    }
}

/// Indexed column accessor struct for the table `WorldPhase`.
///
/// Provides typed access to indexed columns for query building.
pub struct WorldPhaseIxCols {
    pub zone_id: __sdk::__query_builder::IxCol<WorldPhase, u32>,
}

impl __sdk::__query_builder::HasIxCols for WorldPhase {
    type IxCols = WorldPhaseIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        WorldPhaseIxCols {
            zone_id: __sdk::__query_builder::IxCol::new(table_name, "zone_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for WorldPhase {}
