// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::world_event_kind_type::WorldEventKind;
use super::world_event_type::WorldEvent;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `world_event`.
///
/// Obtain a handle from the [`WorldEventTableAccess::world_event`] method on [`super::RemoteTables`],
/// like `ctx.db.world_event()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.world_event().on_insert(...)`.
pub struct WorldEventTableHandle<'ctx> {
    imp: __sdk::TableHandle<WorldEvent>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `world_event`.
///
/// Implemented for [`super::RemoteTables`].
pub trait WorldEventTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`WorldEventTableHandle`], which mediates access to the table `world_event`.
    fn world_event(&self) -> WorldEventTableHandle<'_>;
}

impl WorldEventTableAccess for super::RemoteTables {
    fn world_event(&self) -> WorldEventTableHandle<'_> {
        WorldEventTableHandle {
            imp: self.imp.get_table::<WorldEvent>("world_event"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct WorldEventInsertCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::EventTable for WorldEventTableHandle<'ctx> {
    type Row = WorldEvent;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = WorldEvent> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = WorldEventInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> WorldEventInsertCallbackId {
        WorldEventInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: WorldEventInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<WorldEvent>("world_event");
    _table.add_unique_constraint::<u64>("event_id", |row| &row.event_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<WorldEvent>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<WorldEvent>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `WorldEvent`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait world_eventQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `WorldEvent`.
    fn world_event(&self) -> __sdk::__query_builder::Table<WorldEvent>;
}

impl world_eventQueryTableAccess for __sdk::QueryTableAccessor {
    fn world_event(&self) -> __sdk::__query_builder::Table<WorldEvent> {
        __sdk::__query_builder::Table::new("world_event")
    }
}
