// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::world_event_kind_type::WorldEventKind;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct WorldEvent {
    pub event_id: u64,
    pub tick_id: u64,
    pub event_sequence: u32,
    pub entity_id: u64,
    pub event_kind: WorldEventKind,
}

impl __sdk::InModule for WorldEvent {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `WorldEvent`.
///
/// Provides typed access to columns for query building.
pub struct WorldEventCols {
    pub event_id: __sdk::__query_builder::Col<WorldEvent, u64>,
    pub tick_id: __sdk::__query_builder::Col<WorldEvent, u64>,
    pub event_sequence: __sdk::__query_builder::Col<WorldEvent, u32>,
    pub entity_id: __sdk::__query_builder::Col<WorldEvent, u64>,
    pub event_kind: __sdk::__query_builder::Col<WorldEvent, WorldEventKind>,
}

impl __sdk::__query_builder::HasCols for WorldEvent {
    type Cols = WorldEventCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        WorldEventCols {
            event_id: __sdk::__query_builder::Col::new(table_name, "event_id"),
            tick_id: __sdk::__query_builder::Col::new(table_name, "tick_id"),
            event_sequence: __sdk::__query_builder::Col::new(table_name, "event_sequence"),
            entity_id: __sdk::__query_builder::Col::new(table_name, "entity_id"),
            event_kind: __sdk::__query_builder::Col::new(table_name, "event_kind"),
        }
    }
}

/// Indexed column accessor struct for the table `WorldEvent`.
///
/// Provides typed access to indexed columns for query building.
pub struct WorldEventIxCols {
    pub event_id: __sdk::__query_builder::IxCol<WorldEvent, u64>,
    pub tick_id: __sdk::__query_builder::IxCol<WorldEvent, u64>,
}

impl __sdk::__query_builder::HasIxCols for WorldEvent {
    type IxCols = WorldEventIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        WorldEventIxCols {
            event_id: __sdk::__query_builder::IxCol::new(table_name, "event_id"),
            tick_id: __sdk::__query_builder::IxCol::new(table_name, "tick_id"),
        }
    }
}
