// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct ZoneCounter {
    pub counter_id: u64,
    pub layer: u32,
    pub region_x: i32,
    pub region_z: i32,
    pub counter_name: String,
    pub value: f64,
}

impl __sdk::InModule for ZoneCounter {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `ZoneCounter`.
///
/// Provides typed access to columns for query building.
pub struct ZoneCounterCols {
    pub counter_id: __sdk::__query_builder::Col<ZoneCounter, u64>,
    pub layer: __sdk::__query_builder::Col<ZoneCounter, u32>,
    pub region_x: __sdk::__query_builder::Col<ZoneCounter, i32>,
    pub region_z: __sdk::__query_builder::Col<ZoneCounter, i32>,
    pub counter_name: __sdk::__query_builder::Col<ZoneCounter, String>,
    pub value: __sdk::__query_builder::Col<ZoneCounter, f64>,
}

impl __sdk::__query_builder::HasCols for ZoneCounter {
    type Cols = ZoneCounterCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        ZoneCounterCols {
            counter_id: __sdk::__query_builder::Col::new(table_name, "counter_id"),
            layer: __sdk::__query_builder::Col::new(table_name, "layer"),
            region_x: __sdk::__query_builder::Col::new(table_name, "region_x"),
            region_z: __sdk::__query_builder::Col::new(table_name, "region_z"),
            counter_name: __sdk::__query_builder::Col::new(table_name, "counter_name"),
            value: __sdk::__query_builder::Col::new(table_name, "value"),
        }
    }
}

/// Indexed column accessor struct for the table `ZoneCounter`.
///
/// Provides typed access to indexed columns for query building.
pub struct ZoneCounterIxCols {
    pub counter_id: __sdk::__query_builder::IxCol<ZoneCounter, u64>,
}

impl __sdk::__query_builder::HasIxCols for ZoneCounter {
    type IxCols = ZoneCounterIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        ZoneCounterIxCols {
            counter_id: __sdk::__query_builder::IxCol::new(table_name, "counter_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for ZoneCounter {}
