// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::zone_counter_type::ZoneCounter;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `zone_counter`.
///
/// Obtain a handle from the [`ZoneCounterTableAccess::zone_counter`] method on [`super::RemoteTables`],
/// like `ctx.db.zone_counter()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.zone_counter().on_insert(...)`.
pub struct ZoneCounterTableHandle<'ctx> {
    imp: __sdk::TableHandle<ZoneCounter>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `zone_counter`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ZoneCounterTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ZoneCounterTableHandle`], which mediates access to the table `zone_counter`.
    fn zone_counter(&self) -> ZoneCounterTableHandle<'_>;
}

impl ZoneCounterTableAccess for super::RemoteTables {
    fn zone_counter(&self) -> ZoneCounterTableHandle<'_> {
        ZoneCounterTableHandle {
            imp: self.imp.get_table::<ZoneCounter>("zone_counter"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ZoneCounterInsertCallbackId(__sdk::CallbackId);
pub struct ZoneCounterDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for ZoneCounterTableHandle<'ctx> {
    type Row = ZoneCounter;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = ZoneCounter> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = ZoneCounterInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ZoneCounterInsertCallbackId {
        ZoneCounterInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ZoneCounterInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = ZoneCounterDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ZoneCounterDeleteCallbackId {
        ZoneCounterDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ZoneCounterDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct ZoneCounterUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for ZoneCounterTableHandle<'ctx> {
    type UpdateCallbackId = ZoneCounterUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ZoneCounterUpdateCallbackId {
        ZoneCounterUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ZoneCounterUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `counter_id` unique index on the table `zone_counter`,
/// which allows point queries on the field of the same name
/// via the [`ZoneCounterCounterIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.zone_counter().counter_id().find(...)`.
pub struct ZoneCounterCounterIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<ZoneCounter, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> ZoneCounterTableHandle<'ctx> {
    /// Get a handle on the `counter_id` unique index on the table `zone_counter`.
    pub fn counter_id(&self) -> ZoneCounterCounterIdUnique<'ctx> {
        ZoneCounterCounterIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("counter_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> ZoneCounterCounterIdUnique<'ctx> {
    /// Find the subscribed row whose `counter_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<ZoneCounter> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<ZoneCounter>("zone_counter");
    _table.add_unique_constraint::<u64>("counter_id", |row| &row.counter_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<ZoneCounter>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<ZoneCounter>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `ZoneCounter`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait zone_counterQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `ZoneCounter`.
    fn zone_counter(&self) -> __sdk::__query_builder::Table<ZoneCounter>;
}

impl zone_counterQueryTableAccess for __sdk::QueryTableAccessor {
    fn zone_counter(&self) -> __sdk::__query_builder::Table<ZoneCounter> {
        __sdk::__query_builder::Table::new("zone_counter")
    }
}
