// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::vec_3_f_type::Vec3F;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub enum AbilityTarget {
    None,

    Entity(u64),

    Position(Vec3F),

    Direction(Vec3F),
}

impl __sdk::InModule for AbilityTarget {
    type Module = super::RemoteModule;
}
