// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct ActiveBuff {
    pub buff_instance_id: u64,
    pub entity_id: u64,
    pub buff_id: u32,
    pub source_entity: u64,
    pub stacks: u32,
    pub expires_at_tick: Option<u64>,
    pub mod_ai_override_kind: Option<u8>,
    pub mod_ai_override_target: Option<u64>,
    pub mod_stealth: Option<bool>,
    pub last_dot_tick: Option<u64>,
}

impl __sdk::InModule for ActiveBuff {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `ActiveBuff`.
///
/// Provides typed access to columns for query building.
pub struct ActiveBuffCols {
    pub buff_instance_id: __sdk::__query_builder::Col<ActiveBuff, u64>,
    pub entity_id: __sdk::__query_builder::Col<ActiveBuff, u64>,
    pub buff_id: __sdk::__query_builder::Col<ActiveBuff, u32>,
    pub source_entity: __sdk::__query_builder::Col<ActiveBuff, u64>,
    pub stacks: __sdk::__query_builder::Col<ActiveBuff, u32>,
    pub expires_at_tick: __sdk::__query_builder::Col<ActiveBuff, Option<u64>>,
    pub mod_ai_override_kind: __sdk::__query_builder::Col<ActiveBuff, Option<u8>>,
    pub mod_ai_override_target: __sdk::__query_builder::Col<ActiveBuff, Option<u64>>,
    pub mod_stealth: __sdk::__query_builder::Col<ActiveBuff, Option<bool>>,
    pub last_dot_tick: __sdk::__query_builder::Col<ActiveBuff, Option<u64>>,
}

impl __sdk::__query_builder::HasCols for ActiveBuff {
    type Cols = ActiveBuffCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        ActiveBuffCols {
            buff_instance_id: __sdk::__query_builder::Col::new(table_name, "buff_instance_id"),
            entity_id: __sdk::__query_builder::Col::new(table_name, "entity_id"),
            buff_id: __sdk::__query_builder::Col::new(table_name, "buff_id"),
            source_entity: __sdk::__query_builder::Col::new(table_name, "source_entity"),
            stacks: __sdk::__query_builder::Col::new(table_name, "stacks"),
            expires_at_tick: __sdk::__query_builder::Col::new(table_name, "expires_at_tick"),
            mod_ai_override_kind: __sdk::__query_builder::Col::new(
                table_name,
                "mod_ai_override_kind",
            ),
            mod_ai_override_target: __sdk::__query_builder::Col::new(
                table_name,
                "mod_ai_override_target",
            ),
            mod_stealth: __sdk::__query_builder::Col::new(table_name, "mod_stealth"),
            last_dot_tick: __sdk::__query_builder::Col::new(table_name, "last_dot_tick"),
        }
    }
}

/// Indexed column accessor struct for the table `ActiveBuff`.
///
/// Provides typed access to indexed columns for query building.
pub struct ActiveBuffIxCols {
    pub buff_instance_id: __sdk::__query_builder::IxCol<ActiveBuff, u64>,
    pub entity_id: __sdk::__query_builder::IxCol<ActiveBuff, u64>,
}

impl __sdk::__query_builder::HasIxCols for ActiveBuff {
    type IxCols = ActiveBuffIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        ActiveBuffIxCols {
            buff_instance_id: __sdk::__query_builder::IxCol::new(table_name, "buff_instance_id"),
            entity_id: __sdk::__query_builder::IxCol::new(table_name, "entity_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for ActiveBuff {}
