// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::active_buff_type::ActiveBuff;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `active_buff`.
///
/// Obtain a handle from the [`ActiveBuffTableAccess::active_buff`] method on [`super::RemoteTables`],
/// like `ctx.db.active_buff()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.active_buff().on_insert(...)`.
pub struct ActiveBuffTableHandle<'ctx> {
    imp: __sdk::TableHandle<ActiveBuff>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `active_buff`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ActiveBuffTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ActiveBuffTableHandle`], which mediates access to the table `active_buff`.
    fn active_buff(&self) -> ActiveBuffTableHandle<'_>;
}

impl ActiveBuffTableAccess for super::RemoteTables {
    fn active_buff(&self) -> ActiveBuffTableHandle<'_> {
        ActiveBuffTableHandle {
            imp: self.imp.get_table::<ActiveBuff>("active_buff"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ActiveBuffInsertCallbackId(__sdk::CallbackId);
pub struct ActiveBuffDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for ActiveBuffTableHandle<'ctx> {
    type Row = ActiveBuff;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = ActiveBuff> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = ActiveBuffInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ActiveBuffInsertCallbackId {
        ActiveBuffInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ActiveBuffInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = ActiveBuffDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ActiveBuffDeleteCallbackId {
        ActiveBuffDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ActiveBuffDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct ActiveBuffUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for ActiveBuffTableHandle<'ctx> {
    type UpdateCallbackId = ActiveBuffUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ActiveBuffUpdateCallbackId {
        ActiveBuffUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ActiveBuffUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `buff_instance_id` unique index on the table `active_buff`,
/// which allows point queries on the field of the same name
/// via the [`ActiveBuffBuffInstanceIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.active_buff().buff_instance_id().find(...)`.
pub struct ActiveBuffBuffInstanceIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<ActiveBuff, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> ActiveBuffTableHandle<'ctx> {
    /// Get a handle on the `buff_instance_id` unique index on the table `active_buff`.
    pub fn buff_instance_id(&self) -> ActiveBuffBuffInstanceIdUnique<'ctx> {
        ActiveBuffBuffInstanceIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("buff_instance_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> ActiveBuffBuffInstanceIdUnique<'ctx> {
    /// Find the subscribed row whose `buff_instance_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<ActiveBuff> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<ActiveBuff>("active_buff");
    _table.add_unique_constraint::<u64>("buff_instance_id", |row| &row.buff_instance_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<ActiveBuff>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<ActiveBuff>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `ActiveBuff`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait active_buffQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `ActiveBuff`.
    fn active_buff(&self) -> __sdk::__query_builder::Table<ActiveBuff>;
}

impl active_buffQueryTableAccess for __sdk::QueryTableAccessor {
    fn active_buff(&self) -> __sdk::__query_builder::Table<ActiveBuff> {
        __sdk::__query_builder::Table::new("active_buff")
    }
}
