// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::intent_action_type::IntentAction;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct BatchedIntent {
    pub sequence_id: u64,
    pub client_observed_tick: u64,
    pub action: IntentAction,
}

impl __sdk::InModule for BatchedIntent {
    type Module = super::RemoteModule;
}
