// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::client_sequence_type::ClientSequence;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `client_sequence`.
///
/// Obtain a handle from the [`ClientSequenceTableAccess::client_sequence`] method on [`super::RemoteTables`],
/// like `ctx.db.client_sequence()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.client_sequence().on_insert(...)`.
pub struct ClientSequenceTableHandle<'ctx> {
    imp: __sdk::TableHandle<ClientSequence>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `client_sequence`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ClientSequenceTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ClientSequenceTableHandle`], which mediates access to the table `client_sequence`.
    fn client_sequence(&self) -> ClientSequenceTableHandle<'_>;
}

impl ClientSequenceTableAccess for super::RemoteTables {
    fn client_sequence(&self) -> ClientSequenceTableHandle<'_> {
        ClientSequenceTableHandle {
            imp: self.imp.get_table::<ClientSequence>("client_sequence"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ClientSequenceInsertCallbackId(__sdk::CallbackId);
pub struct ClientSequenceDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for ClientSequenceTableHandle<'ctx> {
    type Row = ClientSequence;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = ClientSequence> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = ClientSequenceInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ClientSequenceInsertCallbackId {
        ClientSequenceInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ClientSequenceInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = ClientSequenceDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ClientSequenceDeleteCallbackId {
        ClientSequenceDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ClientSequenceDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct ClientSequenceUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for ClientSequenceTableHandle<'ctx> {
    type UpdateCallbackId = ClientSequenceUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ClientSequenceUpdateCallbackId {
        ClientSequenceUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ClientSequenceUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `client_identity` unique index on the table `client_sequence`,
/// which allows point queries on the field of the same name
/// via the [`ClientSequenceClientIdentityUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.client_sequence().client_identity().find(...)`.
pub struct ClientSequenceClientIdentityUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<ClientSequence, __sdk::Identity>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> ClientSequenceTableHandle<'ctx> {
    /// Get a handle on the `client_identity` unique index on the table `client_sequence`.
    pub fn client_identity(&self) -> ClientSequenceClientIdentityUnique<'ctx> {
        ClientSequenceClientIdentityUnique {
            imp: self
                .imp
                .get_unique_constraint::<__sdk::Identity>("client_identity"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> ClientSequenceClientIdentityUnique<'ctx> {
    /// Find the subscribed row whose `client_identity` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &__sdk::Identity) -> Option<ClientSequence> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<ClientSequence>("client_sequence");
    _table.add_unique_constraint::<__sdk::Identity>("client_identity", |row| &row.client_identity);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<ClientSequence>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<ClientSequence>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `ClientSequence`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait client_sequenceQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `ClientSequence`.
    fn client_sequence(&self) -> __sdk::__query_builder::Table<ClientSequence>;
}

impl client_sequenceQueryTableAccess for __sdk::QueryTableAccessor {
    fn client_sequence(&self) -> __sdk::__query_builder::Table<ClientSequence> {
        __sdk::__query_builder::Table::new("client_sequence")
    }
}
