// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::combat_event_kind_type::CombatEventKind;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct CombatEvent {
    pub event_id: u64,
    pub tick_id: u64,
    pub event_sequence: u32,
    pub source_entity: u64,
    pub target_entity: u64,
    pub event_kind: CombatEventKind,
}

impl __sdk::InModule for CombatEvent {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `CombatEvent`.
///
/// Provides typed access to columns for query building.
pub struct CombatEventCols {
    pub event_id: __sdk::__query_builder::Col<CombatEvent, u64>,
    pub tick_id: __sdk::__query_builder::Col<CombatEvent, u64>,
    pub event_sequence: __sdk::__query_builder::Col<CombatEvent, u32>,
    pub source_entity: __sdk::__query_builder::Col<CombatEvent, u64>,
    pub target_entity: __sdk::__query_builder::Col<CombatEvent, u64>,
    pub event_kind: __sdk::__query_builder::Col<CombatEvent, CombatEventKind>,
}

impl __sdk::__query_builder::HasCols for CombatEvent {
    type Cols = CombatEventCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        CombatEventCols {
            event_id: __sdk::__query_builder::Col::new(table_name, "event_id"),
            tick_id: __sdk::__query_builder::Col::new(table_name, "tick_id"),
            event_sequence: __sdk::__query_builder::Col::new(table_name, "event_sequence"),
            source_entity: __sdk::__query_builder::Col::new(table_name, "source_entity"),
            target_entity: __sdk::__query_builder::Col::new(table_name, "target_entity"),
            event_kind: __sdk::__query_builder::Col::new(table_name, "event_kind"),
        }
    }
}

/// Indexed column accessor struct for the table `CombatEvent`.
///
/// Provides typed access to indexed columns for query building.
pub struct CombatEventIxCols {
    pub event_id: __sdk::__query_builder::IxCol<CombatEvent, u64>,
    pub tick_id: __sdk::__query_builder::IxCol<CombatEvent, u64>,
}

impl __sdk::__query_builder::HasIxCols for CombatEvent {
    type IxCols = CombatEventIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        CombatEventIxCols {
            event_id: __sdk::__query_builder::IxCol::new(table_name, "event_id"),
            tick_id: __sdk::__query_builder::IxCol::new(table_name, "tick_id"),
        }
    }
}
