// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::death_state_type::DeathState;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `death_state`.
///
/// Obtain a handle from the [`DeathStateTableAccess::death_state`] method on [`super::RemoteTables`],
/// like `ctx.db.death_state()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.death_state().on_insert(...)`.
pub struct DeathStateTableHandle<'ctx> {
    imp: __sdk::TableHandle<DeathState>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `death_state`.
///
/// Implemented for [`super::RemoteTables`].
pub trait DeathStateTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`DeathStateTableHandle`], which mediates access to the table `death_state`.
    fn death_state(&self) -> DeathStateTableHandle<'_>;
}

impl DeathStateTableAccess for super::RemoteTables {
    fn death_state(&self) -> DeathStateTableHandle<'_> {
        DeathStateTableHandle {
            imp: self.imp.get_table::<DeathState>("death_state"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct DeathStateInsertCallbackId(__sdk::CallbackId);
pub struct DeathStateDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for DeathStateTableHandle<'ctx> {
    type Row = DeathState;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = DeathState> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = DeathStateInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> DeathStateInsertCallbackId {
        DeathStateInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: DeathStateInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = DeathStateDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> DeathStateDeleteCallbackId {
        DeathStateDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: DeathStateDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct DeathStateUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for DeathStateTableHandle<'ctx> {
    type UpdateCallbackId = DeathStateUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> DeathStateUpdateCallbackId {
        DeathStateUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: DeathStateUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `entity_id` unique index on the table `death_state`,
/// which allows point queries on the field of the same name
/// via the [`DeathStateEntityIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.death_state().entity_id().find(...)`.
pub struct DeathStateEntityIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<DeathState, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> DeathStateTableHandle<'ctx> {
    /// Get a handle on the `entity_id` unique index on the table `death_state`.
    pub fn entity_id(&self) -> DeathStateEntityIdUnique<'ctx> {
        DeathStateEntityIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("entity_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> DeathStateEntityIdUnique<'ctx> {
    /// Find the subscribed row whose `entity_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<DeathState> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<DeathState>("death_state");
    _table.add_unique_constraint::<u64>("entity_id", |row| &row.entity_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<DeathState>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<DeathState>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `DeathState`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait death_stateQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `DeathState`.
    fn death_state(&self) -> __sdk::__query_builder::Table<DeathState>;
}

impl death_stateQueryTableAccess for __sdk::QueryTableAccessor {
    fn death_state(&self) -> __sdk::__query_builder::Table<DeathState> {
        __sdk::__query_builder::Table::new("death_state")
    }
}
