// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct DebugTeleportArgs {
    pub entity_id: u64,
    pub x: f32,
    pub y: f32,
    pub z: f32,
}

impl From<DebugTeleportArgs> for super::Reducer {
    fn from(args: DebugTeleportArgs) -> Self {
        Self::DebugTeleport {
            entity_id: args.entity_id,
            x: args.x,
            y: args.y,
            z: args.z,
        }
    }
}

impl __sdk::InModule for DebugTeleportArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `debug_teleport`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait debug_teleport {
    /// Request that the remote module invoke the reducer `debug_teleport` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`debug_teleport:debug_teleport_then`] to run a callback after the reducer completes.
    fn debug_teleport(&self, entity_id: u64, x: f32, y: f32, z: f32) -> __sdk::Result<()> {
        self.debug_teleport_then(entity_id, x, y, z, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `debug_teleport` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn debug_teleport_then(
        &self,
        entity_id: u64,
        x: f32,
        y: f32,
        z: f32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl debug_teleport for super::RemoteReducers {
    fn debug_teleport_then(
        &self,
        entity_id: u64,
        x: f32,
        y: f32,
        z: f32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(DebugTeleportArgs { entity_id, x, y, z }, callback)
    }
}
