// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct DebugSetLayerArgs {
    pub entity_id: u64,
    pub layer: u32,
}

impl From<DebugSetLayerArgs> for super::Reducer {
    fn from(args: DebugSetLayerArgs) -> Self {
        Self::DebugSetLayer {
            entity_id: args.entity_id,
            layer: args.layer,
        }
    }
}

impl __sdk::InModule for DebugSetLayerArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `debug_set_layer`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait debug_set_layer {
    /// Request that the remote module invoke the reducer `debug_set_layer` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`debug_set_layer:debug_set_layer_then`] to run a callback after the reducer completes.
    fn debug_set_layer(&self, entity_id: u64, layer: u32) -> __sdk::Result<()> {
        self.debug_set_layer_then(entity_id, layer, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `debug_set_layer` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn debug_set_layer_then(
        &self,
        entity_id: u64,
        layer: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl debug_set_layer for super::RemoteReducers {
    fn debug_set_layer_then(
        &self,
        entity_id: u64,
        layer: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(DebugSetLayerArgs { entity_id, layer }, callback)
    }
}
