// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct EncounterAdd {
    pub add_entity: u64,
    pub boss_entity: u64,
    pub tags: Vec<String>,
    pub archetype: String,
    pub spawned_at_tick: u64,
}

impl __sdk::InModule for EncounterAdd {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `EncounterAdd`.
///
/// Provides typed access to columns for query building.
pub struct EncounterAddCols {
    pub add_entity: __sdk::__query_builder::Col<EncounterAdd, u64>,
    pub boss_entity: __sdk::__query_builder::Col<EncounterAdd, u64>,
    pub tags: __sdk::__query_builder::Col<EncounterAdd, Vec<String>>,
    pub archetype: __sdk::__query_builder::Col<EncounterAdd, String>,
    pub spawned_at_tick: __sdk::__query_builder::Col<EncounterAdd, u64>,
}

impl __sdk::__query_builder::HasCols for EncounterAdd {
    type Cols = EncounterAddCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        EncounterAddCols {
            add_entity: __sdk::__query_builder::Col::new(table_name, "add_entity"),
            boss_entity: __sdk::__query_builder::Col::new(table_name, "boss_entity"),
            tags: __sdk::__query_builder::Col::new(table_name, "tags"),
            archetype: __sdk::__query_builder::Col::new(table_name, "archetype"),
            spawned_at_tick: __sdk::__query_builder::Col::new(table_name, "spawned_at_tick"),
        }
    }
}

/// Indexed column accessor struct for the table `EncounterAdd`.
///
/// Provides typed access to indexed columns for query building.
pub struct EncounterAddIxCols {
    pub add_entity: __sdk::__query_builder::IxCol<EncounterAdd, u64>,
    pub boss_entity: __sdk::__query_builder::IxCol<EncounterAdd, u64>,
}

impl __sdk::__query_builder::HasIxCols for EncounterAdd {
    type IxCols = EncounterAddIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        EncounterAddIxCols {
            add_entity: __sdk::__query_builder::IxCol::new(table_name, "add_entity"),
            boss_entity: __sdk::__query_builder::IxCol::new(table_name, "boss_entity"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for EncounterAdd {}
