// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct EncounterCueData {
    pub cue_id: String,
    pub anchor_entity: Option<u64>,
    pub pos_x: f32,
    pub pos_y: f32,
    pub pos_z: f32,
    pub shape: String,
    pub inner_radius: f32,
    pub outer_radius: f32,
    pub half_height: f32,
    pub starts_at_tick: u64,
    pub expires_at_tick: u64,
}

impl __sdk::InModule for EncounterCueData {
    type Module = super::RemoteModule;
}
