// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::encounter_add_type::EncounterAdd;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `encounter_add`.
///
/// Obtain a handle from the [`EncounterAddTableAccess::encounter_add`] method on [`super::RemoteTables`],
/// like `ctx.db.encounter_add()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.encounter_add().on_insert(...)`.
pub struct EncounterAddTableHandle<'ctx> {
    imp: __sdk::TableHandle<EncounterAdd>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `encounter_add`.
///
/// Implemented for [`super::RemoteTables`].
pub trait EncounterAddTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`EncounterAddTableHandle`], which mediates access to the table `encounter_add`.
    fn encounter_add(&self) -> EncounterAddTableHandle<'_>;
}

impl EncounterAddTableAccess for super::RemoteTables {
    fn encounter_add(&self) -> EncounterAddTableHandle<'_> {
        EncounterAddTableHandle {
            imp: self.imp.get_table::<EncounterAdd>("encounter_add"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct EncounterAddInsertCallbackId(__sdk::CallbackId);
pub struct EncounterAddDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for EncounterAddTableHandle<'ctx> {
    type Row = EncounterAdd;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = EncounterAdd> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = EncounterAddInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> EncounterAddInsertCallbackId {
        EncounterAddInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: EncounterAddInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = EncounterAddDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> EncounterAddDeleteCallbackId {
        EncounterAddDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: EncounterAddDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct EncounterAddUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for EncounterAddTableHandle<'ctx> {
    type UpdateCallbackId = EncounterAddUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> EncounterAddUpdateCallbackId {
        EncounterAddUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: EncounterAddUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `add_entity` unique index on the table `encounter_add`,
/// which allows point queries on the field of the same name
/// via the [`EncounterAddAddEntityUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.encounter_add().add_entity().find(...)`.
pub struct EncounterAddAddEntityUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<EncounterAdd, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> EncounterAddTableHandle<'ctx> {
    /// Get a handle on the `add_entity` unique index on the table `encounter_add`.
    pub fn add_entity(&self) -> EncounterAddAddEntityUnique<'ctx> {
        EncounterAddAddEntityUnique {
            imp: self.imp.get_unique_constraint::<u64>("add_entity"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> EncounterAddAddEntityUnique<'ctx> {
    /// Find the subscribed row whose `add_entity` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<EncounterAdd> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<EncounterAdd>("encounter_add");
    _table.add_unique_constraint::<u64>("add_entity", |row| &row.add_entity);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<EncounterAdd>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<EncounterAdd>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `EncounterAdd`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait encounter_addQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `EncounterAdd`.
    fn encounter_add(&self) -> __sdk::__query_builder::Table<EncounterAdd>;
}

impl encounter_addQueryTableAccess for __sdk::QueryTableAccessor {
    fn encounter_add(&self) -> __sdk::__query_builder::Table<EncounterAdd> {
        __sdk::__query_builder::Table::new("encounter_add")
    }
}
