// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::entity_team_type::EntityTeam;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `entity_team`.
///
/// Obtain a handle from the [`EntityTeamTableAccess::entity_team`] method on [`super::RemoteTables`],
/// like `ctx.db.entity_team()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.entity_team().on_insert(...)`.
pub struct EntityTeamTableHandle<'ctx> {
    imp: __sdk::TableHandle<EntityTeam>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `entity_team`.
///
/// Implemented for [`super::RemoteTables`].
pub trait EntityTeamTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`EntityTeamTableHandle`], which mediates access to the table `entity_team`.
    fn entity_team(&self) -> EntityTeamTableHandle<'_>;
}

impl EntityTeamTableAccess for super::RemoteTables {
    fn entity_team(&self) -> EntityTeamTableHandle<'_> {
        EntityTeamTableHandle {
            imp: self.imp.get_table::<EntityTeam>("entity_team"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct EntityTeamInsertCallbackId(__sdk::CallbackId);
pub struct EntityTeamDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for EntityTeamTableHandle<'ctx> {
    type Row = EntityTeam;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = EntityTeam> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = EntityTeamInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> EntityTeamInsertCallbackId {
        EntityTeamInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: EntityTeamInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = EntityTeamDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> EntityTeamDeleteCallbackId {
        EntityTeamDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: EntityTeamDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct EntityTeamUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for EntityTeamTableHandle<'ctx> {
    type UpdateCallbackId = EntityTeamUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> EntityTeamUpdateCallbackId {
        EntityTeamUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: EntityTeamUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `entity_id` unique index on the table `entity_team`,
/// which allows point queries on the field of the same name
/// via the [`EntityTeamEntityIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.entity_team().entity_id().find(...)`.
pub struct EntityTeamEntityIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<EntityTeam, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> EntityTeamTableHandle<'ctx> {
    /// Get a handle on the `entity_id` unique index on the table `entity_team`.
    pub fn entity_id(&self) -> EntityTeamEntityIdUnique<'ctx> {
        EntityTeamEntityIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("entity_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> EntityTeamEntityIdUnique<'ctx> {
    /// Find the subscribed row whose `entity_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<EntityTeam> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<EntityTeam>("entity_team");
    _table.add_unique_constraint::<u64>("entity_id", |row| &row.entity_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<EntityTeam>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<EntityTeam>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `EntityTeam`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait entity_teamQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `EntityTeam`.
    fn entity_team(&self) -> __sdk::__query_builder::Table<EntityTeam>;
}

impl entity_teamQueryTableAccess for __sdk::QueryTableAccessor {
    fn entity_team(&self) -> __sdk::__query_builder::Table<EntityTeam> {
        __sdk::__query_builder::Table::new("entity_team")
    }
}
