// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct EntityTeam {
    pub entity_id: u64,
    pub team_id: u32,
}

impl __sdk::InModule for EntityTeam {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `EntityTeam`.
///
/// Provides typed access to columns for query building.
pub struct EntityTeamCols {
    pub entity_id: __sdk::__query_builder::Col<EntityTeam, u64>,
    pub team_id: __sdk::__query_builder::Col<EntityTeam, u32>,
}

impl __sdk::__query_builder::HasCols for EntityTeam {
    type Cols = EntityTeamCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        EntityTeamCols {
            entity_id: __sdk::__query_builder::Col::new(table_name, "entity_id"),
            team_id: __sdk::__query_builder::Col::new(table_name, "team_id"),
        }
    }
}

/// Indexed column accessor struct for the table `EntityTeam`.
///
/// Provides typed access to indexed columns for query building.
pub struct EntityTeamIxCols {
    pub entity_id: __sdk::__query_builder::IxCol<EntityTeam, u64>,
}

impl __sdk::__query_builder::HasIxCols for EntityTeam {
    type IxCols = EntityTeamIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        EntityTeamIxCols {
            entity_id: __sdk::__query_builder::IxCol::new(table_name, "entity_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for EntityTeam {}
