// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct EntityHealth {
    pub entity_id: u64,
    pub hp: f32,
    pub max_hp: f32,
    pub rls_group: u8,
}

impl __sdk::InModule for EntityHealth {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `EntityHealth`.
///
/// Provides typed access to columns for query building.
pub struct EntityHealthCols {
    pub entity_id: __sdk::__query_builder::Col<EntityHealth, u64>,
    pub hp: __sdk::__query_builder::Col<EntityHealth, f32>,
    pub max_hp: __sdk::__query_builder::Col<EntityHealth, f32>,
    pub rls_group: __sdk::__query_builder::Col<EntityHealth, u8>,
}

impl __sdk::__query_builder::HasCols for EntityHealth {
    type Cols = EntityHealthCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        EntityHealthCols {
            entity_id: __sdk::__query_builder::Col::new(table_name, "entity_id"),
            hp: __sdk::__query_builder::Col::new(table_name, "hp"),
            max_hp: __sdk::__query_builder::Col::new(table_name, "max_hp"),
            rls_group: __sdk::__query_builder::Col::new(table_name, "rls_group"),
        }
    }
}

/// Indexed column accessor struct for the table `EntityHealth`.
///
/// Provides typed access to indexed columns for query building.
pub struct EntityHealthIxCols {
    pub entity_id: __sdk::__query_builder::IxCol<EntityHealth, u64>,
    pub rls_group: __sdk::__query_builder::IxCol<EntityHealth, u8>,
}

impl __sdk::__query_builder::HasIxCols for EntityHealth {
    type IxCols = EntityHealthIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        EntityHealthIxCols {
            entity_id: __sdk::__query_builder::IxCol::new(table_name, "entity_id"),
            rls_group: __sdk::__query_builder::IxCol::new(table_name, "rls_group"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for EntityHealth {}
