// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct EntityLayer {
    pub entity_id: u64,
    pub layer: u32,
}

impl __sdk::InModule for EntityLayer {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `EntityLayer`.
///
/// Provides typed access to columns for query building.
pub struct EntityLayerCols {
    pub entity_id: __sdk::__query_builder::Col<EntityLayer, u64>,
    pub layer: __sdk::__query_builder::Col<EntityLayer, u32>,
}

impl __sdk::__query_builder::HasCols for EntityLayer {
    type Cols = EntityLayerCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        EntityLayerCols {
            entity_id: __sdk::__query_builder::Col::new(table_name, "entity_id"),
            layer: __sdk::__query_builder::Col::new(table_name, "layer"),
        }
    }
}

/// Indexed column accessor struct for the table `EntityLayer`.
///
/// Provides typed access to indexed columns for query building.
pub struct EntityLayerIxCols {
    pub entity_id: __sdk::__query_builder::IxCol<EntityLayer, u64>,
}

impl __sdk::__query_builder::HasIxCols for EntityLayer {
    type IxCols = EntityLayerIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        EntityLayerIxCols {
            entity_id: __sdk::__query_builder::IxCol::new(table_name, "entity_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for EntityLayer {}
