// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::entity_transform_type::EntityTransform;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `entity_transform`.
///
/// Obtain a handle from the [`EntityTransformTableAccess::entity_transform`] method on [`super::RemoteTables`],
/// like `ctx.db.entity_transform()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.entity_transform().on_insert(...)`.
pub struct EntityTransformTableHandle<'ctx> {
    imp: __sdk::TableHandle<EntityTransform>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `entity_transform`.
///
/// Implemented for [`super::RemoteTables`].
pub trait EntityTransformTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`EntityTransformTableHandle`], which mediates access to the table `entity_transform`.
    fn entity_transform(&self) -> EntityTransformTableHandle<'_>;
}

impl EntityTransformTableAccess for super::RemoteTables {
    fn entity_transform(&self) -> EntityTransformTableHandle<'_> {
        EntityTransformTableHandle {
            imp: self.imp.get_table::<EntityTransform>("entity_transform"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct EntityTransformInsertCallbackId(__sdk::CallbackId);
pub struct EntityTransformDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for EntityTransformTableHandle<'ctx> {
    type Row = EntityTransform;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = EntityTransform> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = EntityTransformInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> EntityTransformInsertCallbackId {
        EntityTransformInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: EntityTransformInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = EntityTransformDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> EntityTransformDeleteCallbackId {
        EntityTransformDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: EntityTransformDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct EntityTransformUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for EntityTransformTableHandle<'ctx> {
    type UpdateCallbackId = EntityTransformUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> EntityTransformUpdateCallbackId {
        EntityTransformUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: EntityTransformUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `entity_id` unique index on the table `entity_transform`,
/// which allows point queries on the field of the same name
/// via the [`EntityTransformEntityIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.entity_transform().entity_id().find(...)`.
pub struct EntityTransformEntityIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<EntityTransform, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> EntityTransformTableHandle<'ctx> {
    /// Get a handle on the `entity_id` unique index on the table `entity_transform`.
    pub fn entity_id(&self) -> EntityTransformEntityIdUnique<'ctx> {
        EntityTransformEntityIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("entity_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> EntityTransformEntityIdUnique<'ctx> {
    /// Find the subscribed row whose `entity_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<EntityTransform> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<EntityTransform>("entity_transform");
    _table.add_unique_constraint::<u64>("entity_id", |row| &row.entity_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<EntityTransform>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<EntityTransform>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `EntityTransform`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait entity_transformQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `EntityTransform`.
    fn entity_transform(&self) -> __sdk::__query_builder::Table<EntityTransform>;
}

impl entity_transformQueryTableAccess for __sdk::QueryTableAccessor {
    fn entity_transform(&self) -> __sdk::__query_builder::Table<EntityTransform> {
        __sdk::__query_builder::Table::new("entity_transform")
    }
}
