// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct EntityTransform {
    pub entity_id: u64,
    pub pos_x: f32,
    pub pos_y: f32,
    pub pos_z: f32,
    pub rot_x: f32,
    pub rot_y: f32,
    pub rot_z: f32,
    pub rot_w: f32,
    pub vel_x: f32,
    pub vel_y: f32,
    pub vel_z: f32,
    pub angvel_x: f32,
    pub angvel_y: f32,
    pub angvel_z: f32,
    pub last_tick: u64,
    pub rls_group: u8,
}

impl __sdk::InModule for EntityTransform {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `EntityTransform`.
///
/// Provides typed access to columns for query building.
pub struct EntityTransformCols {
    pub entity_id: __sdk::__query_builder::Col<EntityTransform, u64>,
    pub pos_x: __sdk::__query_builder::Col<EntityTransform, f32>,
    pub pos_y: __sdk::__query_builder::Col<EntityTransform, f32>,
    pub pos_z: __sdk::__query_builder::Col<EntityTransform, f32>,
    pub rot_x: __sdk::__query_builder::Col<EntityTransform, f32>,
    pub rot_y: __sdk::__query_builder::Col<EntityTransform, f32>,
    pub rot_z: __sdk::__query_builder::Col<EntityTransform, f32>,
    pub rot_w: __sdk::__query_builder::Col<EntityTransform, f32>,
    pub vel_x: __sdk::__query_builder::Col<EntityTransform, f32>,
    pub vel_y: __sdk::__query_builder::Col<EntityTransform, f32>,
    pub vel_z: __sdk::__query_builder::Col<EntityTransform, f32>,
    pub angvel_x: __sdk::__query_builder::Col<EntityTransform, f32>,
    pub angvel_y: __sdk::__query_builder::Col<EntityTransform, f32>,
    pub angvel_z: __sdk::__query_builder::Col<EntityTransform, f32>,
    pub last_tick: __sdk::__query_builder::Col<EntityTransform, u64>,
    pub rls_group: __sdk::__query_builder::Col<EntityTransform, u8>,
}

impl __sdk::__query_builder::HasCols for EntityTransform {
    type Cols = EntityTransformCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        EntityTransformCols {
            entity_id: __sdk::__query_builder::Col::new(table_name, "entity_id"),
            pos_x: __sdk::__query_builder::Col::new(table_name, "pos_x"),
            pos_y: __sdk::__query_builder::Col::new(table_name, "pos_y"),
            pos_z: __sdk::__query_builder::Col::new(table_name, "pos_z"),
            rot_x: __sdk::__query_builder::Col::new(table_name, "rot_x"),
            rot_y: __sdk::__query_builder::Col::new(table_name, "rot_y"),
            rot_z: __sdk::__query_builder::Col::new(table_name, "rot_z"),
            rot_w: __sdk::__query_builder::Col::new(table_name, "rot_w"),
            vel_x: __sdk::__query_builder::Col::new(table_name, "vel_x"),
            vel_y: __sdk::__query_builder::Col::new(table_name, "vel_y"),
            vel_z: __sdk::__query_builder::Col::new(table_name, "vel_z"),
            angvel_x: __sdk::__query_builder::Col::new(table_name, "angvel_x"),
            angvel_y: __sdk::__query_builder::Col::new(table_name, "angvel_y"),
            angvel_z: __sdk::__query_builder::Col::new(table_name, "angvel_z"),
            last_tick: __sdk::__query_builder::Col::new(table_name, "last_tick"),
            rls_group: __sdk::__query_builder::Col::new(table_name, "rls_group"),
        }
    }
}

/// Indexed column accessor struct for the table `EntityTransform`.
///
/// Provides typed access to indexed columns for query building.
pub struct EntityTransformIxCols {
    pub entity_id: __sdk::__query_builder::IxCol<EntityTransform, u64>,
    pub rls_group: __sdk::__query_builder::IxCol<EntityTransform, u8>,
}

impl __sdk::__query_builder::HasIxCols for EntityTransform {
    type IxCols = EntityTransformIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        EntityTransformIxCols {
            entity_id: __sdk::__query_builder::IxCol::new(table_name, "entity_id"),
            rls_group: __sdk::__query_builder::IxCol::new(table_name, "rls_group"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for EntityTransform {}
