// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct ExpireInstancesArgs {}

impl From<ExpireInstancesArgs> for super::Reducer {
    fn from(args: ExpireInstancesArgs) -> Self {
        Self::ExpireInstances
    }
}

impl __sdk::InModule for ExpireInstancesArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `expire_instances`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait expire_instances {
    /// Request that the remote module invoke the reducer `expire_instances` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`expire_instances:expire_instances_then`] to run a callback after the reducer completes.
    fn expire_instances(&self) -> __sdk::Result<()> {
        self.expire_instances_then(|_, _| {})
    }

    /// Request that the remote module invoke the reducer `expire_instances` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn expire_instances_then(
        &self,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl expire_instances for super::RemoteReducers {
    fn expire_instances_then(
        &self,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(ExpireInstancesArgs {}, callback)
    }
}
