// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct IncrementZoneCounterArgs {
    pub layer: u32,
    pub region_x: i32,
    pub region_z: i32,
    pub counter_name: String,
    pub delta: f64,
}

impl From<IncrementZoneCounterArgs> for super::Reducer {
    fn from(args: IncrementZoneCounterArgs) -> Self {
        Self::IncrementZoneCounter {
            layer: args.layer,
            region_x: args.region_x,
            region_z: args.region_z,
            counter_name: args.counter_name,
            delta: args.delta,
        }
    }
}

impl __sdk::InModule for IncrementZoneCounterArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `increment_zone_counter`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait increment_zone_counter {
    /// Request that the remote module invoke the reducer `increment_zone_counter` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`increment_zone_counter:increment_zone_counter_then`] to run a callback after the reducer completes.
    fn increment_zone_counter(
        &self,
        layer: u32,
        region_x: i32,
        region_z: i32,
        counter_name: String,
        delta: f64,
    ) -> __sdk::Result<()> {
        self.increment_zone_counter_then(layer, region_x, region_z, counter_name, delta, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `increment_zone_counter` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn increment_zone_counter_then(
        &self,
        layer: u32,
        region_x: i32,
        region_z: i32,
        counter_name: String,
        delta: f64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl increment_zone_counter for super::RemoteReducers {
    fn increment_zone_counter_then(
        &self,
        layer: u32,
        region_x: i32,
        region_z: i32,
        counter_name: String,
        delta: f64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            IncrementZoneCounterArgs {
                layer,
                region_x,
                region_z,
                counter_name,
                delta,
            },
            callback,
        )
    }
}
