// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::instance_state_type::InstanceState;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Instance {
    pub instance_id: u64,
    pub template_id: String,
    pub layer: u32,
    pub layer_group: u32,
    pub state: InstanceState,
    pub created_at: i64,
    pub expires_at: i64,
    pub max_players: u32,
}

impl __sdk::InModule for Instance {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Instance`.
///
/// Provides typed access to columns for query building.
pub struct InstanceCols {
    pub instance_id: __sdk::__query_builder::Col<Instance, u64>,
    pub template_id: __sdk::__query_builder::Col<Instance, String>,
    pub layer: __sdk::__query_builder::Col<Instance, u32>,
    pub layer_group: __sdk::__query_builder::Col<Instance, u32>,
    pub state: __sdk::__query_builder::Col<Instance, InstanceState>,
    pub created_at: __sdk::__query_builder::Col<Instance, i64>,
    pub expires_at: __sdk::__query_builder::Col<Instance, i64>,
    pub max_players: __sdk::__query_builder::Col<Instance, u32>,
}

impl __sdk::__query_builder::HasCols for Instance {
    type Cols = InstanceCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        InstanceCols {
            instance_id: __sdk::__query_builder::Col::new(table_name, "instance_id"),
            template_id: __sdk::__query_builder::Col::new(table_name, "template_id"),
            layer: __sdk::__query_builder::Col::new(table_name, "layer"),
            layer_group: __sdk::__query_builder::Col::new(table_name, "layer_group"),
            state: __sdk::__query_builder::Col::new(table_name, "state"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
            expires_at: __sdk::__query_builder::Col::new(table_name, "expires_at"),
            max_players: __sdk::__query_builder::Col::new(table_name, "max_players"),
        }
    }
}

/// Indexed column accessor struct for the table `Instance`.
///
/// Provides typed access to indexed columns for query building.
pub struct InstanceIxCols {
    pub instance_id: __sdk::__query_builder::IxCol<Instance, u64>,
}

impl __sdk::__query_builder::HasIxCols for Instance {
    type IxCols = InstanceIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        InstanceIxCols {
            instance_id: __sdk::__query_builder::IxCol::new(table_name, "instance_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Instance {}
