// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::instance_state_type::InstanceState;
use super::instance_type::Instance;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `instance`.
///
/// Obtain a handle from the [`InstanceTableAccess::instance`] method on [`super::RemoteTables`],
/// like `ctx.db.instance()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.instance().on_insert(...)`.
pub struct InstanceTableHandle<'ctx> {
    imp: __sdk::TableHandle<Instance>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `instance`.
///
/// Implemented for [`super::RemoteTables`].
pub trait InstanceTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`InstanceTableHandle`], which mediates access to the table `instance`.
    fn instance(&self) -> InstanceTableHandle<'_>;
}

impl InstanceTableAccess for super::RemoteTables {
    fn instance(&self) -> InstanceTableHandle<'_> {
        InstanceTableHandle {
            imp: self.imp.get_table::<Instance>("instance"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct InstanceInsertCallbackId(__sdk::CallbackId);
pub struct InstanceDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for InstanceTableHandle<'ctx> {
    type Row = Instance;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Instance> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = InstanceInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> InstanceInsertCallbackId {
        InstanceInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: InstanceInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = InstanceDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> InstanceDeleteCallbackId {
        InstanceDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: InstanceDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct InstanceUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for InstanceTableHandle<'ctx> {
    type UpdateCallbackId = InstanceUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> InstanceUpdateCallbackId {
        InstanceUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: InstanceUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `instance_id` unique index on the table `instance`,
/// which allows point queries on the field of the same name
/// via the [`InstanceInstanceIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.instance().instance_id().find(...)`.
pub struct InstanceInstanceIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Instance, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> InstanceTableHandle<'ctx> {
    /// Get a handle on the `instance_id` unique index on the table `instance`.
    pub fn instance_id(&self) -> InstanceInstanceIdUnique<'ctx> {
        InstanceInstanceIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("instance_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> InstanceInstanceIdUnique<'ctx> {
    /// Find the subscribed row whose `instance_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<Instance> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Instance>("instance");
    _table.add_unique_constraint::<u64>("instance_id", |row| &row.instance_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<Instance>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Instance>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `Instance`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait instanceQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `Instance`.
    fn instance(&self) -> __sdk::__query_builder::Table<Instance>;
}

impl instanceQueryTableAccess for __sdk::QueryTableAccessor {
    fn instance(&self) -> __sdk::__query_builder::Table<Instance> {
        __sdk::__query_builder::Table::new("instance")
    }
}
