// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::interact_kind_type::InteractKind;
use super::interact_state_type::InteractState;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct InteractableConfig {
    pub entity_id: u64,
    pub interact_kind: InteractKind,
    pub linked_entity: Option<u64>,
    pub script_id: Option<String>,
    pub tags: Vec<String>,
    pub required_buff: Option<u32>,
    pub required_item: Option<u32>,
    pub interact_range: f32,
    pub puzzle_group: Option<String>,
    pub puzzle_required_count: u32,
    pub puzzle_window_ticks: u32,
    pub state: InteractState,
    pub body_shape: u8,
}

impl __sdk::InModule for InteractableConfig {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `InteractableConfig`.
///
/// Provides typed access to columns for query building.
pub struct InteractableConfigCols {
    pub entity_id: __sdk::__query_builder::Col<InteractableConfig, u64>,
    pub interact_kind: __sdk::__query_builder::Col<InteractableConfig, InteractKind>,
    pub linked_entity: __sdk::__query_builder::Col<InteractableConfig, Option<u64>>,
    pub script_id: __sdk::__query_builder::Col<InteractableConfig, Option<String>>,
    pub tags: __sdk::__query_builder::Col<InteractableConfig, Vec<String>>,
    pub required_buff: __sdk::__query_builder::Col<InteractableConfig, Option<u32>>,
    pub required_item: __sdk::__query_builder::Col<InteractableConfig, Option<u32>>,
    pub interact_range: __sdk::__query_builder::Col<InteractableConfig, f32>,
    pub puzzle_group: __sdk::__query_builder::Col<InteractableConfig, Option<String>>,
    pub puzzle_required_count: __sdk::__query_builder::Col<InteractableConfig, u32>,
    pub puzzle_window_ticks: __sdk::__query_builder::Col<InteractableConfig, u32>,
    pub state: __sdk::__query_builder::Col<InteractableConfig, InteractState>,
    pub body_shape: __sdk::__query_builder::Col<InteractableConfig, u8>,
}

impl __sdk::__query_builder::HasCols for InteractableConfig {
    type Cols = InteractableConfigCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        InteractableConfigCols {
            entity_id: __sdk::__query_builder::Col::new(table_name, "entity_id"),
            interact_kind: __sdk::__query_builder::Col::new(table_name, "interact_kind"),
            linked_entity: __sdk::__query_builder::Col::new(table_name, "linked_entity"),
            script_id: __sdk::__query_builder::Col::new(table_name, "script_id"),
            tags: __sdk::__query_builder::Col::new(table_name, "tags"),
            required_buff: __sdk::__query_builder::Col::new(table_name, "required_buff"),
            required_item: __sdk::__query_builder::Col::new(table_name, "required_item"),
            interact_range: __sdk::__query_builder::Col::new(table_name, "interact_range"),
            puzzle_group: __sdk::__query_builder::Col::new(table_name, "puzzle_group"),
            puzzle_required_count: __sdk::__query_builder::Col::new(
                table_name,
                "puzzle_required_count",
            ),
            puzzle_window_ticks: __sdk::__query_builder::Col::new(
                table_name,
                "puzzle_window_ticks",
            ),
            state: __sdk::__query_builder::Col::new(table_name, "state"),
            body_shape: __sdk::__query_builder::Col::new(table_name, "body_shape"),
        }
    }
}

/// Indexed column accessor struct for the table `InteractableConfig`.
///
/// Provides typed access to indexed columns for query building.
pub struct InteractableConfigIxCols {
    pub entity_id: __sdk::__query_builder::IxCol<InteractableConfig, u64>,
}

impl __sdk::__query_builder::HasIxCols for InteractableConfig {
    type IxCols = InteractableConfigIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        InteractableConfigIxCols {
            entity_id: __sdk::__query_builder::IxCol::new(table_name, "entity_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for InteractableConfig {}
