// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::interact_kind_type::InteractKind;
use super::interact_state_type::InteractState;
use super::interactable_config_type::InteractableConfig;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `interactable_config`.
///
/// Obtain a handle from the [`InteractableConfigTableAccess::interactable_config`] method on [`super::RemoteTables`],
/// like `ctx.db.interactable_config()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.interactable_config().on_insert(...)`.
pub struct InteractableConfigTableHandle<'ctx> {
    imp: __sdk::TableHandle<InteractableConfig>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `interactable_config`.
///
/// Implemented for [`super::RemoteTables`].
pub trait InteractableConfigTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`InteractableConfigTableHandle`], which mediates access to the table `interactable_config`.
    fn interactable_config(&self) -> InteractableConfigTableHandle<'_>;
}

impl InteractableConfigTableAccess for super::RemoteTables {
    fn interactable_config(&self) -> InteractableConfigTableHandle<'_> {
        InteractableConfigTableHandle {
            imp: self
                .imp
                .get_table::<InteractableConfig>("interactable_config"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct InteractableConfigInsertCallbackId(__sdk::CallbackId);
pub struct InteractableConfigDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for InteractableConfigTableHandle<'ctx> {
    type Row = InteractableConfig;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = InteractableConfig> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = InteractableConfigInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> InteractableConfigInsertCallbackId {
        InteractableConfigInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: InteractableConfigInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = InteractableConfigDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> InteractableConfigDeleteCallbackId {
        InteractableConfigDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: InteractableConfigDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct InteractableConfigUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for InteractableConfigTableHandle<'ctx> {
    type UpdateCallbackId = InteractableConfigUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> InteractableConfigUpdateCallbackId {
        InteractableConfigUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: InteractableConfigUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `entity_id` unique index on the table `interactable_config`,
/// which allows point queries on the field of the same name
/// via the [`InteractableConfigEntityIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.interactable_config().entity_id().find(...)`.
pub struct InteractableConfigEntityIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<InteractableConfig, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> InteractableConfigTableHandle<'ctx> {
    /// Get a handle on the `entity_id` unique index on the table `interactable_config`.
    pub fn entity_id(&self) -> InteractableConfigEntityIdUnique<'ctx> {
        InteractableConfigEntityIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("entity_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> InteractableConfigEntityIdUnique<'ctx> {
    /// Find the subscribed row whose `entity_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<InteractableConfig> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<InteractableConfig>("interactable_config");
    _table.add_unique_constraint::<u64>("entity_id", |row| &row.entity_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<InteractableConfig>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<InteractableConfig>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `InteractableConfig`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait interactable_configQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `InteractableConfig`.
    fn interactable_config(&self) -> __sdk::__query_builder::Table<InteractableConfig>;
}

impl interactable_configQueryTableAccess for __sdk::QueryTableAccessor {
    fn interactable_config(&self) -> __sdk::__query_builder::Table<InteractableConfig> {
        __sdk::__query_builder::Table::new("interactable_config")
    }
}
