// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::block_data_type::BlockData;
use super::move_dir_type::MoveDir;
use super::use_ability_data_type::UseAbilityData;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub enum IntentAction {
    Move(MoveDir),

    UseAbility(UseAbilityData),

    Stop,

    FaceTo(MoveDir),

    Interact(u64),

    Block(BlockData),

    ReleaseAbility(u32),

    Jump,

    WeaponSwap,

    TagTarget(u64),
}

impl __sdk::InModule for IntentAction {
    type Module = super::RemoteModule;
}
