// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct ModuleConfig {
    pub key: u32,
    pub admin: __sdk::Identity,
    pub last_committed_tick: u64,
    pub next_instance_layer: u32,
    pub next_tick_id: u64,
    pub global_max_rewind_ticks: u32,
}

impl __sdk::InModule for ModuleConfig {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `ModuleConfig`.
///
/// Provides typed access to columns for query building.
pub struct ModuleConfigCols {
    pub key: __sdk::__query_builder::Col<ModuleConfig, u32>,
    pub admin: __sdk::__query_builder::Col<ModuleConfig, __sdk::Identity>,
    pub last_committed_tick: __sdk::__query_builder::Col<ModuleConfig, u64>,
    pub next_instance_layer: __sdk::__query_builder::Col<ModuleConfig, u32>,
    pub next_tick_id: __sdk::__query_builder::Col<ModuleConfig, u64>,
    pub global_max_rewind_ticks: __sdk::__query_builder::Col<ModuleConfig, u32>,
}

impl __sdk::__query_builder::HasCols for ModuleConfig {
    type Cols = ModuleConfigCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        ModuleConfigCols {
            key: __sdk::__query_builder::Col::new(table_name, "key"),
            admin: __sdk::__query_builder::Col::new(table_name, "admin"),
            last_committed_tick: __sdk::__query_builder::Col::new(
                table_name,
                "last_committed_tick",
            ),
            next_instance_layer: __sdk::__query_builder::Col::new(
                table_name,
                "next_instance_layer",
            ),
            next_tick_id: __sdk::__query_builder::Col::new(table_name, "next_tick_id"),
            global_max_rewind_ticks: __sdk::__query_builder::Col::new(
                table_name,
                "global_max_rewind_ticks",
            ),
        }
    }
}

/// Indexed column accessor struct for the table `ModuleConfig`.
///
/// Provides typed access to indexed columns for query building.
pub struct ModuleConfigIxCols {
    pub key: __sdk::__query_builder::IxCol<ModuleConfig, u32>,
}

impl __sdk::__query_builder::HasIxCols for ModuleConfig {
    type IxCols = ModuleConfigIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        ModuleConfigIxCols {
            key: __sdk::__query_builder::IxCol::new(table_name, "key"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for ModuleConfig {}
