// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::region_info_type::RegionInfo;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `my_region`.
///
/// Obtain a handle from the [`MyRegionTableAccess::my_region`] method on [`super::RemoteTables`],
/// like `ctx.db.my_region()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.my_region().on_insert(...)`.
pub struct MyRegionTableHandle<'ctx> {
    imp: __sdk::TableHandle<RegionInfo>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `my_region`.
///
/// Implemented for [`super::RemoteTables`].
pub trait MyRegionTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`MyRegionTableHandle`], which mediates access to the table `my_region`.
    fn my_region(&self) -> MyRegionTableHandle<'_>;
}

impl MyRegionTableAccess for super::RemoteTables {
    fn my_region(&self) -> MyRegionTableHandle<'_> {
        MyRegionTableHandle {
            imp: self.imp.get_table::<RegionInfo>("my_region"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct MyRegionInsertCallbackId(__sdk::CallbackId);
pub struct MyRegionDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for MyRegionTableHandle<'ctx> {
    type Row = RegionInfo;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = RegionInfo> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = MyRegionInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyRegionInsertCallbackId {
        MyRegionInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MyRegionInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = MyRegionDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyRegionDeleteCallbackId {
        MyRegionDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MyRegionDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct MyRegionUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for MyRegionTableHandle<'ctx> {
    type UpdateCallbackId = MyRegionUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> MyRegionUpdateCallbackId {
        MyRegionUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: MyRegionUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `entity_id` unique index on the table `my_region`,
/// which allows point queries on the field of the same name
/// via the [`MyRegionEntityIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.my_region().entity_id().find(...)`.
pub struct MyRegionEntityIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<RegionInfo, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> MyRegionTableHandle<'ctx> {
    /// Get a handle on the `entity_id` unique index on the table `my_region`.
    pub fn entity_id(&self) -> MyRegionEntityIdUnique<'ctx> {
        MyRegionEntityIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("entity_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> MyRegionEntityIdUnique<'ctx> {
    /// Find the subscribed row whose `entity_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<RegionInfo> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<RegionInfo>("my_region");
    _table.add_unique_constraint::<u64>("entity_id", |row| &row.entity_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<RegionInfo>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<RegionInfo>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `RegionInfo`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait my_regionQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `RegionInfo`.
    fn my_region(&self) -> __sdk::__query_builder::Table<RegionInfo>;
}

impl my_regionQueryTableAccess for __sdk::QueryTableAccessor {
    fn my_region(&self) -> __sdk::__query_builder::Table<RegionInfo> {
        __sdk::__query_builder::Table::new("my_region")
    }
}
