// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::entity_kind_type::EntityKind;
use super::entity_state_type::EntityState;
use super::entity_type::Entity;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `nearby_entities`.
///
/// Obtain a handle from the [`NearbyEntitiesTableAccess::nearby_entities`] method on [`super::RemoteTables`],
/// like `ctx.db.nearby_entities()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.nearby_entities().on_insert(...)`.
pub struct NearbyEntitiesTableHandle<'ctx> {
    imp: __sdk::TableHandle<Entity>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `nearby_entities`.
///
/// Implemented for [`super::RemoteTables`].
pub trait NearbyEntitiesTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`NearbyEntitiesTableHandle`], which mediates access to the table `nearby_entities`.
    fn nearby_entities(&self) -> NearbyEntitiesTableHandle<'_>;
}

impl NearbyEntitiesTableAccess for super::RemoteTables {
    fn nearby_entities(&self) -> NearbyEntitiesTableHandle<'_> {
        NearbyEntitiesTableHandle {
            imp: self.imp.get_table::<Entity>("nearby_entities"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct NearbyEntitiesInsertCallbackId(__sdk::CallbackId);
pub struct NearbyEntitiesDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for NearbyEntitiesTableHandle<'ctx> {
    type Row = Entity;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Entity> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = NearbyEntitiesInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> NearbyEntitiesInsertCallbackId {
        NearbyEntitiesInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: NearbyEntitiesInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = NearbyEntitiesDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> NearbyEntitiesDeleteCallbackId {
        NearbyEntitiesDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: NearbyEntitiesDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Entity>("nearby_entities");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<Entity>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Entity>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `Entity`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait nearby_entitiesQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `Entity`.
    fn nearby_entities(&self) -> __sdk::__query_builder::Table<Entity>;
}

impl nearby_entitiesQueryTableAccess for __sdk::QueryTableAccessor {
    fn nearby_entities(&self) -> __sdk::__query_builder::Table<Entity> {
        __sdk::__query_builder::Table::new("nearby_entities")
    }
}
