// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::entity_health_type::EntityHealth;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `nearby_health`.
///
/// Obtain a handle from the [`NearbyHealthTableAccess::nearby_health`] method on [`super::RemoteTables`],
/// like `ctx.db.nearby_health()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.nearby_health().on_insert(...)`.
pub struct NearbyHealthTableHandle<'ctx> {
    imp: __sdk::TableHandle<EntityHealth>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `nearby_health`.
///
/// Implemented for [`super::RemoteTables`].
pub trait NearbyHealthTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`NearbyHealthTableHandle`], which mediates access to the table `nearby_health`.
    fn nearby_health(&self) -> NearbyHealthTableHandle<'_>;
}

impl NearbyHealthTableAccess for super::RemoteTables {
    fn nearby_health(&self) -> NearbyHealthTableHandle<'_> {
        NearbyHealthTableHandle {
            imp: self.imp.get_table::<EntityHealth>("nearby_health"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct NearbyHealthInsertCallbackId(__sdk::CallbackId);
pub struct NearbyHealthDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for NearbyHealthTableHandle<'ctx> {
    type Row = EntityHealth;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = EntityHealth> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = NearbyHealthInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> NearbyHealthInsertCallbackId {
        NearbyHealthInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: NearbyHealthInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = NearbyHealthDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> NearbyHealthDeleteCallbackId {
        NearbyHealthDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: NearbyHealthDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<EntityHealth>("nearby_health");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<EntityHealth>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<EntityHealth>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `EntityHealth`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait nearby_healthQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `EntityHealth`.
    fn nearby_health(&self) -> __sdk::__query_builder::Table<EntityHealth>;
}

impl nearby_healthQueryTableAccess for __sdk::QueryTableAccessor {
    fn nearby_health(&self) -> __sdk::__query_builder::Table<EntityHealth> {
        __sdk::__query_builder::Table::new("nearby_health")
    }
}
