// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::npc_config_type::NpcConfig;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `npc_config`.
///
/// Obtain a handle from the [`NpcConfigTableAccess::npc_config`] method on [`super::RemoteTables`],
/// like `ctx.db.npc_config()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.npc_config().on_insert(...)`.
pub struct NpcConfigTableHandle<'ctx> {
    imp: __sdk::TableHandle<NpcConfig>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `npc_config`.
///
/// Implemented for [`super::RemoteTables`].
pub trait NpcConfigTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`NpcConfigTableHandle`], which mediates access to the table `npc_config`.
    fn npc_config(&self) -> NpcConfigTableHandle<'_>;
}

impl NpcConfigTableAccess for super::RemoteTables {
    fn npc_config(&self) -> NpcConfigTableHandle<'_> {
        NpcConfigTableHandle {
            imp: self.imp.get_table::<NpcConfig>("npc_config"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct NpcConfigInsertCallbackId(__sdk::CallbackId);
pub struct NpcConfigDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for NpcConfigTableHandle<'ctx> {
    type Row = NpcConfig;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = NpcConfig> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = NpcConfigInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> NpcConfigInsertCallbackId {
        NpcConfigInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: NpcConfigInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = NpcConfigDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> NpcConfigDeleteCallbackId {
        NpcConfigDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: NpcConfigDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct NpcConfigUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for NpcConfigTableHandle<'ctx> {
    type UpdateCallbackId = NpcConfigUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> NpcConfigUpdateCallbackId {
        NpcConfigUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: NpcConfigUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `entity_id` unique index on the table `npc_config`,
/// which allows point queries on the field of the same name
/// via the [`NpcConfigEntityIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.npc_config().entity_id().find(...)`.
pub struct NpcConfigEntityIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<NpcConfig, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> NpcConfigTableHandle<'ctx> {
    /// Get a handle on the `entity_id` unique index on the table `npc_config`.
    pub fn entity_id(&self) -> NpcConfigEntityIdUnique<'ctx> {
        NpcConfigEntityIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("entity_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> NpcConfigEntityIdUnique<'ctx> {
    /// Find the subscribed row whose `entity_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<NpcConfig> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<NpcConfig>("npc_config");
    _table.add_unique_constraint::<u64>("entity_id", |row| &row.entity_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<NpcConfig>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<NpcConfig>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `NpcConfig`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait npc_configQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `NpcConfig`.
    fn npc_config(&self) -> __sdk::__query_builder::Table<NpcConfig>;
}

impl npc_configQueryTableAccess for __sdk::QueryTableAccessor {
    fn npc_config(&self) -> __sdk::__query_builder::Table<NpcConfig> {
        __sdk::__query_builder::Table::new("npc_config")
    }
}
