// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct NpcConfig {
    pub entity_id: u64,
    pub encounter_name: Option<String>,
    pub passive: bool,
    pub no_chase: bool,
    pub ability_id_1: Option<u32>,
    pub ability_id_2: Option<u32>,
    pub ability_id_3: Option<u32>,
    pub ability_id_4: Option<u32>,
    pub leash_radius: f32,
    pub aggro_radius: f32,
    pub body_shape: Option<u8>,
}

impl __sdk::InModule for NpcConfig {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `NpcConfig`.
///
/// Provides typed access to columns for query building.
pub struct NpcConfigCols {
    pub entity_id: __sdk::__query_builder::Col<NpcConfig, u64>,
    pub encounter_name: __sdk::__query_builder::Col<NpcConfig, Option<String>>,
    pub passive: __sdk::__query_builder::Col<NpcConfig, bool>,
    pub no_chase: __sdk::__query_builder::Col<NpcConfig, bool>,
    pub ability_id_1: __sdk::__query_builder::Col<NpcConfig, Option<u32>>,
    pub ability_id_2: __sdk::__query_builder::Col<NpcConfig, Option<u32>>,
    pub ability_id_3: __sdk::__query_builder::Col<NpcConfig, Option<u32>>,
    pub ability_id_4: __sdk::__query_builder::Col<NpcConfig, Option<u32>>,
    pub leash_radius: __sdk::__query_builder::Col<NpcConfig, f32>,
    pub aggro_radius: __sdk::__query_builder::Col<NpcConfig, f32>,
    pub body_shape: __sdk::__query_builder::Col<NpcConfig, Option<u8>>,
}

impl __sdk::__query_builder::HasCols for NpcConfig {
    type Cols = NpcConfigCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        NpcConfigCols {
            entity_id: __sdk::__query_builder::Col::new(table_name, "entity_id"),
            encounter_name: __sdk::__query_builder::Col::new(table_name, "encounter_name"),
            passive: __sdk::__query_builder::Col::new(table_name, "passive"),
            no_chase: __sdk::__query_builder::Col::new(table_name, "no_chase"),
            ability_id_1: __sdk::__query_builder::Col::new(table_name, "ability_id_1"),
            ability_id_2: __sdk::__query_builder::Col::new(table_name, "ability_id_2"),
            ability_id_3: __sdk::__query_builder::Col::new(table_name, "ability_id_3"),
            ability_id_4: __sdk::__query_builder::Col::new(table_name, "ability_id_4"),
            leash_radius: __sdk::__query_builder::Col::new(table_name, "leash_radius"),
            aggro_radius: __sdk::__query_builder::Col::new(table_name, "aggro_radius"),
            body_shape: __sdk::__query_builder::Col::new(table_name, "body_shape"),
        }
    }
}

/// Indexed column accessor struct for the table `NpcConfig`.
///
/// Provides typed access to indexed columns for query building.
pub struct NpcConfigIxCols {
    pub entity_id: __sdk::__query_builder::IxCol<NpcConfig, u64>,
}

impl __sdk::__query_builder::HasIxCols for NpcConfig {
    type IxCols = NpcConfigIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        NpcConfigIxCols {
            entity_id: __sdk::__query_builder::IxCol::new(table_name, "entity_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for NpcConfig {}
