// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::npc_goal_type::NpcGoal;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `npc_goal`.
///
/// Obtain a handle from the [`NpcGoalTableAccess::npc_goal`] method on [`super::RemoteTables`],
/// like `ctx.db.npc_goal()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.npc_goal().on_insert(...)`.
pub struct NpcGoalTableHandle<'ctx> {
    imp: __sdk::TableHandle<NpcGoal>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `npc_goal`.
///
/// Implemented for [`super::RemoteTables`].
pub trait NpcGoalTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`NpcGoalTableHandle`], which mediates access to the table `npc_goal`.
    fn npc_goal(&self) -> NpcGoalTableHandle<'_>;
}

impl NpcGoalTableAccess for super::RemoteTables {
    fn npc_goal(&self) -> NpcGoalTableHandle<'_> {
        NpcGoalTableHandle {
            imp: self.imp.get_table::<NpcGoal>("npc_goal"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct NpcGoalInsertCallbackId(__sdk::CallbackId);
pub struct NpcGoalDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for NpcGoalTableHandle<'ctx> {
    type Row = NpcGoal;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = NpcGoal> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = NpcGoalInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> NpcGoalInsertCallbackId {
        NpcGoalInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: NpcGoalInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = NpcGoalDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> NpcGoalDeleteCallbackId {
        NpcGoalDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: NpcGoalDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct NpcGoalUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for NpcGoalTableHandle<'ctx> {
    type UpdateCallbackId = NpcGoalUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> NpcGoalUpdateCallbackId {
        NpcGoalUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: NpcGoalUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `goal_id` unique index on the table `npc_goal`,
/// which allows point queries on the field of the same name
/// via the [`NpcGoalGoalIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.npc_goal().goal_id().find(...)`.
pub struct NpcGoalGoalIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<NpcGoal, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> NpcGoalTableHandle<'ctx> {
    /// Get a handle on the `goal_id` unique index on the table `npc_goal`.
    pub fn goal_id(&self) -> NpcGoalGoalIdUnique<'ctx> {
        NpcGoalGoalIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("goal_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> NpcGoalGoalIdUnique<'ctx> {
    /// Find the subscribed row whose `goal_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<NpcGoal> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<NpcGoal>("npc_goal");
    _table.add_unique_constraint::<u64>("goal_id", |row| &row.goal_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<NpcGoal>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<NpcGoal>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `NpcGoal`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait npc_goalQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `NpcGoal`.
    fn npc_goal(&self) -> __sdk::__query_builder::Table<NpcGoal>;
}

impl npc_goalQueryTableAccess for __sdk::QueryTableAccessor {
    fn npc_goal(&self) -> __sdk::__query_builder::Table<NpcGoal> {
        __sdk::__query_builder::Table::new("npc_goal")
    }
}
