// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct NpcGoal {
    pub goal_id: u64,
    pub entity_id: u64,
    pub goal_kind: String,
    pub waypoints: String,
    pub priority: u32,
}

impl __sdk::InModule for NpcGoal {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `NpcGoal`.
///
/// Provides typed access to columns for query building.
pub struct NpcGoalCols {
    pub goal_id: __sdk::__query_builder::Col<NpcGoal, u64>,
    pub entity_id: __sdk::__query_builder::Col<NpcGoal, u64>,
    pub goal_kind: __sdk::__query_builder::Col<NpcGoal, String>,
    pub waypoints: __sdk::__query_builder::Col<NpcGoal, String>,
    pub priority: __sdk::__query_builder::Col<NpcGoal, u32>,
}

impl __sdk::__query_builder::HasCols for NpcGoal {
    type Cols = NpcGoalCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        NpcGoalCols {
            goal_id: __sdk::__query_builder::Col::new(table_name, "goal_id"),
            entity_id: __sdk::__query_builder::Col::new(table_name, "entity_id"),
            goal_kind: __sdk::__query_builder::Col::new(table_name, "goal_kind"),
            waypoints: __sdk::__query_builder::Col::new(table_name, "waypoints"),
            priority: __sdk::__query_builder::Col::new(table_name, "priority"),
        }
    }
}

/// Indexed column accessor struct for the table `NpcGoal`.
///
/// Provides typed access to indexed columns for query building.
pub struct NpcGoalIxCols {
    pub entity_id: __sdk::__query_builder::IxCol<NpcGoal, u64>,
    pub goal_id: __sdk::__query_builder::IxCol<NpcGoal, u64>,
}

impl __sdk::__query_builder::HasIxCols for NpcGoal {
    type IxCols = NpcGoalIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        NpcGoalIxCols {
            entity_id: __sdk::__query_builder::IxCol::new(table_name, "entity_id"),
            goal_id: __sdk::__query_builder::IxCol::new(table_name, "goal_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for NpcGoal {}
