// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::npc_ai_state_type::NpcAiState;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct NpcState {
    pub entity_id: u64,
    pub ai_state: NpcAiState,
    pub target_entity: Option<u64>,
}

impl __sdk::InModule for NpcState {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `NpcState`.
///
/// Provides typed access to columns for query building.
pub struct NpcStateCols {
    pub entity_id: __sdk::__query_builder::Col<NpcState, u64>,
    pub ai_state: __sdk::__query_builder::Col<NpcState, NpcAiState>,
    pub target_entity: __sdk::__query_builder::Col<NpcState, Option<u64>>,
}

impl __sdk::__query_builder::HasCols for NpcState {
    type Cols = NpcStateCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        NpcStateCols {
            entity_id: __sdk::__query_builder::Col::new(table_name, "entity_id"),
            ai_state: __sdk::__query_builder::Col::new(table_name, "ai_state"),
            target_entity: __sdk::__query_builder::Col::new(table_name, "target_entity"),
        }
    }
}

/// Indexed column accessor struct for the table `NpcState`.
///
/// Provides typed access to indexed columns for query building.
pub struct NpcStateIxCols {
    pub entity_id: __sdk::__query_builder::IxCol<NpcState, u64>,
}

impl __sdk::__query_builder::HasIxCols for NpcState {
    type IxCols = NpcStateIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        NpcStateIxCols {
            entity_id: __sdk::__query_builder::IxCol::new(table_name, "entity_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for NpcState {}
