// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Party {
    pub party_id: u64,
    pub leader_entity: u64,
    pub max_members: u32,
    pub created_at: i64,
}

impl __sdk::InModule for Party {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Party`.
///
/// Provides typed access to columns for query building.
pub struct PartyCols {
    pub party_id: __sdk::__query_builder::Col<Party, u64>,
    pub leader_entity: __sdk::__query_builder::Col<Party, u64>,
    pub max_members: __sdk::__query_builder::Col<Party, u32>,
    pub created_at: __sdk::__query_builder::Col<Party, i64>,
}

impl __sdk::__query_builder::HasCols for Party {
    type Cols = PartyCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        PartyCols {
            party_id: __sdk::__query_builder::Col::new(table_name, "party_id"),
            leader_entity: __sdk::__query_builder::Col::new(table_name, "leader_entity"),
            max_members: __sdk::__query_builder::Col::new(table_name, "max_members"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
        }
    }
}

/// Indexed column accessor struct for the table `Party`.
///
/// Provides typed access to indexed columns for query building.
pub struct PartyIxCols {
    pub party_id: __sdk::__query_builder::IxCol<Party, u64>,
}

impl __sdk::__query_builder::HasIxCols for Party {
    type IxCols = PartyIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        PartyIxCols {
            party_id: __sdk::__query_builder::IxCol::new(table_name, "party_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Party {}
