// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::party_invite_type::PartyInvite;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `party_invite`.
///
/// Obtain a handle from the [`PartyInviteTableAccess::party_invite`] method on [`super::RemoteTables`],
/// like `ctx.db.party_invite()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.party_invite().on_insert(...)`.
pub struct PartyInviteTableHandle<'ctx> {
    imp: __sdk::TableHandle<PartyInvite>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `party_invite`.
///
/// Implemented for [`super::RemoteTables`].
pub trait PartyInviteTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`PartyInviteTableHandle`], which mediates access to the table `party_invite`.
    fn party_invite(&self) -> PartyInviteTableHandle<'_>;
}

impl PartyInviteTableAccess for super::RemoteTables {
    fn party_invite(&self) -> PartyInviteTableHandle<'_> {
        PartyInviteTableHandle {
            imp: self.imp.get_table::<PartyInvite>("party_invite"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct PartyInviteInsertCallbackId(__sdk::CallbackId);
pub struct PartyInviteDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for PartyInviteTableHandle<'ctx> {
    type Row = PartyInvite;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = PartyInvite> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = PartyInviteInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PartyInviteInsertCallbackId {
        PartyInviteInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: PartyInviteInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = PartyInviteDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PartyInviteDeleteCallbackId {
        PartyInviteDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: PartyInviteDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct PartyInviteUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for PartyInviteTableHandle<'ctx> {
    type UpdateCallbackId = PartyInviteUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> PartyInviteUpdateCallbackId {
        PartyInviteUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: PartyInviteUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `invite_id` unique index on the table `party_invite`,
/// which allows point queries on the field of the same name
/// via the [`PartyInviteInviteIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.party_invite().invite_id().find(...)`.
pub struct PartyInviteInviteIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<PartyInvite, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> PartyInviteTableHandle<'ctx> {
    /// Get a handle on the `invite_id` unique index on the table `party_invite`.
    pub fn invite_id(&self) -> PartyInviteInviteIdUnique<'ctx> {
        PartyInviteInviteIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("invite_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> PartyInviteInviteIdUnique<'ctx> {
    /// Find the subscribed row whose `invite_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<PartyInvite> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<PartyInvite>("party_invite");
    _table.add_unique_constraint::<u64>("invite_id", |row| &row.invite_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<PartyInvite>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<PartyInvite>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `PartyInvite`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait party_inviteQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `PartyInvite`.
    fn party_invite(&self) -> __sdk::__query_builder::Table<PartyInvite>;
}

impl party_inviteQueryTableAccess for __sdk::QueryTableAccessor {
    fn party_invite(&self) -> __sdk::__query_builder::Table<PartyInvite> {
        __sdk::__query_builder::Table::new("party_invite")
    }
}
