// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::intent_action_type::IntentAction;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct PlayerIntent {
    pub intent_id: u64,
    pub client_identity: __sdk::Identity,
    pub entity_id: u64,
    pub sequence_id: u64,
    pub target_tick: u64,
    pub client_observed_tick: u64,
    pub action: IntentAction,
}

impl __sdk::InModule for PlayerIntent {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `PlayerIntent`.
///
/// Provides typed access to columns for query building.
pub struct PlayerIntentCols {
    pub intent_id: __sdk::__query_builder::Col<PlayerIntent, u64>,
    pub client_identity: __sdk::__query_builder::Col<PlayerIntent, __sdk::Identity>,
    pub entity_id: __sdk::__query_builder::Col<PlayerIntent, u64>,
    pub sequence_id: __sdk::__query_builder::Col<PlayerIntent, u64>,
    pub target_tick: __sdk::__query_builder::Col<PlayerIntent, u64>,
    pub client_observed_tick: __sdk::__query_builder::Col<PlayerIntent, u64>,
    pub action: __sdk::__query_builder::Col<PlayerIntent, IntentAction>,
}

impl __sdk::__query_builder::HasCols for PlayerIntent {
    type Cols = PlayerIntentCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        PlayerIntentCols {
            intent_id: __sdk::__query_builder::Col::new(table_name, "intent_id"),
            client_identity: __sdk::__query_builder::Col::new(table_name, "client_identity"),
            entity_id: __sdk::__query_builder::Col::new(table_name, "entity_id"),
            sequence_id: __sdk::__query_builder::Col::new(table_name, "sequence_id"),
            target_tick: __sdk::__query_builder::Col::new(table_name, "target_tick"),
            client_observed_tick: __sdk::__query_builder::Col::new(
                table_name,
                "client_observed_tick",
            ),
            action: __sdk::__query_builder::Col::new(table_name, "action"),
        }
    }
}

/// Indexed column accessor struct for the table `PlayerIntent`.
///
/// Provides typed access to indexed columns for query building.
pub struct PlayerIntentIxCols {
    pub entity_id: __sdk::__query_builder::IxCol<PlayerIntent, u64>,
    pub intent_id: __sdk::__query_builder::IxCol<PlayerIntent, u64>,
    pub target_tick: __sdk::__query_builder::IxCol<PlayerIntent, u64>,
}

impl __sdk::__query_builder::HasIxCols for PlayerIntent {
    type IxCols = PlayerIntentIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        PlayerIntentIxCols {
            entity_id: __sdk::__query_builder::IxCol::new(table_name, "entity_id"),
            intent_id: __sdk::__query_builder::IxCol::new(table_name, "intent_id"),
            target_tick: __sdk::__query_builder::IxCol::new(table_name, "target_tick"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for PlayerIntent {}
