// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::equipment_slot_type::EquipmentSlot;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct PlayerEquipment {
    pub row_id: u64,
    pub owner_entity: u64,
    pub slot: EquipmentSlot,
    pub item_id: u32,
}

impl __sdk::InModule for PlayerEquipment {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `PlayerEquipment`.
///
/// Provides typed access to columns for query building.
pub struct PlayerEquipmentCols {
    pub row_id: __sdk::__query_builder::Col<PlayerEquipment, u64>,
    pub owner_entity: __sdk::__query_builder::Col<PlayerEquipment, u64>,
    pub slot: __sdk::__query_builder::Col<PlayerEquipment, EquipmentSlot>,
    pub item_id: __sdk::__query_builder::Col<PlayerEquipment, u32>,
}

impl __sdk::__query_builder::HasCols for PlayerEquipment {
    type Cols = PlayerEquipmentCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        PlayerEquipmentCols {
            row_id: __sdk::__query_builder::Col::new(table_name, "row_id"),
            owner_entity: __sdk::__query_builder::Col::new(table_name, "owner_entity"),
            slot: __sdk::__query_builder::Col::new(table_name, "slot"),
            item_id: __sdk::__query_builder::Col::new(table_name, "item_id"),
        }
    }
}

/// Indexed column accessor struct for the table `PlayerEquipment`.
///
/// Provides typed access to indexed columns for query building.
pub struct PlayerEquipmentIxCols {
    pub owner_entity: __sdk::__query_builder::IxCol<PlayerEquipment, u64>,
    pub row_id: __sdk::__query_builder::IxCol<PlayerEquipment, u64>,
}

impl __sdk::__query_builder::HasIxCols for PlayerEquipment {
    type IxCols = PlayerEquipmentIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        PlayerEquipmentIxCols {
            owner_entity: __sdk::__query_builder::IxCol::new(table_name, "owner_entity"),
            row_id: __sdk::__query_builder::IxCol::new(table_name, "row_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for PlayerEquipment {}
