// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct RegionInfo {
    pub entity_id: u64,
    pub region_x: i32,
    pub region_z: i32,
    pub layer: u32,
}

impl __sdk::InModule for RegionInfo {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `RegionInfo`.
///
/// Provides typed access to columns for query building.
pub struct RegionInfoCols {
    pub entity_id: __sdk::__query_builder::Col<RegionInfo, u64>,
    pub region_x: __sdk::__query_builder::Col<RegionInfo, i32>,
    pub region_z: __sdk::__query_builder::Col<RegionInfo, i32>,
    pub layer: __sdk::__query_builder::Col<RegionInfo, u32>,
}

impl __sdk::__query_builder::HasCols for RegionInfo {
    type Cols = RegionInfoCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        RegionInfoCols {
            entity_id: __sdk::__query_builder::Col::new(table_name, "entity_id"),
            region_x: __sdk::__query_builder::Col::new(table_name, "region_x"),
            region_z: __sdk::__query_builder::Col::new(table_name, "region_z"),
            layer: __sdk::__query_builder::Col::new(table_name, "layer"),
        }
    }
}
