// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct RegisterWorkerArgs {
    pub worker_identity: __sdk::Identity,
}

impl From<RegisterWorkerArgs> for super::Reducer {
    fn from(args: RegisterWorkerArgs) -> Self {
        Self::RegisterWorker {
            worker_identity: args.worker_identity,
        }
    }
}

impl __sdk::InModule for RegisterWorkerArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `register_worker`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait register_worker {
    /// Request that the remote module invoke the reducer `register_worker` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`register_worker:register_worker_then`] to run a callback after the reducer completes.
    fn register_worker(&self, worker_identity: __sdk::Identity) -> __sdk::Result<()> {
        self.register_worker_then(worker_identity, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `register_worker` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn register_worker_then(
        &self,
        worker_identity: __sdk::Identity,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl register_worker for super::RemoteReducers {
    fn register_worker_then(
        &self,
        worker_identity: __sdk::Identity,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(RegisterWorkerArgs { worker_identity }, callback)
    }
}
