// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::batched_intent_type::BatchedIntent;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SubmitIntentsBatchArgs {
    pub entity_id: u64,
    pub intents: Vec<BatchedIntent>,
}

impl From<SubmitIntentsBatchArgs> for super::Reducer {
    fn from(args: SubmitIntentsBatchArgs) -> Self {
        Self::SubmitIntentsBatch {
            entity_id: args.entity_id,
            intents: args.intents,
        }
    }
}

impl __sdk::InModule for SubmitIntentsBatchArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `submit_intents_batch`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait submit_intents_batch {
    /// Request that the remote module invoke the reducer `submit_intents_batch` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`submit_intents_batch:submit_intents_batch_then`] to run a callback after the reducer completes.
    fn submit_intents_batch(
        &self,
        entity_id: u64,
        intents: Vec<BatchedIntent>,
    ) -> __sdk::Result<()> {
        self.submit_intents_batch_then(entity_id, intents, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `submit_intents_batch` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn submit_intents_batch_then(
        &self,
        entity_id: u64,
        intents: Vec<BatchedIntent>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl submit_intents_batch for super::RemoteReducers {
    fn submit_intents_batch_then(
        &self,
        entity_id: u64,
        intents: Vec<BatchedIntent>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(SubmitIntentsBatchArgs { entity_id, intents }, callback)
    }
}
