// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::intent_action_type::IntentAction;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SubmitIntentArgs {
    pub entity_id: u64,
    pub sequence_id: u64,
    pub action: IntentAction,
    pub client_observed_tick: u64,
}

impl From<SubmitIntentArgs> for super::Reducer {
    fn from(args: SubmitIntentArgs) -> Self {
        Self::SubmitIntent {
            entity_id: args.entity_id,
            sequence_id: args.sequence_id,
            action: args.action,
            client_observed_tick: args.client_observed_tick,
        }
    }
}

impl __sdk::InModule for SubmitIntentArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `submit_intent`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait submit_intent {
    /// Request that the remote module invoke the reducer `submit_intent` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`submit_intent:submit_intent_then`] to run a callback after the reducer completes.
    fn submit_intent(
        &self,
        entity_id: u64,
        sequence_id: u64,
        action: IntentAction,
        client_observed_tick: u64,
    ) -> __sdk::Result<()> {
        self.submit_intent_then(
            entity_id,
            sequence_id,
            action,
            client_observed_tick,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `submit_intent` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn submit_intent_then(
        &self,
        entity_id: u64,
        sequence_id: u64,
        action: IntentAction,
        client_observed_tick: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl submit_intent for super::RemoteReducers {
    fn submit_intent_then(
        &self,
        entity_id: u64,
        sequence_id: u64,
        action: IntentAction,
        client_observed_tick: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            SubmitIntentArgs {
                entity_id,
                sequence_id,
                action,
                client_observed_tick,
            },
            callback,
        )
    }
}
