// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct TerrainChunkUpsertArgs {
    pub terrain_set_id: u32,
    pub chunk_morton: u64,
    pub vertices: Vec<f32>,
    pub indices: Vec<u32>,
    pub lod: u8,
}

impl From<TerrainChunkUpsertArgs> for super::Reducer {
    fn from(args: TerrainChunkUpsertArgs) -> Self {
        Self::TerrainChunkUpsert {
            terrain_set_id: args.terrain_set_id,
            chunk_morton: args.chunk_morton,
            vertices: args.vertices,
            indices: args.indices,
            lod: args.lod,
        }
    }
}

impl __sdk::InModule for TerrainChunkUpsertArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `terrain_chunk_upsert`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait terrain_chunk_upsert {
    /// Request that the remote module invoke the reducer `terrain_chunk_upsert` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`terrain_chunk_upsert:terrain_chunk_upsert_then`] to run a callback after the reducer completes.
    fn terrain_chunk_upsert(
        &self,
        terrain_set_id: u32,
        chunk_morton: u64,
        vertices: Vec<f32>,
        indices: Vec<u32>,
        lod: u8,
    ) -> __sdk::Result<()> {
        self.terrain_chunk_upsert_then(
            terrain_set_id,
            chunk_morton,
            vertices,
            indices,
            lod,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `terrain_chunk_upsert` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn terrain_chunk_upsert_then(
        &self,
        terrain_set_id: u32,
        chunk_morton: u64,
        vertices: Vec<f32>,
        indices: Vec<u32>,
        lod: u8,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl terrain_chunk_upsert for super::RemoteReducers {
    fn terrain_chunk_upsert_then(
        &self,
        terrain_set_id: u32,
        chunk_morton: u64,
        vertices: Vec<f32>,
        indices: Vec<u32>,
        lod: u8,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            TerrainChunkUpsertArgs {
                terrain_set_id,
                chunk_morton,
                vertices,
                indices,
                lod,
            },
            callback,
        )
    }
}
