// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::terrain_core_type::TerrainCore;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `terrain_core`.
///
/// Obtain a handle from the [`TerrainCoreTableAccess::terrain_core`] method on [`super::RemoteTables`],
/// like `ctx.db.terrain_core()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.terrain_core().on_insert(...)`.
pub struct TerrainCoreTableHandle<'ctx> {
    imp: __sdk::TableHandle<TerrainCore>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `terrain_core`.
///
/// Implemented for [`super::RemoteTables`].
pub trait TerrainCoreTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`TerrainCoreTableHandle`], which mediates access to the table `terrain_core`.
    fn terrain_core(&self) -> TerrainCoreTableHandle<'_>;
}

impl TerrainCoreTableAccess for super::RemoteTables {
    fn terrain_core(&self) -> TerrainCoreTableHandle<'_> {
        TerrainCoreTableHandle {
            imp: self.imp.get_table::<TerrainCore>("terrain_core"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct TerrainCoreInsertCallbackId(__sdk::CallbackId);
pub struct TerrainCoreDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for TerrainCoreTableHandle<'ctx> {
    type Row = TerrainCore;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = TerrainCore> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = TerrainCoreInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TerrainCoreInsertCallbackId {
        TerrainCoreInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: TerrainCoreInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = TerrainCoreDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TerrainCoreDeleteCallbackId {
        TerrainCoreDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: TerrainCoreDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct TerrainCoreUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for TerrainCoreTableHandle<'ctx> {
    type UpdateCallbackId = TerrainCoreUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> TerrainCoreUpdateCallbackId {
        TerrainCoreUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: TerrainCoreUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `row_id` unique index on the table `terrain_core`,
/// which allows point queries on the field of the same name
/// via the [`TerrainCoreRowIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.terrain_core().row_id().find(...)`.
pub struct TerrainCoreRowIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<TerrainCore, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> TerrainCoreTableHandle<'ctx> {
    /// Get a handle on the `row_id` unique index on the table `terrain_core`.
    pub fn row_id(&self) -> TerrainCoreRowIdUnique<'ctx> {
        TerrainCoreRowIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("row_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> TerrainCoreRowIdUnique<'ctx> {
    /// Find the subscribed row whose `row_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<TerrainCore> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<TerrainCore>("terrain_core");
    _table.add_unique_constraint::<u64>("row_id", |row| &row.row_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<TerrainCore>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<TerrainCore>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `TerrainCore`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait terrain_coreQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `TerrainCore`.
    fn terrain_core(&self) -> __sdk::__query_builder::Table<TerrainCore>;
}

impl terrain_coreQueryTableAccess for __sdk::QueryTableAccessor {
    fn terrain_core(&self) -> __sdk::__query_builder::Table<TerrainCore> {
        __sdk::__query_builder::Table::new("terrain_core")
    }
}
