// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct TerrainManifestUpsertArgs {
    pub terrain_set_id: u32,
    pub chunk_morton: u64,
    pub content_hash: String,
    pub version: u32,
}

impl From<TerrainManifestUpsertArgs> for super::Reducer {
    fn from(args: TerrainManifestUpsertArgs) -> Self {
        Self::TerrainManifestUpsert {
            terrain_set_id: args.terrain_set_id,
            chunk_morton: args.chunk_morton,
            content_hash: args.content_hash,
            version: args.version,
        }
    }
}

impl __sdk::InModule for TerrainManifestUpsertArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `terrain_manifest_upsert`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait terrain_manifest_upsert {
    /// Request that the remote module invoke the reducer `terrain_manifest_upsert` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`terrain_manifest_upsert:terrain_manifest_upsert_then`] to run a callback after the reducer completes.
    fn terrain_manifest_upsert(
        &self,
        terrain_set_id: u32,
        chunk_morton: u64,
        content_hash: String,
        version: u32,
    ) -> __sdk::Result<()> {
        self.terrain_manifest_upsert_then(
            terrain_set_id,
            chunk_morton,
            content_hash,
            version,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `terrain_manifest_upsert` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn terrain_manifest_upsert_then(
        &self,
        terrain_set_id: u32,
        chunk_morton: u64,
        content_hash: String,
        version: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl terrain_manifest_upsert for super::RemoteReducers {
    fn terrain_manifest_upsert_then(
        &self,
        terrain_set_id: u32,
        chunk_morton: u64,
        content_hash: String,
        version: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            TerrainManifestUpsertArgs {
                terrain_set_id,
                chunk_morton,
                content_hash,
                version,
            },
            callback,
        )
    }
}
