// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::terrain_manifest_type::TerrainManifest;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `terrain_manifest`.
///
/// Obtain a handle from the [`TerrainManifestTableAccess::terrain_manifest`] method on [`super::RemoteTables`],
/// like `ctx.db.terrain_manifest()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.terrain_manifest().on_insert(...)`.
pub struct TerrainManifestTableHandle<'ctx> {
    imp: __sdk::TableHandle<TerrainManifest>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `terrain_manifest`.
///
/// Implemented for [`super::RemoteTables`].
pub trait TerrainManifestTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`TerrainManifestTableHandle`], which mediates access to the table `terrain_manifest`.
    fn terrain_manifest(&self) -> TerrainManifestTableHandle<'_>;
}

impl TerrainManifestTableAccess for super::RemoteTables {
    fn terrain_manifest(&self) -> TerrainManifestTableHandle<'_> {
        TerrainManifestTableHandle {
            imp: self.imp.get_table::<TerrainManifest>("terrain_manifest"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct TerrainManifestInsertCallbackId(__sdk::CallbackId);
pub struct TerrainManifestDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for TerrainManifestTableHandle<'ctx> {
    type Row = TerrainManifest;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = TerrainManifest> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = TerrainManifestInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TerrainManifestInsertCallbackId {
        TerrainManifestInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: TerrainManifestInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = TerrainManifestDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TerrainManifestDeleteCallbackId {
        TerrainManifestDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: TerrainManifestDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct TerrainManifestUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for TerrainManifestTableHandle<'ctx> {
    type UpdateCallbackId = TerrainManifestUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> TerrainManifestUpdateCallbackId {
        TerrainManifestUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: TerrainManifestUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `row_id` unique index on the table `terrain_manifest`,
/// which allows point queries on the field of the same name
/// via the [`TerrainManifestRowIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.terrain_manifest().row_id().find(...)`.
pub struct TerrainManifestRowIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<TerrainManifest, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> TerrainManifestTableHandle<'ctx> {
    /// Get a handle on the `row_id` unique index on the table `terrain_manifest`.
    pub fn row_id(&self) -> TerrainManifestRowIdUnique<'ctx> {
        TerrainManifestRowIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("row_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> TerrainManifestRowIdUnique<'ctx> {
    /// Find the subscribed row whose `row_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<TerrainManifest> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<TerrainManifest>("terrain_manifest");
    _table.add_unique_constraint::<u64>("row_id", |row| &row.row_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<TerrainManifest>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<TerrainManifest>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `TerrainManifest`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait terrain_manifestQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `TerrainManifest`.
    fn terrain_manifest(&self) -> __sdk::__query_builder::Table<TerrainManifest>;
}

impl terrain_manifestQueryTableAccess for __sdk::QueryTableAccessor {
    fn terrain_manifest(&self) -> __sdk::__query_builder::Table<TerrainManifest> {
        __sdk::__query_builder::Table::new("terrain_manifest")
    }
}
