// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct TerrainChunk {
    pub row_id: u64,
    pub terrain_set_id: u32,
    pub chunk_morton: u64,
    pub vertices: Vec<f32>,
    pub indices: Vec<u32>,
    pub lod: u8,
}

impl __sdk::InModule for TerrainChunk {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `TerrainChunk`.
///
/// Provides typed access to columns for query building.
pub struct TerrainChunkCols {
    pub row_id: __sdk::__query_builder::Col<TerrainChunk, u64>,
    pub terrain_set_id: __sdk::__query_builder::Col<TerrainChunk, u32>,
    pub chunk_morton: __sdk::__query_builder::Col<TerrainChunk, u64>,
    pub vertices: __sdk::__query_builder::Col<TerrainChunk, Vec<f32>>,
    pub indices: __sdk::__query_builder::Col<TerrainChunk, Vec<u32>>,
    pub lod: __sdk::__query_builder::Col<TerrainChunk, u8>,
}

impl __sdk::__query_builder::HasCols for TerrainChunk {
    type Cols = TerrainChunkCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        TerrainChunkCols {
            row_id: __sdk::__query_builder::Col::new(table_name, "row_id"),
            terrain_set_id: __sdk::__query_builder::Col::new(table_name, "terrain_set_id"),
            chunk_morton: __sdk::__query_builder::Col::new(table_name, "chunk_morton"),
            vertices: __sdk::__query_builder::Col::new(table_name, "vertices"),
            indices: __sdk::__query_builder::Col::new(table_name, "indices"),
            lod: __sdk::__query_builder::Col::new(table_name, "lod"),
        }
    }
}

/// Indexed column accessor struct for the table `TerrainChunk`.
///
/// Provides typed access to indexed columns for query building.
pub struct TerrainChunkIxCols {
    pub row_id: __sdk::__query_builder::IxCol<TerrainChunk, u64>,
}

impl __sdk::__query_builder::HasIxCols for TerrainChunk {
    type IxCols = TerrainChunkIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        TerrainChunkIxCols {
            row_id: __sdk::__query_builder::IxCol::new(table_name, "row_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for TerrainChunk {}
