// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct TerrainCore {
    pub row_id: u64,
    pub terrain_set_id: u32,
    pub chunk_morton: u64,
    pub voxel_idx: u32,
    pub hermite_normal_x: f32,
    pub hermite_normal_y: f32,
    pub hermite_normal_z: f32,
    pub qef_offset_x: f32,
    pub qef_offset_y: f32,
    pub qef_offset_z: f32,
    pub material_id: u16,
    pub flags: u32,
}

impl __sdk::InModule for TerrainCore {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `TerrainCore`.
///
/// Provides typed access to columns for query building.
pub struct TerrainCoreCols {
    pub row_id: __sdk::__query_builder::Col<TerrainCore, u64>,
    pub terrain_set_id: __sdk::__query_builder::Col<TerrainCore, u32>,
    pub chunk_morton: __sdk::__query_builder::Col<TerrainCore, u64>,
    pub voxel_idx: __sdk::__query_builder::Col<TerrainCore, u32>,
    pub hermite_normal_x: __sdk::__query_builder::Col<TerrainCore, f32>,
    pub hermite_normal_y: __sdk::__query_builder::Col<TerrainCore, f32>,
    pub hermite_normal_z: __sdk::__query_builder::Col<TerrainCore, f32>,
    pub qef_offset_x: __sdk::__query_builder::Col<TerrainCore, f32>,
    pub qef_offset_y: __sdk::__query_builder::Col<TerrainCore, f32>,
    pub qef_offset_z: __sdk::__query_builder::Col<TerrainCore, f32>,
    pub material_id: __sdk::__query_builder::Col<TerrainCore, u16>,
    pub flags: __sdk::__query_builder::Col<TerrainCore, u32>,
}

impl __sdk::__query_builder::HasCols for TerrainCore {
    type Cols = TerrainCoreCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        TerrainCoreCols {
            row_id: __sdk::__query_builder::Col::new(table_name, "row_id"),
            terrain_set_id: __sdk::__query_builder::Col::new(table_name, "terrain_set_id"),
            chunk_morton: __sdk::__query_builder::Col::new(table_name, "chunk_morton"),
            voxel_idx: __sdk::__query_builder::Col::new(table_name, "voxel_idx"),
            hermite_normal_x: __sdk::__query_builder::Col::new(table_name, "hermite_normal_x"),
            hermite_normal_y: __sdk::__query_builder::Col::new(table_name, "hermite_normal_y"),
            hermite_normal_z: __sdk::__query_builder::Col::new(table_name, "hermite_normal_z"),
            qef_offset_x: __sdk::__query_builder::Col::new(table_name, "qef_offset_x"),
            qef_offset_y: __sdk::__query_builder::Col::new(table_name, "qef_offset_y"),
            qef_offset_z: __sdk::__query_builder::Col::new(table_name, "qef_offset_z"),
            material_id: __sdk::__query_builder::Col::new(table_name, "material_id"),
            flags: __sdk::__query_builder::Col::new(table_name, "flags"),
        }
    }
}

/// Indexed column accessor struct for the table `TerrainCore`.
///
/// Provides typed access to indexed columns for query building.
pub struct TerrainCoreIxCols {
    pub row_id: __sdk::__query_builder::IxCol<TerrainCore, u64>,
}

impl __sdk::__query_builder::HasIxCols for TerrainCore {
    type IxCols = TerrainCoreIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        TerrainCoreIxCols {
            row_id: __sdk::__query_builder::IxCol::new(table_name, "row_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for TerrainCore {}
