// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::terrain_set_type::TerrainSet;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `terrain_set`.
///
/// Obtain a handle from the [`TerrainSetTableAccess::terrain_set`] method on [`super::RemoteTables`],
/// like `ctx.db.terrain_set()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.terrain_set().on_insert(...)`.
pub struct TerrainSetTableHandle<'ctx> {
    imp: __sdk::TableHandle<TerrainSet>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `terrain_set`.
///
/// Implemented for [`super::RemoteTables`].
pub trait TerrainSetTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`TerrainSetTableHandle`], which mediates access to the table `terrain_set`.
    fn terrain_set(&self) -> TerrainSetTableHandle<'_>;
}

impl TerrainSetTableAccess for super::RemoteTables {
    fn terrain_set(&self) -> TerrainSetTableHandle<'_> {
        TerrainSetTableHandle {
            imp: self.imp.get_table::<TerrainSet>("terrain_set"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct TerrainSetInsertCallbackId(__sdk::CallbackId);
pub struct TerrainSetDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for TerrainSetTableHandle<'ctx> {
    type Row = TerrainSet;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = TerrainSet> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = TerrainSetInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TerrainSetInsertCallbackId {
        TerrainSetInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: TerrainSetInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = TerrainSetDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TerrainSetDeleteCallbackId {
        TerrainSetDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: TerrainSetDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct TerrainSetUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for TerrainSetTableHandle<'ctx> {
    type UpdateCallbackId = TerrainSetUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> TerrainSetUpdateCallbackId {
        TerrainSetUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: TerrainSetUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `terrain_set_id` unique index on the table `terrain_set`,
/// which allows point queries on the field of the same name
/// via the [`TerrainSetTerrainSetIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.terrain_set().terrain_set_id().find(...)`.
pub struct TerrainSetTerrainSetIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<TerrainSet, u32>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> TerrainSetTableHandle<'ctx> {
    /// Get a handle on the `terrain_set_id` unique index on the table `terrain_set`.
    pub fn terrain_set_id(&self) -> TerrainSetTerrainSetIdUnique<'ctx> {
        TerrainSetTerrainSetIdUnique {
            imp: self.imp.get_unique_constraint::<u32>("terrain_set_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> TerrainSetTerrainSetIdUnique<'ctx> {
    /// Find the subscribed row whose `terrain_set_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u32) -> Option<TerrainSet> {
        self.imp.find(col_val)
    }
}

/// Access to the `name` unique index on the table `terrain_set`,
/// which allows point queries on the field of the same name
/// via the [`TerrainSetNameUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.terrain_set().name().find(...)`.
pub struct TerrainSetNameUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<TerrainSet, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> TerrainSetTableHandle<'ctx> {
    /// Get a handle on the `name` unique index on the table `terrain_set`.
    pub fn name(&self) -> TerrainSetNameUnique<'ctx> {
        TerrainSetNameUnique {
            imp: self.imp.get_unique_constraint::<String>("name"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> TerrainSetNameUnique<'ctx> {
    /// Find the subscribed row whose `name` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<TerrainSet> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<TerrainSet>("terrain_set");
    _table.add_unique_constraint::<u32>("terrain_set_id", |row| &row.terrain_set_id);
    _table.add_unique_constraint::<String>("name", |row| &row.name);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<TerrainSet>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<TerrainSet>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `TerrainSet`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait terrain_setQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `TerrainSet`.
    fn terrain_set(&self) -> __sdk::__query_builder::Table<TerrainSet>;
}

impl terrain_setQueryTableAccess for __sdk::QueryTableAccessor {
    fn terrain_set(&self) -> __sdk::__query_builder::Table<TerrainSet> {
        __sdk::__query_builder::Table::new("terrain_set")
    }
}
