// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::world_phase_type::WorldPhase;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `world_phase`.
///
/// Obtain a handle from the [`WorldPhaseTableAccess::world_phase`] method on [`super::RemoteTables`],
/// like `ctx.db.world_phase()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.world_phase().on_insert(...)`.
pub struct WorldPhaseTableHandle<'ctx> {
    imp: __sdk::TableHandle<WorldPhase>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `world_phase`.
///
/// Implemented for [`super::RemoteTables`].
pub trait WorldPhaseTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`WorldPhaseTableHandle`], which mediates access to the table `world_phase`.
    fn world_phase(&self) -> WorldPhaseTableHandle<'_>;
}

impl WorldPhaseTableAccess for super::RemoteTables {
    fn world_phase(&self) -> WorldPhaseTableHandle<'_> {
        WorldPhaseTableHandle {
            imp: self.imp.get_table::<WorldPhase>("world_phase"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct WorldPhaseInsertCallbackId(__sdk::CallbackId);
pub struct WorldPhaseDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for WorldPhaseTableHandle<'ctx> {
    type Row = WorldPhase;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = WorldPhase> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = WorldPhaseInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> WorldPhaseInsertCallbackId {
        WorldPhaseInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: WorldPhaseInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = WorldPhaseDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> WorldPhaseDeleteCallbackId {
        WorldPhaseDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: WorldPhaseDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct WorldPhaseUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for WorldPhaseTableHandle<'ctx> {
    type UpdateCallbackId = WorldPhaseUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> WorldPhaseUpdateCallbackId {
        WorldPhaseUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: WorldPhaseUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `zone_id` unique index on the table `world_phase`,
/// which allows point queries on the field of the same name
/// via the [`WorldPhaseZoneIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.world_phase().zone_id().find(...)`.
pub struct WorldPhaseZoneIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<WorldPhase, u32>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> WorldPhaseTableHandle<'ctx> {
    /// Get a handle on the `zone_id` unique index on the table `world_phase`.
    pub fn zone_id(&self) -> WorldPhaseZoneIdUnique<'ctx> {
        WorldPhaseZoneIdUnique {
            imp: self.imp.get_unique_constraint::<u32>("zone_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> WorldPhaseZoneIdUnique<'ctx> {
    /// Find the subscribed row whose `zone_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u32) -> Option<WorldPhase> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<WorldPhase>("world_phase");
    _table.add_unique_constraint::<u32>("zone_id", |row| &row.zone_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<WorldPhase>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<WorldPhase>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `WorldPhase`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait world_phaseQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `WorldPhase`.
    fn world_phase(&self) -> __sdk::__query_builder::Table<WorldPhase>;
}

impl world_phaseQueryTableAccess for __sdk::QueryTableAccessor {
    fn world_phase(&self) -> __sdk::__query_builder::Table<WorldPhase> {
        __sdk::__query_builder::Table::new("world_phase")
    }
}
