// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::world_event_kind_type::WorldEventKind;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct WorldEventInput {
    pub entity_id: u64,
    pub event_sequence: u32,
    pub event_kind: WorldEventKind,
}

impl __sdk::InModule for WorldEventInput {
    type Module = super::RemoteModule;
}
