// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct ZoneCounterDeltaInput {
    pub layer: u32,
    pub region_x: i32,
    pub region_z: i32,
    pub counter_name: String,
    pub delta: f64,
}

impl __sdk::InModule for ZoneCounterDeltaInput {
    type Module = super::RemoteModule;
}
