[package]
name = "server_module"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib"]

[features]
default = ["debug"]
debug = []

[dependencies]
game_schema = { workspace = true, features = ["spacetimedb"] }
spacetimedb = "2.0"
log = { workspace = true }
