[package]
name = "server_module"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib"]

[features]
default = ["debug"]
debug = []

[dependencies]
game_schema = { workspace = true, features = ["spacetimedb"] }
spacetimedb = { version = "2.1", features = ["unstable"] }
log = { workspace = true }
ron = { workspace = true }
serde = { workspace = true }
